target_os linux64
primary_requirement /nfs/sc/disks/swuser_work_jojones/21.1_b115/acds 

regtest_path regtest/ip/ethernet/alt_ethernet_crete_gdr/qhip/scripts/funct_deterministic/GDR_RUN  --topology=7 --type=GDR_DE --reg-custom-result-dir=GDR_e7
regtest_path regtest/ip/ethernet/alt_ethernet_crete_gdr/qhip/scripts/funct_deterministic/GDR_RUN  --topology=9 --type=GDR_DE --reg-custom-result-dir=GDR_e9
regtest_path regtest/ip/ethernet/alt_ethernet_crete_gdr/qhip/scripts/funct_deterministic/GDR_RUN  --topology=4 --type=GDR_DE --reg-custom-result-dir=GDR_e4
regtest_path regtest/ip/ethernet/alt_ethernet_crete_gdr/qhip/scripts/funct_deterministic/GDR_RUN  --topology=16 --type=GDR_DE --reg-custom-result-dir=GDR_e16
