// (C) 2001-2023 Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License Subscription 
// Agreement, Intel FPGA IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Intel and sold by 
// Intel or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


// avalon_st_adapter.v

// Generated using ACDS version 13.0 156 at 2013.05.13.13:46:40

`timescale 1 ps / 1 ps
module avalon_st_adapter (
		input  wire        avalon_st_tx_clk_clk,           //   avalon_st_tx_clk.clk
		input  wire        avalon_st_tx_reset_reset_n,     // avalon_st_tx_reset.reset_n
		output wire        avalon_st_tx_in_ready,          //    avalon_st_tx_in.ready
		input  wire        avalon_st_tx_in_valid,          //                   .valid
		input  wire [63:0] avalon_st_tx_in_data,           //                   .data
		input  wire        avalon_st_tx_in_error,          //                   .error
		input  wire        avalon_st_tx_in_startofpacket,  //                   .startofpacket
		input  wire        avalon_st_tx_in_endofpacket,    //                   .endofpacket
		input  wire [2:0]  avalon_st_tx_in_empty,          //                   .empty
		input  wire        avalon_st_tx_out_ready,         //   avalon_st_tx_out.ready
		output wire        avalon_st_tx_out_valid,         //                   .valid
		output wire [31:0] avalon_st_tx_out_data,          //                   .data
		output wire        avalon_st_tx_out_error,         //                   .error
		output wire        avalon_st_tx_out_startofpacket, //                   .startofpacket
		output wire        avalon_st_tx_out_endofpacket,   //                   .endofpacket
		output wire [1:0]  avalon_st_tx_out_empty,         //                   .empty
		input  wire        avalon_st_rx_clk_clk,           //   avalon_st_rx_clk.clk
		input  wire        avalon_st_rx_reset_reset_n,     // avalon_st_rx_reset.reset_n
		output wire        avalon_st_rx_in_ready,          //    avalon_st_rx_in.ready
		input  wire        avalon_st_rx_in_valid,          //                   .valid
		input  wire [31:0] avalon_st_rx_in_data,           //                   .data
		input  wire [5:0]  avalon_st_rx_in_error,          //                   .error
		input  wire        avalon_st_rx_in_startofpacket,  //                   .startofpacket
		input  wire        avalon_st_rx_in_endofpacket,    //                   .endofpacket
		input  wire [1:0]  avalon_st_rx_in_empty,          //                   .empty
		input  wire        avalon_st_rx_out_ready,         //   avalon_st_rx_out.ready
		output wire        avalon_st_rx_out_valid,         //                   .valid
		output wire [63:0] avalon_st_rx_out_data,          //                   .data
		output wire [5:0]  avalon_st_rx_out_error,         //                   .error
		output wire        avalon_st_rx_out_startofpacket, //                   .startofpacket
		output wire        avalon_st_rx_out_endofpacket,   //                   .endofpacket
		output wire [2:0]  avalon_st_rx_out_empty          //                   .empty
	);

	avalon_st_adapter_avalon_st_tx avalon_st_tx (
		.clk               (avalon_st_tx_clk_clk),           //   clk.clk
		.reset_n           (avalon_st_tx_reset_reset_n),     // reset.reset_n
		.in_ready          (avalon_st_tx_in_ready),          //    in.ready
		.in_valid          (avalon_st_tx_in_valid),          //      .valid
		.in_data           (avalon_st_tx_in_data),           //      .data
		.in_error          (avalon_st_tx_in_error),          //      .error
		.in_startofpacket  (avalon_st_tx_in_startofpacket),  //      .startofpacket
		.in_endofpacket    (avalon_st_tx_in_endofpacket),    //      .endofpacket
		.in_empty          (avalon_st_tx_in_empty),          //      .empty
		.out_ready         (avalon_st_tx_out_ready),         //   out.ready
		.out_valid         (avalon_st_tx_out_valid),         //      .valid
		.out_data          (avalon_st_tx_out_data),          //      .data
		.out_error         (avalon_st_tx_out_error),         //      .error
		.out_startofpacket (avalon_st_tx_out_startofpacket), //      .startofpacket
		.out_endofpacket   (avalon_st_tx_out_endofpacket),   //      .endofpacket
		.out_empty         (avalon_st_tx_out_empty)          //      .empty
	);

	avalon_st_adapter_avalon_st_rx avalon_st_rx (
		.clk               (avalon_st_rx_clk_clk),           //   clk.clk
		.reset_n           (avalon_st_rx_reset_reset_n),     // reset.reset_n
		.in_ready          (avalon_st_rx_in_ready),          //    in.ready
		.in_valid          (avalon_st_rx_in_valid),          //      .valid
		.in_data           (avalon_st_rx_in_data),           //      .data
		.in_error          (avalon_st_rx_in_error),          //      .error
		.in_startofpacket  (avalon_st_rx_in_startofpacket),  //      .startofpacket
		.in_endofpacket    (avalon_st_rx_in_endofpacket),    //      .endofpacket
		.in_empty          (avalon_st_rx_in_empty),          //      .empty
		.out_ready         (avalon_st_rx_out_ready),         //   out.ready
		.out_valid         (avalon_st_rx_out_valid),         //      .valid
		.out_data          (avalon_st_rx_out_data),          //      .data
		.out_error         (avalon_st_rx_out_error),         //      .error
		.out_startofpacket (avalon_st_rx_out_startofpacket), //      .startofpacket
		.out_endofpacket   (avalon_st_rx_out_endofpacket),   //      .endofpacket
		.out_empty         (avalon_st_rx_out_empty)          //      .empty
	);

endmodule
