// (C) 2001-2023 Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License Subscription 
// Agreement, Intel FPGA IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Intel and sold by 
// Intel or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


//------------------------------------------------------------------------------
// Copyright 2016 - Present Intel-PSG. All rights reserved.
//
// The source code contained or described herein and all documents related
// to the source code ("Material") are owned by Intel Corporation or its
// suppliers or licensors. Title to the Material remains with Intel
// Corporation or its suppliers and licensors. The Material contains trade
// secrets and proprietary and confidential information of Intel or its
// suppliers and licensors. The Material is protected by worldwide copyright
// and trade secret laws and treaty provisions. No part of the Material may
// be used; copied, reproduced, modified, published, uploaded, posted,
// transmitted; distributed, or disclosed in any way without Intel's prior
// express written permission.
//
// No license under any patent; copyright, trade secret or other intellectual
// property right is granted to or conferred upon you by disclosure or
// delivery of the Materials; either expressly, by implication, inducement,
// estoppel or otherwise. Any license under such intellectual property rights
// must be express and approved by Intel in writing.
//
//------------------------------------------------------------------------------
// Description:
//
//   UVM Register model autogenerated using "phv_di2uvm"
//
//------------------------------------------------------------------------------
// This file is autogenerated using phv_di2uvm@phv_tools/2020WW01.5
//
// @@@     @@   @   @ @@@@@  @   @   @@   @@@  @@@ @@@@@ @   @  @   @ @@@@@  @ @
// @  @   @  @  @@  @   @    @@@@@  @  @  @  @  @  @      @ @   @@@@@ @      @ @
// @   @ @    @ @ @ @   @    @ @ @ @    @ @   @ @  @@@@    @    @ @ @ @@@@   @ @
// @  @   @  @  @  @@   @    @   @  @  @  @  @  @  @       @    @   @ @
// @@@     @@   @   @   @    @   @   @@   @@@  @@@ @       @    @   @ @@@@@  @ @
//
//------------------------------------------------------------------------------

`ifndef __GDR_BARAK_QUAD_CFG_CTRL_URM_SVH__
`define __GDR_BARAK_QUAD_CFG_CTRL_URM_SVH__

//------------------------------------------------------------------------------
// Class: gdr_barak_quad_cfg_ctrl
//------------------------------------------------------------------------------
class gdr_barak_quad_cfg_ctrl_urm extends uvm_reg_block;
   `uvm_object_utils(gdr_barak_quad_cfg_ctrl_urm)

   //---------------------------------------------------------------------------
   // Group: Variables
   //---------------------------------------------------------------------------
   //
   // URM Sub-instance
   //
   rand gdr_barak_quad_avmm_cfgcsr_urm          u_gdr_barak_quad_avmm_cfgcsr;
   //
   // Knobs that can be used to disable the creation of the URM instance
   // Default is enabled!
   //
   bit                                          u_gdr_barak_quad_avmm_cfgcsr_disable;
   //
   // Address map instances
   //
   uvm_reg_map                                  config_map;

   //---------------------------------------------------------------------------
   // UVM Methods
   //---------------------------------------------------------------------------
   //
   // Function: new
   //    Class contructor
   //
   // Parameters:
   //    - name : class's string based name
   //
   function new (string n = "gdr_barak_quad_cfg_ctrl_urm");
      super.new(n, build_coverage(UVM_CVR_ALL));
   endfunction : new
   //
   // Function: build
   //    Build function
   //
   function void build();
      //
      // Create address map(s)
      //
      config_map  = create_map("config_map", `UVM_REG_ADDR_WIDTH'h0, 4, UVM_LITTLE_ENDIAN, 1);
      default_map = config_map;
      `uvm_info(get_type_name(), {"get_full_name() = ", get_full_name()}, UVM_MEDIUM)
      //
      // Construct Sub-URM instances
      //
      if (!uvm_config_db#(bit)::get(null, get_full_name(), "u_gdr_barak_quad_avmm_cfgcsr_disable", u_gdr_barak_quad_avmm_cfgcsr_disable))
      begin
         u_gdr_barak_quad_avmm_cfgcsr_disable = 0;
      end
      if (!u_gdr_barak_quad_avmm_cfgcsr_disable)
      begin
         u_gdr_barak_quad_avmm_cfgcsr = gdr_barak_quad_avmm_cfgcsr_urm::type_id::create("u_gdr_barak_quad_avmm_cfgcsr",,get_full_name());
         u_gdr_barak_quad_avmm_cfgcsr.configure(this);
         u_gdr_barak_quad_avmm_cfgcsr.build();
         config_map.add_submap(u_gdr_barak_quad_avmm_cfgcsr.config_map, `UVM_REG_ADDR_WIDTH'h00000000);
      end
      else
      begin
         u_gdr_barak_quad_avmm_cfgcsr.rand_mode(0);
      end
   endfunction : build
   //
   // Function : set_hdl_path_root
   // Override the base's set_hdl_path_root() and call the subsequent
   // URM block's set_hdl_path_root
   //
   function void set_hdl_path_root (string path, string kind = "RTL");
      super.set_hdl_path_root(path, kind);
      if (!u_gdr_barak_quad_avmm_cfgcsr_disable)
      begin
         u_gdr_barak_quad_avmm_cfgcsr.set_hdl_path_root({path, ".u_gdr_barak_quad_avmm_cfgcsr"}, kind);
      end
   endfunction : set_hdl_path_root

endclass : gdr_barak_quad_cfg_ctrl_urm

`endif//__GDR_BARAK_QUAD_CFG_CTRL_URM_SVH__
