// (C) 2001-2023 Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License Subscription 
// Agreement, Intel FPGA IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Intel and sold by 
// Intel or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


// megafunction wizard: %RAM: 2-PORT%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altera_syncram 

// ============================================================
// File Name: alt_em10g32_altsyncram.v
// Megafunction Name(s):
// 			altera_syncram
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 13.1.0 Internal Build 70 05/16/2013 PN Full Version
// ************************************************************


//Copyright (C) 1991-2013 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module alt_em10g32_altsyncram (
	data,
	rd_aclr,
	rdaddress,
	rdclock,
	rden,
	wraddress,
	wrclock,
	wren,
    eccstatus,
	q);

    // Parameters
    parameter DEVICE_FAMILY             = "Stratix V";
    parameter WIDTH                     = 32;
    parameter DEPTH                     = 32;
    parameter ENABLE_MEM_ECC            = 0;
    parameter ENABLE_ECC_PIPELINE_STAGE = 0;
    parameter REGISTERED_OUTPUT         = 0;
    parameter ADDRESS_WIDTH             = 5;
    parameter RAM_BLOCK_TYPE            = "M20K";
    
	input	[WIDTH-1:0]  data;
	input	  rd_aclr;
	input	[ADDRESS_WIDTH-1:0]  rdaddress;
	input	  rdclock;
	input	  rden;
	input	[ADDRESS_WIDTH-1:0]  wraddress;
	input	  wrclock;
	input	  wren;
    output	[1:0]  eccstatus;
	output	[WIDTH-1:0]  q;


	wire [WIDTH-1:0] sub_wire0;
	wire [WIDTH-1:0] q = sub_wire0[WIDTH-1:0];

    generate
    if (ENABLE_MEM_ECC == 1) begin: altsyncram_ecc_enable
        altera_syncram	altera_syncram_component (
                    .clock0 (wrclock),
                    .wren_a (wren),
                    .aclr1 (rd_aclr),
                    .address_b (rdaddress),
                    .clock1 (rdclock),
                    .address_a (wraddress),
                    .data_a (data),
                    .rden_b (rden),
                    .q_b (sub_wire0),
                    .aclr0 (1'b0),
                    .address2_a (1'b1),
                    .address2_b (1'b1),
                    .addressstall_a (1'b0),
                    .addressstall_b (1'b0),
                    .byteena_a (1'b1),
                    .byteena_b (1'b1),
                    .clocken0 (1'b1),
                    .clocken1 (1'b1),
                    .clocken2 (1'b1),
                    .clocken3 (1'b1),
                    .data_b ({WIDTH{1'b1}}),
                    .eccencbypass (1'b0),
                    .eccencparity ({8{1'b0}}),
                    .eccstatus (eccstatus),
                    .q_a (),
                    .rden_a (1'b1),
                    .sclr (1'b0),
                    .wren_b (1'b0));
        defparam
            altera_syncram_component.address_aclr_b = (DEVICE_FAMILY == "Stratix 10") ? "NONE" : "CLEAR1",
            altera_syncram_component.address_reg_b = "CLOCK1",
            altera_syncram_component.clock_enable_input_a = "BYPASS",
            altera_syncram_component.clock_enable_input_b = "BYPASS",
            altera_syncram_component.clock_enable_output_b = "BYPASS",
            altera_syncram_component.enable_ecc = "TRUE",
            altera_syncram_component.ecc_pipeline_stage_enabled = ENABLE_ECC_PIPELINE_STAGE ? "TRUE" : "FALSE",
            altera_syncram_component.intended_device_family = DEVICE_FAMILY,
            altera_syncram_component.lpm_type = "altera_syncram",
            altera_syncram_component.numwords_a = DEPTH,
            altera_syncram_component.numwords_b = DEPTH,
            altera_syncram_component.operation_mode = "DUAL_PORT",
            altera_syncram_component.outdata_aclr_b = "CLEAR1",
            altera_syncram_component.outdata_reg_b = REGISTERED_OUTPUT ? "CLOCK1" : "UNREGISTERED",
            altera_syncram_component.power_up_uninitialized = "TRUE",
            altera_syncram_component.ram_block_type = RAM_BLOCK_TYPE,
            altera_syncram_component.rdcontrol_reg_b = "CLOCK1",
            altera_syncram_component.widthad_a = ADDRESS_WIDTH,
            altera_syncram_component.widthad_b = ADDRESS_WIDTH,
            altera_syncram_component.width_a = WIDTH,
            altera_syncram_component.width_b = WIDTH,
            altera_syncram_component.width_byteena_a = 1,
            altera_syncram_component.width_eccstatus = 2;
    end
    else begin : altsyncram_ecc_disable
        altera_syncram	altera_syncram_component (
                .clock0 (wrclock),
                .wren_a (wren),
                .aclr1 (rd_aclr),
                .address_b (rdaddress),
                .clock1 (rdclock),
                .address_a (wraddress),
                .data_a (data),
                .rden_b (rden),
                .q_b (sub_wire0),
                .aclr0 (1'b0),
                .address2_a (1'b1),
                .address2_b (1'b1),
                .addressstall_a (1'b0),
                .addressstall_b (1'b0),
                .byteena_a (1'b1),
                .byteena_b (1'b1),
                .clocken0 (1'b1),
                .clocken1 (1'b1),
                .clocken2 (1'b1),
                .clocken3 (1'b1),
                .data_b ({WIDTH{1'b1}}),
                .eccencbypass (1'b0),
                .eccencparity ({8{1'b0}}),
                .q_a (),
                .rden_a (1'b1),
                .sclr (1'b0),
                .wren_b (1'b0));
        defparam
            altera_syncram_component.address_aclr_b = (DEVICE_FAMILY == "Stratix 10") ? "NONE" : "CLEAR1",
            altera_syncram_component.address_reg_b = "CLOCK1",
            altera_syncram_component.clock_enable_input_a = "BYPASS",
            altera_syncram_component.clock_enable_input_b = "BYPASS",
            altera_syncram_component.clock_enable_output_b = "BYPASS",
            altera_syncram_component.enable_ecc = "FALSE",
            altera_syncram_component.ecc_pipeline_stage_enabled = ENABLE_ECC_PIPELINE_STAGE ? "TRUE" : "FALSE",
            altera_syncram_component.intended_device_family = DEVICE_FAMILY,
            altera_syncram_component.lpm_type = "altera_syncram",
            altera_syncram_component.numwords_a = DEPTH,
            altera_syncram_component.numwords_b = DEPTH,
            altera_syncram_component.operation_mode = "DUAL_PORT",
            altera_syncram_component.outdata_aclr_b = "CLEAR1",
            altera_syncram_component.outdata_reg_b = REGISTERED_OUTPUT ? "CLOCK1" : "UNREGISTERED",
            altera_syncram_component.power_up_uninitialized = "TRUE",
            altera_syncram_component.ram_block_type = RAM_BLOCK_TYPE,
            altera_syncram_component.rdcontrol_reg_b = "CLOCK1",
            altera_syncram_component.widthad_a = ADDRESS_WIDTH,
            altera_syncram_component.widthad_b = ADDRESS_WIDTH,
            altera_syncram_component.width_a = WIDTH,
            altera_syncram_component.width_b = WIDTH,
            altera_syncram_component.width_byteena_a = 1,
            altera_syncram_component.width_eccstatus = 2;
        
        assign eccstatus = 2'd0;
    end
    endgenerate


endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ADDRESSSTALL_A NUMERIC "0"
// Retrieval info: PRIVATE: ADDRESSSTALL_B NUMERIC "0"
// Retrieval info: PRIVATE: BYTEENA_ACLR_A NUMERIC "0"
// Retrieval info: PRIVATE: BYTEENA_ACLR_B NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_ENABLE_A NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_ENABLE_B NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_SIZE NUMERIC "9"
// Retrieval info: PRIVATE: BlankMemory NUMERIC "1"
// Retrieval info: PRIVATE: CLOCK_ENABLE_INPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_INPUT_B NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_OUTPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_OUTPUT_B NUMERIC "0"
// Retrieval info: PRIVATE: CLRdata NUMERIC "0"
// Retrieval info: PRIVATE: CLRq NUMERIC "1"
// Retrieval info: PRIVATE: CLRrdaddress NUMERIC "1"
// Retrieval info: PRIVATE: CLRrren NUMERIC "0"
// Retrieval info: PRIVATE: CLRwraddress NUMERIC "0"
// Retrieval info: PRIVATE: CLRwren NUMERIC "0"
// Retrieval info: PRIVATE: Clock NUMERIC "1"
// Retrieval info: PRIVATE: Clock_A NUMERIC "0"
// Retrieval info: PRIVATE: Clock_B NUMERIC "0"
// Retrieval info: PRIVATE: IMPLEMENT_IN_LES NUMERIC "0"
// Retrieval info: PRIVATE: INDATA_ACLR_B NUMERIC "0"
// Retrieval info: PRIVATE: INDATA_REG_B NUMERIC "0"
// Retrieval info: PRIVATE: INIT_FILE_LAYOUT STRING "PORT_B"
// Retrieval info: PRIVATE: INIT_TO_SIM_X NUMERIC "1"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Stratix V"
// Retrieval info: PRIVATE: JTAG_ENABLED NUMERIC "0"
// Retrieval info: PRIVATE: JTAG_ID STRING "NONE"
// Retrieval info: PRIVATE: MAXIMUM_DEPTH NUMERIC "0"
// Retrieval info: PRIVATE: MEMSIZE NUMERIC "1152"
// Retrieval info: PRIVATE: MEM_IN_BITS NUMERIC "0"
// Retrieval info: PRIVATE: MIFfilename STRING ""
// Retrieval info: PRIVATE: OPERATION_MODE NUMERIC "2"
// Retrieval info: PRIVATE: OUTDATA_ACLR_B NUMERIC "1"
// Retrieval info: PRIVATE: OUTDATA_REG_B NUMERIC "0"
// Retrieval info: PRIVATE: RAM_BLOCK_TYPE NUMERIC "2"
// Retrieval info: PRIVATE: READ_DURING_WRITE_MODE_MIXED_PORTS NUMERIC "2"
// Retrieval info: PRIVATE: READ_DURING_WRITE_MODE_PORT_A NUMERIC "3"
// Retrieval info: PRIVATE: READ_DURING_WRITE_MODE_PORT_B NUMERIC "3"
// Retrieval info: PRIVATE: REGdata NUMERIC "1"
// Retrieval info: PRIVATE: REGq NUMERIC "0"
// Retrieval info: PRIVATE: REGrdaddress NUMERIC "1"
// Retrieval info: PRIVATE: REGrren NUMERIC "1"
// Retrieval info: PRIVATE: REGwraddress NUMERIC "1"
// Retrieval info: PRIVATE: REGwren NUMERIC "1"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "0"
// Retrieval info: PRIVATE: USE_DIFF_CLKEN NUMERIC "0"
// Retrieval info: PRIVATE: UseDPRAM NUMERIC "1"
// Retrieval info: PRIVATE: VarWidth NUMERIC "0"
// Retrieval info: PRIVATE: WIDTH_READ_A NUMERIC "36"
// Retrieval info: PRIVATE: WIDTH_READ_B NUMERIC "36"
// Retrieval info: PRIVATE: WIDTH_WRITE_A NUMERIC "36"
// Retrieval info: PRIVATE: WIDTH_WRITE_B NUMERIC "36"
// Retrieval info: PRIVATE: WRADDR_ACLR_B NUMERIC "0"
// Retrieval info: PRIVATE: WRADDR_REG_B NUMERIC "0"
// Retrieval info: PRIVATE: WRCTRL_ACLR_B NUMERIC "0"
// Retrieval info: PRIVATE: enable NUMERIC "0"
// Retrieval info: PRIVATE: rden NUMERIC "1"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: ADDRESS_ACLR_B STRING "CLEAR1"
// Retrieval info: CONSTANT: ADDRESS_REG_B STRING "CLOCK1"
// Retrieval info: CONSTANT: CLOCK_ENABLE_INPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: CLOCK_ENABLE_INPUT_B STRING "BYPASS"
// Retrieval info: CONSTANT: CLOCK_ENABLE_OUTPUT_B STRING "BYPASS"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Stratix V"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altera_syncram"
// Retrieval info: CONSTANT: NUMWORDS_A NUMERIC "32"
// Retrieval info: CONSTANT: NUMWORDS_B NUMERIC "32"
// Retrieval info: CONSTANT: OPERATION_MODE STRING "DUAL_PORT"
// Retrieval info: CONSTANT: OUTDATA_ACLR_B STRING "CLEAR1"
// Retrieval info: CONSTANT: OUTDATA_REG_B STRING "UNREGISTERED"
// Retrieval info: CONSTANT: POWER_UP_UNINITIALIZED STRING "TRUE"
// Retrieval info: CONSTANT: RAM_BLOCK_TYPE STRING "M20K"
// Retrieval info: CONSTANT: RDCONTROL_REG_B STRING "CLOCK1"
// Retrieval info: CONSTANT: WIDTHAD_A NUMERIC "5"
// Retrieval info: CONSTANT: WIDTHAD_B NUMERIC "5"
// Retrieval info: CONSTANT: WIDTH_A NUMERIC "36"
// Retrieval info: CONSTANT: WIDTH_B NUMERIC "36"
// Retrieval info: CONSTANT: WIDTH_BYTEENA_A NUMERIC "1"
// Retrieval info: USED_PORT: data 0 0 36 0 INPUT NODEFVAL "data[35..0]"
// Retrieval info: USED_PORT: q 0 0 36 0 OUTPUT NODEFVAL "q[35..0]"
// Retrieval info: USED_PORT: rd_aclr 0 0 0 0 INPUT GND "rd_aclr"
// Retrieval info: USED_PORT: rdaddress 0 0 5 0 INPUT NODEFVAL "rdaddress[4..0]"
// Retrieval info: USED_PORT: rdclock 0 0 0 0 INPUT NODEFVAL "rdclock"
// Retrieval info: USED_PORT: rden 0 0 0 0 INPUT VCC "rden"
// Retrieval info: USED_PORT: wraddress 0 0 5 0 INPUT NODEFVAL "wraddress[4..0]"
// Retrieval info: USED_PORT: wrclock 0 0 0 0 INPUT VCC "wrclock"
// Retrieval info: USED_PORT: wren 0 0 0 0 INPUT GND "wren"
// Retrieval info: CONNECT: @aclr1 0 0 0 0 rd_aclr 0 0 0 0
// Retrieval info: CONNECT: @address_a 0 0 5 0 wraddress 0 0 5 0
// Retrieval info: CONNECT: @address_b 0 0 5 0 rdaddress 0 0 5 0
// Retrieval info: CONNECT: @clock0 0 0 0 0 wrclock 0 0 0 0
// Retrieval info: CONNECT: @clock1 0 0 0 0 rdclock 0 0 0 0
// Retrieval info: CONNECT: @data_a 0 0 36 0 data 0 0 36 0
// Retrieval info: CONNECT: @rden_b 0 0 0 0 rden 0 0 0 0
// Retrieval info: CONNECT: @wren_a 0 0 0 0 wren 0 0 0 0
// Retrieval info: CONNECT: q 0 0 36 0 @q_b 0 0 36 0
// Retrieval info: GEN_FILE: TYPE_NORMAL alt_em10g32_altsyncram.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL alt_em10g32_altsyncram.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL alt_em10g32_altsyncram.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL alt_em10g32_altsyncram.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL alt_em10g32_altsyncram_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL alt_em10g32_altsyncram_bb.v FALSE
// Retrieval info: LIB_FILE: altera_mf
