// address_decode.v

// Generated using ACDS version 22.3 89

`timescale 1 ps / 1 ps
module address_decode (
		input  wire        clk_csr_clk,                                                 //                                         clk_csr.clk
		input  wire        csr_reset_n,                                                 //                                             csr.reset_n
		input  wire [15:0] merlin_master_translator_0_avalon_anti_master_0_address,     // merlin_master_translator_0_avalon_anti_master_0.address
		output wire        merlin_master_translator_0_avalon_anti_master_0_waitrequest, //                                                .waitrequest
		input  wire        merlin_master_translator_0_avalon_anti_master_0_read,        //                                                .read
		output wire [31:0] merlin_master_translator_0_avalon_anti_master_0_readdata,    //                                                .readdata
		input  wire        merlin_master_translator_0_avalon_anti_master_0_write,       //                                                .write
		input  wire [31:0] merlin_master_translator_0_avalon_anti_master_0_writedata,   //                                                .writedata
		output wire [12:0] mac_avalon_anti_slave_0_address,                             //                         mac_avalon_anti_slave_0.address
		output wire        mac_avalon_anti_slave_0_write,                               //                                                .write
		output wire        mac_avalon_anti_slave_0_read,                                //                                                .read
		input  wire [31:0] mac_avalon_anti_slave_0_readdata,                            //                                                .readdata
		output wire [31:0] mac_avalon_anti_slave_0_writedata,                           //                                                .writedata
		input  wire        mac_avalon_anti_slave_0_waitrequest,                         //                                                .waitrequest
		output wire [9:0]  phy_avalon_anti_slave_0_address,                             //                         phy_avalon_anti_slave_0.address
		output wire        phy_avalon_anti_slave_0_write,                               //                                                .write
		output wire        phy_avalon_anti_slave_0_read,                                //                                                .read
		input  wire [31:0] phy_avalon_anti_slave_0_readdata,                            //                                                .readdata
		output wire [31:0] phy_avalon_anti_slave_0_writedata,                           //                                                .writedata
		input  wire        phy_avalon_anti_slave_0_waitrequest                          //                                                .waitrequest
	);

	wire         clk_csr_clk_clk;                                                                    // clk_csr:clk_out -> [merlin_master_translator_0:clk, merlin_slave_translator_0:clk, merlin_slave_translator_1:clk, mm_interconnect_0:clk_csr_clk_clk]
	wire         clk_csr_clk_reset_reset;                                                            // clk_csr:reset_n_out -> [merlin_master_translator_0:reset, merlin_slave_translator_0:reset, merlin_slave_translator_1:reset, mm_interconnect_0:merlin_master_translator_0_reset_reset_bridge_in_reset_reset]
	wire         merlin_master_translator_0_avalon_universal_master_0_waitrequest;                   // mm_interconnect_0:merlin_master_translator_0_avalon_universal_master_0_waitrequest -> merlin_master_translator_0:uav_waitrequest
	wire  [31:0] merlin_master_translator_0_avalon_universal_master_0_readdata;                      // mm_interconnect_0:merlin_master_translator_0_avalon_universal_master_0_readdata -> merlin_master_translator_0:uav_readdata
	wire         merlin_master_translator_0_avalon_universal_master_0_debugaccess;                   // merlin_master_translator_0:uav_debugaccess -> mm_interconnect_0:merlin_master_translator_0_avalon_universal_master_0_debugaccess
	wire  [17:0] merlin_master_translator_0_avalon_universal_master_0_address;                       // merlin_master_translator_0:uav_address -> mm_interconnect_0:merlin_master_translator_0_avalon_universal_master_0_address
	wire         merlin_master_translator_0_avalon_universal_master_0_read;                          // merlin_master_translator_0:uav_read -> mm_interconnect_0:merlin_master_translator_0_avalon_universal_master_0_read
	wire   [3:0] merlin_master_translator_0_avalon_universal_master_0_byteenable;                    // merlin_master_translator_0:uav_byteenable -> mm_interconnect_0:merlin_master_translator_0_avalon_universal_master_0_byteenable
	wire         merlin_master_translator_0_avalon_universal_master_0_readdatavalid;                 // mm_interconnect_0:merlin_master_translator_0_avalon_universal_master_0_readdatavalid -> merlin_master_translator_0:uav_readdatavalid
	wire         merlin_master_translator_0_avalon_universal_master_0_lock;                          // merlin_master_translator_0:uav_lock -> mm_interconnect_0:merlin_master_translator_0_avalon_universal_master_0_lock
	wire         merlin_master_translator_0_avalon_universal_master_0_write;                         // merlin_master_translator_0:uav_write -> mm_interconnect_0:merlin_master_translator_0_avalon_universal_master_0_write
	wire  [31:0] merlin_master_translator_0_avalon_universal_master_0_writedata;                     // merlin_master_translator_0:uav_writedata -> mm_interconnect_0:merlin_master_translator_0_avalon_universal_master_0_writedata
	wire   [9:0] merlin_master_translator_0_avalon_universal_master_0_burstcount;                    // merlin_master_translator_0:uav_burstcount -> mm_interconnect_0:merlin_master_translator_0_avalon_universal_master_0_burstcount
	wire  [31:0] mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_readdata;      // merlin_slave_translator_0:uav_readdata -> mm_interconnect_0:merlin_slave_translator_0_avalon_universal_slave_0_readdata
	wire         mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_waitrequest;   // merlin_slave_translator_0:uav_waitrequest -> mm_interconnect_0:merlin_slave_translator_0_avalon_universal_slave_0_waitrequest
	wire         mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_debugaccess;   // mm_interconnect_0:merlin_slave_translator_0_avalon_universal_slave_0_debugaccess -> merlin_slave_translator_0:uav_debugaccess
	wire  [14:0] mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_address;       // mm_interconnect_0:merlin_slave_translator_0_avalon_universal_slave_0_address -> merlin_slave_translator_0:uav_address
	wire         mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_read;          // mm_interconnect_0:merlin_slave_translator_0_avalon_universal_slave_0_read -> merlin_slave_translator_0:uav_read
	wire   [3:0] mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_byteenable;    // mm_interconnect_0:merlin_slave_translator_0_avalon_universal_slave_0_byteenable -> merlin_slave_translator_0:uav_byteenable
	wire         mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_readdatavalid; // merlin_slave_translator_0:uav_readdatavalid -> mm_interconnect_0:merlin_slave_translator_0_avalon_universal_slave_0_readdatavalid
	wire         mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_lock;          // mm_interconnect_0:merlin_slave_translator_0_avalon_universal_slave_0_lock -> merlin_slave_translator_0:uav_lock
	wire         mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_write;         // mm_interconnect_0:merlin_slave_translator_0_avalon_universal_slave_0_write -> merlin_slave_translator_0:uav_write
	wire  [31:0] mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_writedata;     // mm_interconnect_0:merlin_slave_translator_0_avalon_universal_slave_0_writedata -> merlin_slave_translator_0:uav_writedata
	wire   [3:0] mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_burstcount;    // mm_interconnect_0:merlin_slave_translator_0_avalon_universal_slave_0_burstcount -> merlin_slave_translator_0:uav_burstcount
	wire  [31:0] mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_readdata;      // merlin_slave_translator_1:uav_readdata -> mm_interconnect_0:merlin_slave_translator_1_avalon_universal_slave_0_readdata
	wire         mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_waitrequest;   // merlin_slave_translator_1:uav_waitrequest -> mm_interconnect_0:merlin_slave_translator_1_avalon_universal_slave_0_waitrequest
	wire         mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_debugaccess;   // mm_interconnect_0:merlin_slave_translator_1_avalon_universal_slave_0_debugaccess -> merlin_slave_translator_1:uav_debugaccess
	wire  [16:0] mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_address;       // mm_interconnect_0:merlin_slave_translator_1_avalon_universal_slave_0_address -> merlin_slave_translator_1:uav_address
	wire         mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_read;          // mm_interconnect_0:merlin_slave_translator_1_avalon_universal_slave_0_read -> merlin_slave_translator_1:uav_read
	wire   [3:0] mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_byteenable;    // mm_interconnect_0:merlin_slave_translator_1_avalon_universal_slave_0_byteenable -> merlin_slave_translator_1:uav_byteenable
	wire         mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_readdatavalid; // merlin_slave_translator_1:uav_readdatavalid -> mm_interconnect_0:merlin_slave_translator_1_avalon_universal_slave_0_readdatavalid
	wire         mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_lock;          // mm_interconnect_0:merlin_slave_translator_1_avalon_universal_slave_0_lock -> merlin_slave_translator_1:uav_lock
	wire         mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_write;         // mm_interconnect_0:merlin_slave_translator_1_avalon_universal_slave_0_write -> merlin_slave_translator_1:uav_write
	wire  [31:0] mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_writedata;     // mm_interconnect_0:merlin_slave_translator_1_avalon_universal_slave_0_writedata -> merlin_slave_translator_1:uav_writedata
	wire   [3:0] mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_burstcount;    // mm_interconnect_0:merlin_slave_translator_1_avalon_universal_slave_0_burstcount -> merlin_slave_translator_1:uav_burstcount

	address_decode_clk_csr clk_csr (
		.clk_out     (clk_csr_clk_clk),         //  output,  width = 1,          clk.clk
		.in_clk      (clk_csr_clk),             //   input,  width = 1,       clk_in.clk
		.reset_n     (csr_reset_n),             //   input,  width = 1, clk_in_reset.reset_n
		.reset_n_out (clk_csr_clk_reset_reset)  //  output,  width = 1,    clk_reset.reset_n
	);

	address_decode_merlin_master_translator_0 merlin_master_translator_0 (
		.av_address        (merlin_master_translator_0_avalon_anti_master_0_address),            //   input,  width = 16,      avalon_anti_master_0.address
		.av_waitrequest    (merlin_master_translator_0_avalon_anti_master_0_waitrequest),        //  output,   width = 1,                          .waitrequest
		.av_read           (merlin_master_translator_0_avalon_anti_master_0_read),               //   input,   width = 1,                          .read
		.av_readdata       (merlin_master_translator_0_avalon_anti_master_0_readdata),           //  output,  width = 32,                          .readdata
		.av_write          (merlin_master_translator_0_avalon_anti_master_0_write),              //   input,   width = 1,                          .write
		.av_writedata      (merlin_master_translator_0_avalon_anti_master_0_writedata),          //   input,  width = 32,                          .writedata
		.uav_address       (merlin_master_translator_0_avalon_universal_master_0_address),       //  output,  width = 18, avalon_universal_master_0.address
		.uav_burstcount    (merlin_master_translator_0_avalon_universal_master_0_burstcount),    //  output,  width = 10,                          .burstcount
		.uav_read          (merlin_master_translator_0_avalon_universal_master_0_read),          //  output,   width = 1,                          .read
		.uav_write         (merlin_master_translator_0_avalon_universal_master_0_write),         //  output,   width = 1,                          .write
		.uav_waitrequest   (merlin_master_translator_0_avalon_universal_master_0_waitrequest),   //   input,   width = 1,                          .waitrequest
		.uav_readdatavalid (merlin_master_translator_0_avalon_universal_master_0_readdatavalid), //   input,   width = 1,                          .readdatavalid
		.uav_byteenable    (merlin_master_translator_0_avalon_universal_master_0_byteenable),    //  output,   width = 4,                          .byteenable
		.uav_readdata      (merlin_master_translator_0_avalon_universal_master_0_readdata),      //   input,  width = 32,                          .readdata
		.uav_writedata     (merlin_master_translator_0_avalon_universal_master_0_writedata),     //  output,  width = 32,                          .writedata
		.uav_lock          (merlin_master_translator_0_avalon_universal_master_0_lock),          //  output,   width = 1,                          .lock
		.uav_debugaccess   (merlin_master_translator_0_avalon_universal_master_0_debugaccess),   //  output,   width = 1,                          .debugaccess
		.clk               (clk_csr_clk_clk),                                                    //   input,   width = 1,                       clk.clk
		.reset             (~clk_csr_clk_reset_reset)                                            //   input,   width = 1,                     reset.reset
	);

	address_decode_merlin_slave_translator_0 merlin_slave_translator_0 (
		.av_address        (mac_avalon_anti_slave_0_address),                                                    //  output,  width = 13,      avalon_anti_slave_0.address
		.av_write          (mac_avalon_anti_slave_0_write),                                                      //  output,   width = 1,                         .write
		.av_read           (mac_avalon_anti_slave_0_read),                                                       //  output,   width = 1,                         .read
		.av_readdata       (mac_avalon_anti_slave_0_readdata),                                                   //   input,  width = 32,                         .readdata
		.av_writedata      (mac_avalon_anti_slave_0_writedata),                                                  //  output,  width = 32,                         .writedata
		.av_waitrequest    (mac_avalon_anti_slave_0_waitrequest),                                                //   input,   width = 1,                         .waitrequest
		.uav_address       (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_address),       //   input,  width = 15, avalon_universal_slave_0.address
		.uav_burstcount    (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_burstcount),    //   input,   width = 4,                         .burstcount
		.uav_read          (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_read),          //   input,   width = 1,                         .read
		.uav_write         (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_write),         //   input,   width = 1,                         .write
		.uav_waitrequest   (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_waitrequest),   //  output,   width = 1,                         .waitrequest
		.uav_readdatavalid (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_readdatavalid), //  output,   width = 1,                         .readdatavalid
		.uav_byteenable    (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_byteenable),    //   input,   width = 4,                         .byteenable
		.uav_readdata      (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_readdata),      //  output,  width = 32,                         .readdata
		.uav_writedata     (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_writedata),     //   input,  width = 32,                         .writedata
		.uav_lock          (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_lock),          //   input,   width = 1,                         .lock
		.uav_debugaccess   (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_debugaccess),   //   input,   width = 1,                         .debugaccess
		.clk               (clk_csr_clk_clk),                                                                    //   input,   width = 1,                      clk.clk
		.reset             (~clk_csr_clk_reset_reset)                                                            //   input,   width = 1,                    reset.reset
	);

	address_decode_merlin_slave_translator_1 merlin_slave_translator_1 (
		.av_address        (phy_avalon_anti_slave_0_address),                                                    //  output,  width = 10,      avalon_anti_slave_0.address
		.av_write          (phy_avalon_anti_slave_0_write),                                                      //  output,   width = 1,                         .write
		.av_read           (phy_avalon_anti_slave_0_read),                                                       //  output,   width = 1,                         .read
		.av_readdata       (phy_avalon_anti_slave_0_readdata),                                                   //   input,  width = 32,                         .readdata
		.av_writedata      (phy_avalon_anti_slave_0_writedata),                                                  //  output,  width = 32,                         .writedata
		.av_waitrequest    (phy_avalon_anti_slave_0_waitrequest),                                                //   input,   width = 1,                         .waitrequest
		.uav_address       (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_address),       //   input,  width = 17, avalon_universal_slave_0.address
		.uav_burstcount    (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_burstcount),    //   input,   width = 4,                         .burstcount
		.uav_read          (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_read),          //   input,   width = 1,                         .read
		.uav_write         (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_write),         //   input,   width = 1,                         .write
		.uav_waitrequest   (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_waitrequest),   //  output,   width = 1,                         .waitrequest
		.uav_readdatavalid (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_readdatavalid), //  output,   width = 1,                         .readdatavalid
		.uav_byteenable    (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_byteenable),    //   input,   width = 4,                         .byteenable
		.uav_readdata      (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_readdata),      //  output,  width = 32,                         .readdata
		.uav_writedata     (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_writedata),     //   input,  width = 32,                         .writedata
		.uav_lock          (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_lock),          //   input,   width = 1,                         .lock
		.uav_debugaccess   (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_debugaccess),   //   input,   width = 1,                         .debugaccess
		.clk               (clk_csr_clk_clk),                                                                    //   input,   width = 1,                      clk.clk
		.reset             (~clk_csr_clk_reset_reset)                                                            //   input,   width = 1,                    reset.reset
	);

	address_decode_altera_mm_interconnect_1920_ly4woyi mm_interconnect_0 (
		.merlin_master_translator_0_avalon_universal_master_0_address       (merlin_master_translator_0_avalon_universal_master_0_address),                       //   input,  width = 18,   merlin_master_translator_0_avalon_universal_master_0.address
		.merlin_master_translator_0_avalon_universal_master_0_waitrequest   (merlin_master_translator_0_avalon_universal_master_0_waitrequest),                   //  output,   width = 1,                                                       .waitrequest
		.merlin_master_translator_0_avalon_universal_master_0_burstcount    (merlin_master_translator_0_avalon_universal_master_0_burstcount),                    //   input,  width = 10,                                                       .burstcount
		.merlin_master_translator_0_avalon_universal_master_0_byteenable    (merlin_master_translator_0_avalon_universal_master_0_byteenable),                    //   input,   width = 4,                                                       .byteenable
		.merlin_master_translator_0_avalon_universal_master_0_read          (merlin_master_translator_0_avalon_universal_master_0_read),                          //   input,   width = 1,                                                       .read
		.merlin_master_translator_0_avalon_universal_master_0_readdata      (merlin_master_translator_0_avalon_universal_master_0_readdata),                      //  output,  width = 32,                                                       .readdata
		.merlin_master_translator_0_avalon_universal_master_0_readdatavalid (merlin_master_translator_0_avalon_universal_master_0_readdatavalid),                 //  output,   width = 1,                                                       .readdatavalid
		.merlin_master_translator_0_avalon_universal_master_0_write         (merlin_master_translator_0_avalon_universal_master_0_write),                         //   input,   width = 1,                                                       .write
		.merlin_master_translator_0_avalon_universal_master_0_writedata     (merlin_master_translator_0_avalon_universal_master_0_writedata),                     //   input,  width = 32,                                                       .writedata
		.merlin_master_translator_0_avalon_universal_master_0_lock          (merlin_master_translator_0_avalon_universal_master_0_lock),                          //   input,   width = 1,                                                       .lock
		.merlin_master_translator_0_avalon_universal_master_0_debugaccess   (merlin_master_translator_0_avalon_universal_master_0_debugaccess),                   //   input,   width = 1,                                                       .debugaccess
		.merlin_slave_translator_0_avalon_universal_slave_0_address         (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_address),       //  output,  width = 15,     merlin_slave_translator_0_avalon_universal_slave_0.address
		.merlin_slave_translator_0_avalon_universal_slave_0_write           (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_write),         //  output,   width = 1,                                                       .write
		.merlin_slave_translator_0_avalon_universal_slave_0_read            (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_read),          //  output,   width = 1,                                                       .read
		.merlin_slave_translator_0_avalon_universal_slave_0_readdata        (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_readdata),      //   input,  width = 32,                                                       .readdata
		.merlin_slave_translator_0_avalon_universal_slave_0_writedata       (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_writedata),     //  output,  width = 32,                                                       .writedata
		.merlin_slave_translator_0_avalon_universal_slave_0_burstcount      (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_burstcount),    //  output,   width = 4,                                                       .burstcount
		.merlin_slave_translator_0_avalon_universal_slave_0_byteenable      (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_byteenable),    //  output,   width = 4,                                                       .byteenable
		.merlin_slave_translator_0_avalon_universal_slave_0_readdatavalid   (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_readdatavalid), //   input,   width = 1,                                                       .readdatavalid
		.merlin_slave_translator_0_avalon_universal_slave_0_waitrequest     (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_waitrequest),   //   input,   width = 1,                                                       .waitrequest
		.merlin_slave_translator_0_avalon_universal_slave_0_lock            (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_lock),          //  output,   width = 1,                                                       .lock
		.merlin_slave_translator_0_avalon_universal_slave_0_debugaccess     (mm_interconnect_0_merlin_slave_translator_0_avalon_universal_slave_0_debugaccess),   //  output,   width = 1,                                                       .debugaccess
		.merlin_slave_translator_1_avalon_universal_slave_0_address         (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_address),       //  output,  width = 17,     merlin_slave_translator_1_avalon_universal_slave_0.address
		.merlin_slave_translator_1_avalon_universal_slave_0_write           (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_write),         //  output,   width = 1,                                                       .write
		.merlin_slave_translator_1_avalon_universal_slave_0_read            (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_read),          //  output,   width = 1,                                                       .read
		.merlin_slave_translator_1_avalon_universal_slave_0_readdata        (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_readdata),      //   input,  width = 32,                                                       .readdata
		.merlin_slave_translator_1_avalon_universal_slave_0_writedata       (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_writedata),     //  output,  width = 32,                                                       .writedata
		.merlin_slave_translator_1_avalon_universal_slave_0_burstcount      (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_burstcount),    //  output,   width = 4,                                                       .burstcount
		.merlin_slave_translator_1_avalon_universal_slave_0_byteenable      (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_byteenable),    //  output,   width = 4,                                                       .byteenable
		.merlin_slave_translator_1_avalon_universal_slave_0_readdatavalid   (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_readdatavalid), //   input,   width = 1,                                                       .readdatavalid
		.merlin_slave_translator_1_avalon_universal_slave_0_waitrequest     (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_waitrequest),   //   input,   width = 1,                                                       .waitrequest
		.merlin_slave_translator_1_avalon_universal_slave_0_lock            (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_lock),          //  output,   width = 1,                                                       .lock
		.merlin_slave_translator_1_avalon_universal_slave_0_debugaccess     (mm_interconnect_0_merlin_slave_translator_1_avalon_universal_slave_0_debugaccess),   //  output,   width = 1,                                                       .debugaccess
		.merlin_master_translator_0_reset_reset_bridge_in_reset_reset       (~clk_csr_clk_reset_reset),                                                           //   input,   width = 1, merlin_master_translator_0_reset_reset_bridge_in_reset.reset
		.clk_csr_clk_clk                                                    (clk_csr_clk_clk)                                                                     //   input,   width = 1,                                            clk_csr_clk.clk
	);

endmodule
