${REG_LOCAL_ROOT_DIR_PATH}/design/rtl/sm_tsn_cfg3_top/hps_axi_bridge/hps_axi_bridge.v      
${REG_LOCAL_ROOT_DIR_PATH}/design/rtl/sm_tsn_cfg3_top/rst_ctrl/ipbb_asyn_to_syn_rst.sv
#${REG_LOCAL_ROOT_DIR_PATH}/design/rtl/sm_tsn_cfg3_top/rst_ctrl/rst_ctrl.sv
${REG_LOCAL_ROOT_DIR_PATH}/GHRD_CONCURRENT/custom_ip/rst_ctrl.sv      
#${REG_LOCAL_ROOT_DIR_PATH}/design/rtl/sm_tsn_cfg3_top/user_space_csr/user_csr_space.v
#${REG_LOCAL_ROOT_DIR_PATH}/design/rtl/sm_tsn_cfg3_top/user_space_csr/csr_shell.sv
${REG_LOCAL_ROOT_DIR_PATH}/GHRD_CONCURRENT/custom_ip/user_csr_space.v      
${REG_LOCAL_ROOT_DIR_PATH}/GHRD_CONCURRENT/custom_ip/csr_shell.sv      
${REG_LOCAL_ROOT_DIR_PATH}/design/rtl/sm_tsn_cfg3_top/tsn_shell.sv
${REG_LOCAL_ROOT_DIR_PATH}/design/rtl/sm_tsn_cfg3_top/hps_subsys/hps_subsys.v
${REG_LOCAL_ROOT_DIR_PATH}/GHRD_CONCURRENT/qsys_top/altera_merlin_axi_translator_1931/synth/qsys_top_altera_merlin_axi_translator_1931_d46vvwa.sv
${REG_LOCAL_ROOT_DIR_PATH}/GHRD_CONCURRENT/qsys_top/altera_mm_interconnect_1920/synth/qsys_top_altera_mm_interconnect_1920_xdtjoey.v      
${REG_LOCAL_ROOT_DIR_PATH}/GHRD_CONCURRENT/qsys_top/altera_mm_interconnect_1920/sim/qsys_top_altera_mm_interconnect_1920_co5livq.v      
${REG_LOCAL_ROOT_DIR_PATH}/GHRD_CONCURRENT/qsys_top/altera_reset_controller_1922/synth/altera_reset_controller.v
${REG_LOCAL_ROOT_DIR_PATH}/GHRD_CONCURRENT/qsys_top/altera_reset_controller_1922/synth/altera_reset_synchronizer.v      
${REG_LOCAL_ROOT_DIR_PATH}/GHRD_CONCURRENT/qsys_top/synth/qsys_top.v      
${REG_LOCAL_ROOT_DIR_PATH}/GHRD_CONCURRENT/ghrd_agilex5_top.v      
