// hps_subsys.v

// Generated using ACDS version 23.4.1 162

`timescale 1 ps / 1 ps
module hps_subsys (
		output wire        h2f_reset_reset_n,               //               h2f_reset.reset_n
		input  wire        lwhps2fpga_clk_clk,              //          lwhps2fpga_clk.clk
		input  wire        lwhps2fpga_rst_reset_n,          //          lwhps2fpga_rst.reset_n
		output wire [3:0]  lwhps2fpga_awid,                 //              lwhps2fpga.awid
		output wire [28:0] lwhps2fpga_awaddr,               //                        .awaddr
		output wire [7:0]  lwhps2fpga_awlen,                //                        .awlen
		output wire [2:0]  lwhps2fpga_awsize,               //                        .awsize
		output wire [1:0]  lwhps2fpga_awburst,              //                        .awburst
		output wire        lwhps2fpga_awlock,               //                        .awlock
		output wire [3:0]  lwhps2fpga_awcache,              //                        .awcache
		output wire [2:0]  lwhps2fpga_awprot,               //                        .awprot
		output wire        lwhps2fpga_awvalid,              //                        .awvalid
		input  wire        lwhps2fpga_awready,              //                        .awready
		output wire [31:0] lwhps2fpga_wdata,                //                        .wdata
		output wire [3:0]  lwhps2fpga_wstrb,                //                        .wstrb
		output wire        lwhps2fpga_wlast,                //                        .wlast
		output wire        lwhps2fpga_wvalid,               //                        .wvalid
		input  wire        lwhps2fpga_wready,               //                        .wready
		input  wire [3:0]  lwhps2fpga_bid,                  //                        .bid
		input  wire [1:0]  lwhps2fpga_bresp,                //                        .bresp
		input  wire        lwhps2fpga_bvalid,               //                        .bvalid
		output wire        lwhps2fpga_bready,               //                        .bready
		output wire [3:0]  lwhps2fpga_arid,                 //                        .arid
		output wire [28:0] lwhps2fpga_araddr,               //                        .araddr
		output wire [7:0]  lwhps2fpga_arlen,                //                        .arlen
		output wire [2:0]  lwhps2fpga_arsize,               //                        .arsize
		output wire [1:0]  lwhps2fpga_arburst,              //                        .arburst
		output wire        lwhps2fpga_arlock,               //                        .arlock
		output wire [3:0]  lwhps2fpga_arcache,              //                        .arcache
		output wire [2:0]  lwhps2fpga_arprot,               //                        .arprot
		output wire        lwhps2fpga_arvalid,              //                        .arvalid
		input  wire        lwhps2fpga_arready,              //                        .arready
		input  wire [3:0]  lwhps2fpga_rid,                  //                        .rid
		input  wire [31:0] lwhps2fpga_rdata,                //                        .rdata
		input  wire [1:0]  lwhps2fpga_rresp,                //                        .rresp
		input  wire        lwhps2fpga_rlast,                //                        .rlast
		input  wire        lwhps2fpga_rvalid,               //                        .rvalid
		output wire        lwhps2fpga_rready,               //                        .rready
		input  wire        emac_ptp_clk_clk,                //            emac_ptp_clk.clk
		input  wire        emac_timestamp_clk_clk,          //      emac_timestamp_clk.clk
		input  wire        emac0_ptp_mac_ptp_trig,          //               emac0_ptp.mac_ptp_trig
		output wire        emac0_ptp_mac_ptp_pps,           //                        .mac_ptp_pps
		output wire        emac0_ptp_mac_ptp_tstmp_data,    //                        .mac_ptp_tstmp_data
		output wire        emac0_ptp_mac_ptp_tstmp_en,      //                        .mac_ptp_tstmp_en
		output wire        emac0_mac_tx_clk_o,              //                   emac0.mac_tx_clk_o
		input  wire        emac0_mac_tx_clk_i,              //                        .mac_tx_clk_i
		input  wire        emac0_mac_rx_clk,                //                        .mac_rx_clk
		output wire        emac0_mac_rst_tx_n,              //                        .mac_rst_tx_n
		output wire        emac0_mac_rst_rx_n,              //                        .mac_rst_rx_n
		output wire        emac0_mac_txen,                  //                        .mac_txen
		output wire        emac0_mac_txer,                  //                        .mac_txer
		input  wire        emac0_mac_rxdv,                  //                        .mac_rxdv
		input  wire        emac0_mac_rxer,                  //                        .mac_rxer
		input  wire [7:0]  emac0_mac_rxd,                   //                        .mac_rxd
		input  wire        emac0_mac_col,                   //                        .mac_col
		input  wire        emac0_mac_crs,                   //                        .mac_crs
		output wire [2:0]  emac0_mac_speed,                 //                        .mac_speed
		output wire [7:0]  emac0_mac_txd_o,                 //                        .mac_txd_o
		input  wire        emac1_ptp_mac_ptp_trig,          //               emac1_ptp.mac_ptp_trig
		output wire        emac1_ptp_mac_ptp_pps,           //                        .mac_ptp_pps
		output wire        emac1_ptp_mac_ptp_tstmp_data,    //                        .mac_ptp_tstmp_data
		output wire        emac1_ptp_mac_ptp_tstmp_en,      //                        .mac_ptp_tstmp_en
		output wire        emac1_mac_tx_clk_o,              //                   emac1.mac_tx_clk_o
		input  wire        emac1_mac_tx_clk_i,              //                        .mac_tx_clk_i
		input  wire        emac1_mac_rx_clk,                //                        .mac_rx_clk
		output wire        emac1_mac_rst_tx_n,              //                        .mac_rst_tx_n
		output wire        emac1_mac_rst_rx_n,              //                        .mac_rst_rx_n
		output wire        emac1_mac_txen,                  //                        .mac_txen
		output wire        emac1_mac_txer,                  //                        .mac_txer
		input  wire        emac1_mac_rxdv,                  //                        .mac_rxdv
		input  wire        emac1_mac_rxer,                  //                        .mac_rxer
		input  wire [7:0]  emac1_mac_rxd,                   //                        .mac_rxd
		input  wire        emac1_mac_col,                   //                        .mac_col
		input  wire        emac1_mac_crs,                   //                        .mac_crs
		output wire [2:0]  emac1_mac_speed,                 //                        .mac_speed
		output wire [7:0]  emac1_mac_txd_o,                 //                        .mac_txd_o
		input  wire        emac2_ptp_mac_ptp_trig,          //               emac2_ptp.mac_ptp_trig
		output wire        emac2_ptp_mac_ptp_pps,           //                        .mac_ptp_pps
		output wire        emac2_ptp_mac_ptp_tstmp_data,    //                        .mac_ptp_tstmp_data
		output wire        emac2_ptp_mac_ptp_tstmp_en,      //                        .mac_ptp_tstmp_en
		output wire        emac2_mac_tx_clk_o,              //                   emac2.mac_tx_clk_o
		input  wire        emac2_mac_tx_clk_i,              //                        .mac_tx_clk_i
		input  wire        emac2_mac_rx_clk,                //                        .mac_rx_clk
		output wire        emac2_mac_rst_tx_n,              //                        .mac_rst_tx_n
		output wire        emac2_mac_rst_rx_n,              //                        .mac_rst_rx_n
		output wire        emac2_mac_txen,                  //                        .mac_txen
		output wire        emac2_mac_txer,                  //                        .mac_txer
		input  wire        emac2_mac_rxdv,                  //                        .mac_rxdv
		input  wire        emac2_mac_rxer,                  //                        .mac_rxer
		input  wire [7:0]  emac2_mac_rxd,                   //                        .mac_rxd
		input  wire        emac2_mac_col,                   //                        .mac_col
		input  wire        emac2_mac_crs,                   //                        .mac_crs
		output wire [2:0]  emac2_mac_speed,                 //                        .mac_speed
		output wire [7:0]  emac2_mac_txd_o,                 //                        .mac_txd_o
		input  wire        hps_io_hps_osc_clk,              //                  hps_io.hps_osc_clk
		input  wire [63:0] fpga2hps_interrupt_irq,          //      fpga2hps_interrupt.irq
		output wire        emif_hps_emif_mem_0_mem_ck_t,    //     emif_hps_emif_mem_0.mem_ck_t
		output wire        emif_hps_emif_mem_0_mem_ck_c,    //                        .mem_ck_c
		output wire        emif_hps_emif_mem_0_mem_cke,     //                        .mem_cke
		output wire        emif_hps_emif_mem_0_mem_odt,     //                        .mem_odt
		output wire        emif_hps_emif_mem_0_mem_cs_n,    //                        .mem_cs_n
		output wire [16:0] emif_hps_emif_mem_0_mem_a,       //                        .mem_a
		output wire [1:0]  emif_hps_emif_mem_0_mem_ba,      //                        .mem_ba
		output wire        emif_hps_emif_mem_0_mem_bg,      //                        .mem_bg
		output wire        emif_hps_emif_mem_0_mem_act_n,   //                        .mem_act_n
		output wire        emif_hps_emif_mem_0_mem_par,     //                        .mem_par
		input  wire        emif_hps_emif_mem_0_mem_alert_n, //                        .mem_alert_n
		output wire        emif_hps_emif_mem_0_mem_reset_n, //                        .mem_reset_n
		inout  wire [31:0] emif_hps_emif_mem_0_mem_dq,      //                        .mem_dq
		inout  wire [3:0]  emif_hps_emif_mem_0_mem_dqs_t,   //                        .mem_dqs_t
		inout  wire [3:0]  emif_hps_emif_mem_0_mem_dqs_c,   //                        .mem_dqs_c
		input  wire        emif_hps_emif_oct_0_oct_rzqin,   //     emif_hps_emif_oct_0.oct_rzqin
		input  wire        emif_hps_emif_ref_clk_0_clk,     // emif_hps_emif_ref_clk_0.clk
		input  wire        clk_clk,                         //                     clk.clk
		input  wire        reset_reset_n                    //                   reset.reset_n
	);

	initial begin
		$display("Custom HPS is here");
	end

endmodule
