//==============================================================================
// Copyright (c) Programmable Solutions Group (PSG),
// Intel Corporation 2016 - present.
// All rights reserved.
//
//==============================================================================

`ifndef __MUX_BASE_TEST_SVH__
`define __MUX_BASE_TEST_SVH__

//------------------------------------------------------------------------------
// Class: mux_base_test
//
// Base test class for all other tests.
// This class is abstract, so it cannot be directly used.
// Instead, it defines attributes and methods common for all other tests.
//
//------------------------------------------------------------------------------
class mux_base_test extends altuvm_test;

   //---------------------------------------------------------------------------
   // Class Variables
   //---------------------------------------------------------------------------
   // Top environment
   mux_env         m_env;
   // Top configuration
   mux_env_config  m_env_config;
   // Main RTB configuration class
   mux_rtb_config  m_rtb_config;

   // CRU Config
   altuvm_cru_config  m_cru_config;
   // CRU generation, specific to Project
   mux_gen_cru     m_gen_cru;

   // Ethernet agent configuration
   mux_eth_agent_cfg  m_eth_mst_agent_cfg;

   // Axi system configuration
   mux_axi_agent_cfg  m_axi_st_system_cfg;

   // Register top block
//   mux_reg_urm                     m_ral;

   //
   // Constructor: new
   //
   // Creates instance of this UVM component.
   //
   // Parameter(s):
   //  name   - Name of the instance.
   //  parent - Handle to the hierarchical parent, *null* if none.
   //
   function new(string name, uvm_component parent);
      super.new(name, parent);

      // Set the factory type override to override the autogenerated RAL class
      // with the extended class which has the definition of the coverage and
      // contraints (I am showing all possible way to override class as below.
      // All of them are valid approach)

      // Approach1 : Looks cool!
      //mux_reg_urm::type_id::set_type_override(mux_reg_urm_ext::get_type());
      //
      // Approach2 :
      // uvm_factory::get().set_type_override_by_type(
      //    mux_reg_urm::get_type(), mux_reg_urm_ext::get_type());
      //
      // Approach3 :
      // set_type_override_by_type(
      //    mux_reg_urm::get_type(), mux_reg_urm_ext::get_type());
      //
      // BAD example that will be deprecated in UVM-1.2
      // Dont use "factory"! The global handle of it will be removed in UVM-1.2:
      // factory.set_type_override_by_type(
      //    mux_reg_urm::get_type(), mux_reg_urm_ext::get_type());
   endfunction : new
   //
   // Function: build_phase
   //
   // Create the subcomponents based on the configuration object settings.
   //
   // Parameter(s):
   //  phase - Current UVM phase.
   //
   function void build_phase(uvm_phase phase);
      uses_rptcatcher();
      $display("AS_DBG : Enter base test build phase");
      super.build_phase(phase);
      $display("AS_DBG : base test super.build phase done");

      // Top environment

      m_env = mux_env::type_id::create("m_env", this);
      $display ("AS_DBG:  m_env created in base test ");
      m_env.set_rtb_path("top_tb.rtb");

      // Top configuration
      m_env_config = mux_env_config::type_id::create("m_env_config");
      m_env_config.m_msg_id = m_env.get_name();

      `ifdef FM7_FC
        m_env_config.is_block = 0;
      `else
        m_env_config.is_block = 1;
      `endif

      // Set the concrete class into UVM configuration table
      `altuvm_set_config_db(mux_env_config, "mux_env_config", m_env_config, "m_env")

      // Get the RTB configuration object
      `altuvm_get_config_db(mux_rtb_config, {m_env.get_rtb_path(), ".", "get_rtb_config()"}, m_rtb_config)

      //
      m_eth_mst_agent_cfg = mux_eth_agent_cfg::type_id::create("m_eth_mst_agent_cfg");
      m_eth_mst_agent_cfg.set_gmii_default_cfg();
      uvm_config_db#(svt_ethernet_agent_configuration)::set(this,"m_env.m_eth_env*", "cfg", m_eth_mst_agent_cfg);
    `ifdef MUX_DEBUG
      uvm_config_db#(svt_ethernet_agent_configuration)::set(this,"m_env.ethernet_mac_mst*", "cfg", m_eth_mst_agent_cfg);
      uvm_config_db#(svt_ethernet_agent_configuration)::set(this,"m_env.ethernet_mac_slv*", "cfg", m_eth_mst_agent_cfg);
    `endif

      // AXI
      m_axi_st_system_cfg = mux_axi_agent_cfg::type_id::create("m_axi_st_system_cfg");
      uvm_config_db#(svt_axi_system_configuration)::set(this,"m_env.m_axi_st_env*", "cfg", m_axi_st_system_cfg);

      /*//////////////////////////////////////////////////////////////*/
      /* TODO: Enable or disable the RAL (Register Abstraction Layer) */
      /*       -- UVM Register Model by setting 1 or 0 to uses_ral(). */
      /*//////////////////////////////////////////////////////////////*/
      //m_env.uses_ral(1);

      // Create and setup RAL
     // build_ral();

      //if (m_env.get_uses_ral())
         // Enable (1) or disable (0) the randomization of the register fields values
      //   `altuvm_set_config_db(int, "m_random_enable", 1, "m_env.m_ral")

      m_env.uses_im(0); // Disable the Interrupt Manager (IM) control
      m_env.uses_rptcatcher(1);
      uses_summary(1);  // To use ALTUVM summary feature

      // Create CRU Config Object
      m_cru_config = altuvm_cru_config::type_id::create("m_cru_config");
      `altuvm_set_config_db(altuvm_cru_config, "m_cru_config", m_cru_config, "m_env")
      // CRU generation - use randomized variables to generate clocks and resets
      m_gen_cru = mux_gen_cru::type_id::create("m_gen_cru");
      // Do CRU configuration
      cru_config();

      // Initialize environment configuration
      init_config();

      `altuvm_set_config_db(int, "m_has_scbd", 1,  "m_env")
   /////////////////////////////////////////////////////////////////////////////
   // NOTE:
   // m_enable_objection: set to 1 to enable the objection control in
   //                     scoreboard, it will drop the objection when number
   //                     of packets being verified reach m_total_packet.
   // m_total_packet:  the number of packet being checked and verified
   //                  before dropping the objection.
   /////////////////////////////////////////////////////////////////////////////
   /* TODO: When the testbench is stable and there are transactions           */
   /*       exercising the DUT, turn the m_enable_objection to 1 and set the  */
   /*       _num_pkt to fixed number of packets, or set based on the packets  */
   /*       that being sent in each individual test.                          */
   /*       Please override this set_config_db in respective tests by setting */
   /*       m_enable_object = 1 and m_total_packets = fixed number of packet  */
   /*       or number of packets being sent based on individual test.         */
   /*/////////////////////////////////////////////////////////////////////////*/
      `altuvm_set_config_db(int, "m_enable_objection", 0, "m_env.m_scoreboard")
// NOTE:
// Set to 100 packets to be compared. <<example>>
      `altuvm_set_config_db(int, "m_total_packets", 100, "m_env.m_scoreboard")

      `uvm_info("PHASE-DEBUG", "build_phase -> done", UVM_LOW)
   endfunction : build_phase
   //
   // Function: connect_phase
   //
   // Connect the ral using connect_ral() function.
   //
   // Parameter(s):
   //  phase - Current UVM phase.
   //
   function void connect_phase(uvm_phase phase);
      super.connect_phase(phase);
      // Do RAL connections
     // connect_ral();
      `uvm_info("PHASE-DEBUG", "connect_phase -> done", UVM_MEDIUM)
   endfunction : connect_phase
   //
   // Function: end_of_elaboration_phase
   //
   // Set the verbosity and print the uvm hierarchy.
   //
   // Parameter(s):
   //  phase - Current UVM phase.
   //
   function void end_of_elaboration_phase(uvm_phase phase);
      super.end_of_elaboration_phase(phase);
      // Change the SSG UVC's verbosity
      if (m_env.get_report_verbosity_level() >= UVM_DEBUG)
         verbosity_pkg::set_verbosity(verbosity_pkg::VERBOSITY_DEBUG);

      `uvm_info("PHASE-DEBUG", "end_of_elaboration_phase -> done", UVM_MEDIUM)
   endfunction : end_of_elaboration_phase
   //
   // Function: build_ral
   //
   // Build RAL block.
   //
   virtual function void build_ral();
      // Create Register block of the IP
//      m_ral           = mux_reg_urm::type_id::create("m_ral", , get_full_name());
//      // Setup Register block
//      m_ral.build();
//      // Enable URM Coverage Sampling
//      m_ral.set_coverage(UVM_CVR_ALL);
//      // Pass the RAL to the handler inside the IP's environment using
//      // UVM configuration mechanism
//      if (m_env.get_uses_ral())
//         `altuvm_set_config_db(mux_reg_urm, "m_ral", m_ral, "m_env.m_ral")
   endfunction : build_ral
   //
   // Function: connect_ral
   //
   // Connection for RAL.
   //
   virtual function void connect_ral();
//      m_ral.default_map.set_auto_predict(0);
//
//      // Lock Register block to avoid further modifications
//      m_ral.lock_model();

      //------------------------------------------------------------------------
      // Register prediction part:
      //------------------------------------------------------------------------
      // Replacing implicit register model prediction with explicit prediction
      // based on Avalon-MM bus activity observed by the Avalon-MM agent monitor
      // Set the predictor map:
   endfunction : connect_ral
   //
   // Function: init_config
   //
   // Function to initialize the common configuration.
   //
   virtual function void init_config();
     if(!m_env_config.randomize())
       `uvm_error(m_env_config.m_msg_id, "m_env_config randomization failed.")
     //
     m_env_config.init();
   endfunction : init_config
   //
   // Function: cru_config
   //
   // Function to configure the clock and reset signals behavior.
   //
   virtual function void cru_config();
      if (!m_gen_cru.randomize())
         `uvm_error(m_env_config.m_msg_id, "m_gen_cru randomization failed.")
   /*///////////////////////////////////////////////////////////////////////////////*/
   /* TODO: 1. Define and register the TB driven clocks with frequency or period,   */
   /*          unit = {kHz/MHz/GHz/us/ns/ps}, skew and duty cycle.                  */
   /*       2. Register the clocks that go into TB. (observed clocks)               */
   /*       3. Define and register the TB driven resets with init deassertion time. */
   /*       4. Register the resets that go into TB. (observed resets)               */
   /*///////////////////////////////////////////////////////////////////////////////*/
   // NOTE:
   // Below are examples. Please change and update per requirement.
   ////////////////////////////////////////////////////////////////////////
      m_cru_config.set_clock_freqtime("cpu_clk",      0, m_gen_cru.m_freqtime["cpu_clk"],      m_gen_cru.m_unit["cpu_clk"],      m_gen_cru.m_skew["cpu_clk"],      50);
      m_cru_config.set_clock_freqtime("reconfig_clk", 1, m_gen_cru.m_freqtime["reconfig_clk"], m_gen_cru.m_unit["reconfig_clk"], m_gen_cru.m_skew["reconfig_clk"], 50);

      m_cru_config.register_reset("cpu_reset",      0, m_gen_cru.m_init_time["cpu_reset"]);
      m_cru_config.register_reset("reconfig_reset", 1, m_gen_cru.m_init_time["reconfig_reset"]);
   endfunction : cru_config


   function void final_phase(uvm_phase phase);
      uvm_report_server svr;

      super.final_phase(phase);
//`ifdef VCS
//      //
//      // Gets the global report server.
//      //
//      svr = uvm_report_server::get_server();
//      //
//      // If there are any warning, fatal or error severity message then declare test as failed.
//      //
//      if (svr.get_severity_count(UVM_FATAL) +
//          svr.get_severity_count(UVM_ERROR) +
//         (svr.get_severity_count(UVM_WARNING) * m_summary_check_warn) == 0) begin
//         `uvm_info("VCS_CM_TEST_STATUS", "The test is assigned to PASS in coverage database!", UVM_LOW)
//         $cm_post(`CM_TEST_STATUS,  "pass");
//      end
//`endif
   endfunction : final_phase

endclass : mux_base_test

`endif//__MUX_BASE_TEST_SVH__
