//****************************************************************************
// SPDX-License-Identifier: MIT-0
// Copyright(c) 2019-2024 Intel Corporation.
//****************************************************************************

module mrphy_dr_wrapper #(
    parameter NUM_PHY = 3
)(
    // Channel interfaces
     mrphy_csr_if.phy      csr_if      [NUM_PHY],
     mrphy_mac_tx_if.phy   mac_tx_if   [NUM_PHY],
     mrphy_mac_rx_if.mac   mac_rx_if   [NUM_PHY],
     mrphy_adapter_if.phy  adapter_if  [NUM_PHY],
     mrphy_reset_if.phy    reset_if    [NUM_PHY],
     mrphy_serial_if.phy   serial_if   [NUM_PHY],
     mrphy_misc_if.phy     misc_if     [NUM_PHY],
     mrphy_latency_if.phy  latency_if  [NUM_PHY],
     mrphy_reconfig_if.phy reconfig_if [NUM_PHY],
    
    // DR/Control interfaces from dr_if_pkg
     dr_lavmm_if.dr dr_lavmm_if [NUM_PHY],
     pause_if.dr    pause_if    [NUM_PHY],
     grant_if.dr    grant_if    [NUM_PHY],
    // Shared signals
    input  [5:0] one_hot_sel,
    input   i_pma_cu_clk_bank0,
    input   i_system_pll_clk_mrphy_0,
    input   i_system_pll_lock_mrphy_0,
    input   i_system_pll_lock_mrphy_1,
    input   i_system_pll_lock_mrphy_2
);

mr_top mr_top_inst (
        // CSR
        .csr_address_mrphy_0    (csr_if[0].address),
        .csr_address_mrphy_1    (csr_if[1].address),
        .csr_address_mrphy_2    (csr_if[2].address),
        .csr_clk_mrphy_0        (csr_if[0].clk),
        .csr_clk_mrphy_1        (csr_if[1].clk),
        .csr_clk_mrphy_2        (csr_if[2].clk),
        .csr_read_mrphy_0       (csr_if[0].read),
        .csr_read_mrphy_1       (csr_if[1].read),
        .csr_read_mrphy_2       (csr_if[2].read),
        .csr_readdata_mrphy_0   (csr_if[0].readdata),
        .csr_readdata_mrphy_1   (csr_if[1].readdata),
        .csr_readdata_mrphy_2   (csr_if[2].readdata),
        .csr_waitrequest_mrphy_0(csr_if[0].waitrequest),
        .csr_waitrequest_mrphy_1(csr_if[1].waitrequest),
        .csr_waitrequest_mrphy_2(csr_if[2].waitrequest),
        .csr_write_mrphy_0      (csr_if[0].write),
        .csr_write_mrphy_1      (csr_if[1].write),
        .csr_write_mrphy_2      (csr_if[2].write),
        .csr_writedata_mrphy_0  (csr_if[0].writedata),
        .csr_writedata_mrphy_1  (csr_if[1].writedata),
        .csr_writedata_mrphy_2  (csr_if[2].writedata),

        // MAC TX
        .gmii8b_mac_speed_mrphy_0 (mac_tx_if[0].mac_speed),
        .gmii8b_mac_speed_mrphy_1 (mac_tx_if[1].mac_speed),
        .gmii8b_mac_speed_mrphy_2 (mac_tx_if[2].mac_speed),
        .gmii8b_mac_tx_d_mrphy_0  (mac_tx_if[0].tx_d),
        .gmii8b_mac_tx_d_mrphy_1  (mac_tx_if[1].tx_d),
        .gmii8b_mac_tx_d_mrphy_2  (mac_tx_if[2].tx_d),
        .gmii8b_mac_txen_mrphy_0  (mac_tx_if[0].txen),
        .gmii8b_mac_txen_mrphy_1  (mac_tx_if[1].txen),
        .gmii8b_mac_txen_mrphy_2  (mac_tx_if[2].txen),
        .gmii8b_mac_txer_mrphy_0  (mac_tx_if[0].txer),
        .gmii8b_mac_txer_mrphy_1  (mac_tx_if[1].txer),
        .gmii8b_mac_txer_mrphy_2  (mac_tx_if[2].txer),

        // MAC RX
        .gmii8b_mac_rxd_mrphy_0   (mac_rx_if[0].rxd),
        .gmii8b_mac_rxd_mrphy_1   (mac_rx_if[1].rxd),
        .gmii8b_mac_rxd_mrphy_2   (mac_rx_if[2].rxd),
        .gmii8b_mac_rxdv_mrphy_0  (mac_rx_if[0].rxdv),
        .gmii8b_mac_rxdv_mrphy_1  (mac_rx_if[1].rxdv),
        .gmii8b_mac_rxdv_mrphy_2  (mac_rx_if[2].rxdv),
        .gmii8b_mac_rxer_mrphy_0  (mac_rx_if[0].rxer),
        .gmii8b_mac_rxer_mrphy_1  (mac_rx_if[1].rxer),
        .gmii8b_mac_rxer_mrphy_2  (mac_rx_if[2].rxer),

        // Adapter
        .gmii8b_tx_clkin_mrphy_0  (adapter_if[0].gmii8b_tx_clkin),
        .gmii8b_tx_clkin_mrphy_1  (adapter_if[1].gmii8b_tx_clkin),
        .gmii8b_tx_clkin_mrphy_2  (adapter_if[2].gmii8b_tx_clkin),
        .gmii8b_tx_rst_n_mrphy_0  (adapter_if[0].gmii8b_tx_rst_n),
        .gmii8b_tx_rst_n_mrphy_1  (adapter_if[1].gmii8b_tx_rst_n),
        .gmii8b_tx_rst_n_mrphy_2  (adapter_if[2].gmii8b_tx_rst_n),
        .gmii8b_rx_rst_n_mrphy_0  (adapter_if[0].gmii8b_rx_rst_n),
        .gmii8b_rx_rst_n_mrphy_1  (adapter_if[1].gmii8b_rx_rst_n),
        .gmii8b_rx_rst_n_mrphy_2  (adapter_if[2].gmii8b_rx_rst_n),
        .gmii8b_rx_clkout_mrphy_0 (adapter_if[0].gmii8b_rx_clkout),
        .gmii8b_rx_clkout_mrphy_1 (adapter_if[1].gmii8b_rx_clkout),
        .gmii8b_rx_clkout_mrphy_2 (adapter_if[2].gmii8b_rx_clkout),
        .gmii8b_tx_clkout_mrphy_0 (adapter_if[0].gmii8b_tx_clkout),
        .gmii8b_tx_clkout_mrphy_1 (adapter_if[1].gmii8b_tx_clkout),
        .gmii8b_tx_clkout_mrphy_2 (adapter_if[2].gmii8b_tx_clkout),

        // Latency
       /* .gmii16b_rx_latency_mrphy_0(latency_if[0].latency.rx_latency),
        .gmii16b_rx_latency_mrphy_1(latency_if[1].latency.rx_latency),
        .gmii16b_rx_latency_mrphy_2(latency_if[2].latency.rx_latency),
        .gmii16b_tx_latency_mrphy_0(latency_if[0].latency.tx_latency),
        .gmii16b_tx_latency_mrphy_1(latency_if[1].latency.tx_latency),
        .gmii16b_tx_latency_mrphy_2(latency_if[2].latency.tx_latency),*/
       .latency_measure_clk_mrphy_0  (latency_if[0].measure_clk ),
      // .latency_measure_clk_mrphy_1  (latency_if[1].measure_clk ),
       .latency_measure_clk_mrphy_2  (latency_if[2].measure_clk ),
       .latency_sclk_mrphy_0         (latency_if[0].sclk ),
      // .latency_sclk_mrphy_1         (latency_if[1].sclk ),
       .latency_sclk_mrphy_2         (latency_if[2].sclk ),

        // Reset
        .reset_mrphy_0            (reset_if[0].reset),
        .reset_mrphy_1            (reset_if[1].reset),
        .reset_mrphy_2            (reset_if[2].reset),
        .rx_digitalreset_mrphy_0  (reset_if[0].rx_digitalreset),
        .rx_digitalreset_mrphy_1  (reset_if[1].rx_digitalreset),
        .rx_digitalreset_mrphy_2  (reset_if[2].rx_digitalreset),
        .tx_digitalreset_mrphy_0  (reset_if[0].tx_digitalreset),
        .tx_digitalreset_mrphy_1  (reset_if[1].tx_digitalreset),
        .tx_digitalreset_mrphy_2  (reset_if[2].tx_digitalreset),
        .i_rst_n_mrphy_0          (reset_if[0].i_rst_n),
        .i_rst_n_mrphy_1          (reset_if[1].i_rst_n),
        .i_rst_n_mrphy_2          (reset_if[2].i_rst_n),
        .i_tx_rst_n_mrphy_0       (reset_if[0].i_tx_rst_n),
        .i_tx_rst_n_mrphy_1       (reset_if[1].i_tx_rst_n),
        .i_tx_rst_n_mrphy_2       (reset_if[2].i_tx_rst_n),
        .i_rx_rst_n_mrphy_0       (reset_if[0].i_rx_rst_n),
        .i_rx_rst_n_mrphy_1       (reset_if[1].i_rx_rst_n),
        .i_rx_rst_n_mrphy_2       (reset_if[2].i_rx_rst_n),
        .o_rst_ack_n_mrphy_0      (reset_if[0].o_rst_ack_n),
        .o_rst_ack_n_mrphy_1      (reset_if[1].o_rst_ack_n),
        .o_rst_ack_n_mrphy_2      (reset_if[2].o_rst_ack_n),
        .o_tx_rst_ack_n_mrphy_0   (reset_if[0].o_tx_rst_ack_n),
        .o_tx_rst_ack_n_mrphy_1   (reset_if[1].o_tx_rst_ack_n),
        .o_tx_rst_ack_n_mrphy_2   (reset_if[2].o_tx_rst_ack_n),
        .o_rx_rst_ack_n_mrphy_0   (reset_if[0].o_rx_rst_ack_n),
        .o_rx_rst_ack_n_mrphy_1   (reset_if[1].o_rx_rst_ack_n),
        .o_rx_rst_ack_n_mrphy_2   (reset_if[2].o_rx_rst_ack_n),

        // LED/Status/Misc
        .led_link_mrphy_0        (misc_if[0].led_link),
        .led_link_mrphy_1        (misc_if[1].led_link),
        .led_link_mrphy_2        (misc_if[2].led_link),
        .led_char_err_mrphy_0    (misc_if[0].led_char_err),
        .led_char_err_mrphy_1    (misc_if[1].led_char_err),
        .led_char_err_mrphy_2    (misc_if[2].led_char_err),
        .led_disp_err_mrphy_0    (misc_if[0].led_disp_err),
        .led_disp_err_mrphy_1    (misc_if[1].led_disp_err),
        .led_disp_err_mrphy_2    (misc_if[2].led_disp_err),
        .led_an_mrphy_0          (misc_if[0].led_an),
        .led_an_mrphy_1          (misc_if[1].led_an),
        .led_an_mrphy_2          (misc_if[2].led_an),
        .operating_speed_mrphy_0 (misc_if[0].operating_speed),
        .operating_speed_mrphy_1 (misc_if[1].operating_speed),
        .operating_speed_mrphy_2 (misc_if[2].operating_speed),
        .mrphy_pll_lock_mrphy_0  (misc_if[0].mrphy_pll_lock),
        .mrphy_pll_lock_mrphy_1  (misc_if[1].mrphy_pll_lock),
        .mrphy_pll_lock_mrphy_2  (misc_if[2].mrphy_pll_lock),
        .tx_ready_mrphy_0        (misc_if[0].tx_ready),
        .tx_ready_mrphy_1        (misc_if[1].tx_ready),
        .tx_ready_mrphy_2        (misc_if[2].tx_ready),
        .rx_ready_mrphy_0        (misc_if[0].rx_ready),
        .rx_ready_mrphy_1        (misc_if[1].rx_ready),
        .rx_ready_mrphy_2        (misc_if[2].rx_ready),
       /* .rx_pma_clkout_mrphy_0   (misc_if[0].misc.rx_pma_clkout),
        .rx_pma_clkout_mrphy_1   (misc_if[1].misc.rx_pma_clkout),
        .rx_pma_clkout_mrphy_2   (misc_if[2].misc.rx_pma_clkout),
        .o_refclk_bus_out_mrphy_0(misc_if[0].misc.o_refclk_bus_out),
        .o_refclk_bus_out_mrphy_1(misc_if[1].misc.o_refclk_bus_out),
        .o_refclk_bus_out_mrphy_2(misc_if[2].misc.o_refclk_bus_out),
        .o_rs_request_ch0        (misc_if[0].misc.o_src_rs_req),
        .o_rs_request_ch1        (misc_if[1].misc.o_src_rs_req),
        .o_rs_request_ch2        (misc_if[2].misc.o_src_rs_req),*/

        // Serial
        .o_tx_serial_data_p_ch0  (serial_if[0].tx_serial_data),
        .o_tx_serial_data_p_ch1  (serial_if[1].tx_serial_data),
        .o_tx_serial_data_p_ch2  (serial_if[2].tx_serial_data),
        .o_tx_serial_data_n_ch0  (serial_if[0].tx_serial_data_n),
        .o_tx_serial_data_n_ch1  (serial_if[1].tx_serial_data_n),
        .o_tx_serial_data_n_ch2  (serial_if[2].tx_serial_data_n),
        .i_rx_serial_data_p_ch0  (serial_if[0].rx_serial_data),
        .i_rx_serial_data_p_ch1  (serial_if[1].rx_serial_data),
        .i_rx_serial_data_p_ch2  (serial_if[2].rx_serial_data),
        .i_rx_serial_data_n_ch0  (serial_if[0].rx_serial_data_n),
        .i_rx_serial_data_n_ch1  (serial_if[1].rx_serial_data_n),
        .i_rx_serial_data_n_ch2  (serial_if[2].rx_serial_data_n),
        .rx_is_lockedtodata_mrphy_0(misc_if[0].rx_is_lockedtodata),
        .rx_is_lockedtodata_mrphy_1(misc_if[1].rx_is_lockedtodata),
        .rx_is_lockedtodata_mrphy_2(misc_if[2].rx_is_lockedtodata),

        // Reconfig
        .reconfig_clk_mrphy_0    (reconfig_if[0].clk),
        .reconfig_clk_mrphy_1    (reconfig_if[1].clk),
        .reconfig_clk_mrphy_2    (reconfig_if[2].clk),
        .reconfig_reset_mrphy_0  (reconfig_if[0].reset),
        .reconfig_reset_mrphy_1  (reconfig_if[1].reset),
        .reconfig_reset_mrphy_2  (reconfig_if[2].reset),
        .reconfig_write_mrphy_0  (reconfig_if[0].write),
        .reconfig_write_mrphy_1  (reconfig_if[1].write),
        .reconfig_write_mrphy_2  (reconfig_if[2].write),
        .reconfig_read_mrphy_0   (reconfig_if[0].read),
        .reconfig_read_mrphy_1   (reconfig_if[1].read),
        .reconfig_read_mrphy_2   (reconfig_if[2].read),
        .reconfig_address_mrphy_0(reconfig_if[0].address),
        .reconfig_address_mrphy_1(reconfig_if[1].address),
        .reconfig_address_mrphy_2(reconfig_if[2].address),
        .reconfig_be_mrphy_0     (reconfig_if[0].be),
        .reconfig_be_mrphy_1     (reconfig_if[1].be),
        .reconfig_be_mrphy_2     (reconfig_if[2].be),
        .reconfig_writedata_mrphy_0(reconfig_if[0].writedata),
        .reconfig_writedata_mrphy_1(reconfig_if[1].writedata),
        .reconfig_writedata_mrphy_2(reconfig_if[2].writedata),
        .reconfig_readdata_mrphy_0(reconfig_if[0].readdata),
        .reconfig_readdata_mrphy_1(reconfig_if[1].readdata),
        .reconfig_readdata_mrphy_2(reconfig_if[2].readdata),
        .reconfig_waitrequest_mrphy_0(reconfig_if[0].waitrequest),
        .reconfig_waitrequest_mrphy_1(reconfig_if[1].waitrequest),
        .reconfig_waitrequest_mrphy_2(reconfig_if[2].waitrequest),
        .reconfig_readdata_valid_mrphy_0(reconfig_if[0].readdatavalid),
        .reconfig_readdata_valid_mrphy_1(reconfig_if[1].readdatavalid),
        .reconfig_readdata_valid_mrphy_2(reconfig_if[2].readdatavalid), 

        // DR/Control signals from dr_if_pkg interfaces:
        // DR LAVMM per channel
        .i_dr_lavmm_addr_ch0      (dr_lavmm_if[0].addr),
        .i_dr_lavmm_addr_ch1      (dr_lavmm_if[1].addr),
        .i_dr_lavmm_addr_ch2      (dr_lavmm_if[2].addr),
        .i_dr_lavmm_be_ch0        (dr_lavmm_if[0].be),
        .i_dr_lavmm_be_ch1        (dr_lavmm_if[1].be),
        .i_dr_lavmm_be_ch2        (dr_lavmm_if[2].be),
        .i_dr_lavmm_clk_ch0       (dr_lavmm_if[0].clk),
        .i_dr_lavmm_clk_ch1       (dr_lavmm_if[1].clk),
        .i_dr_lavmm_clk_ch2       (dr_lavmm_if[2].clk),
        .i_dr_lavmm_read_ch0      (dr_lavmm_if[0].read),
        .i_dr_lavmm_read_ch1      (dr_lavmm_if[1].read),
        .i_dr_lavmm_read_ch2      (dr_lavmm_if[2].read),
        .i_dr_lavmm_rstn_ch0      (dr_lavmm_if[0].rstn),
        .i_dr_lavmm_rstn_ch1      (dr_lavmm_if[1].rstn),
        .i_dr_lavmm_rstn_ch2      (dr_lavmm_if[2].rstn),
        .i_dr_lavmm_wdata_ch0     (dr_lavmm_if[0].wdata),
        .i_dr_lavmm_wdata_ch1     (dr_lavmm_if[1].wdata),
        .i_dr_lavmm_wdata_ch2     (dr_lavmm_if[2].wdata),
        .i_dr_lavmm_write_ch0     (dr_lavmm_if[0].write),
        .i_dr_lavmm_write_ch1     (dr_lavmm_if[1].write),
        .i_dr_lavmm_write_ch2     (dr_lavmm_if[2].write),
        .o_dr_lavmm_rdata_ch0     (dr_lavmm_if[0].rdata),
        .o_dr_lavmm_rdata_ch1     (dr_lavmm_if[1].rdata),
        .o_dr_lavmm_rdata_ch2     (dr_lavmm_if[2].rdata),
        .o_dr_lavmm_rdata_valid_ch0(dr_lavmm_if[0].rdata_valid),
        .o_dr_lavmm_rdata_valid_ch1(dr_lavmm_if[1].rdata_valid),
        .o_dr_lavmm_rdata_valid_ch2(dr_lavmm_if[2].rdata_valid),
        .o_dr_lavmm_waitreq_ch0   (dr_lavmm_if[0].waitreq),
        .o_dr_lavmm_waitreq_ch1   (dr_lavmm_if[1].waitreq),
        .o_dr_lavmm_waitreq_ch2   (dr_lavmm_if[2].waitreq),

        // Pause/grant per channel
        .i_src_pause_request_ch0  (pause_if[0].src_pause_request),
        .i_src_pause_request_ch1  (pause_if[1].src_pause_request),
        .i_src_pause_request_ch2  (pause_if[2].src_pause_request),
        .o_src_pause_grant_ch0    (pause_if[0].src_pause_grant),
        .o_src_pause_grant_ch1    (pause_if[1].src_pause_grant),
        .o_src_pause_grant_ch2    (pause_if[2].src_pause_grant),

        // RS grant/request per channel
        .i_rs_grant_ch0           (grant_if[0].rs_grant),
        .i_rs_grant_ch1           (grant_if[1].rs_grant),
        .i_rs_grant_ch2           (grant_if[2].rs_grant),
        .o_rs_request_ch0         (grant_if[0].rs_request),
        .o_rs_request_ch1         (grant_if[1].rs_request),
        .o_rs_request_ch2         (grant_if[2].rs_request),

      /*  .rx_clkout_mrphy_0        (misc_if[0].rx_clkout),
        .rx_clkout_mrphy_1        (misc_if[1].rx_clkout),
        .rx_clkout_mrphy_2        (misc_if[2].rx_clkout),
        .tx_clkout_mrphy_0        (misc_if[0].tx_clkout),
        .tx_clkout_mrphy_1        (misc_if[1].tx_clkout),
        .tx_clkout_mrphy_2        (misc_if[2].tx_clkout),*/
        .rx_cdr_refclk_p_mrphy_0  (misc_if[0].rx_cdr_refclk_p),
        .rx_cdr_refclk_p_mrphy_1  (misc_if[1].rx_cdr_refclk_p),
        .rx_cdr_refclk_p_mrphy_2  (misc_if[2].rx_cdr_refclk_p),
        .tx_pll_refclk_p_mrphy_0  (misc_if[0].tx_pll_refclk_p),
        .tx_pll_refclk_p_mrphy_1  (misc_if[1].tx_pll_refclk_p),
        .tx_pll_refclk_p_mrphy_2  (misc_if[2].tx_pll_refclk_p),
        .xcvr_mode_mrphy_0        (misc_if[0].xcvr_mode),
        .xcvr_mode_mrphy_1        (misc_if[1].xcvr_mode),
        .xcvr_mode_mrphy_2        (misc_if[2].xcvr_mode),
        // Shared
        .one_hot_sel              (one_hot_sel),
        .i_pma_cu_clk_bank0       (i_pma_cu_clk_bank0),
        .i_system_pll_clk_mrphy_0 (i_system_pll_clk_mrphy_0),
        .i_system_pll_lock_mrphy_0(i_system_pll_lock_mrphy_0),
        .i_system_pll_lock_mrphy_1(i_system_pll_lock_mrphy_1),
        .i_system_pll_lock_mrphy_2(i_system_pll_lock_mrphy_2)
);

 endmodule
