// ${REG_LOCAL_ROOT_DIR_PATH}/ip/ethernet/intel_mge_phy_scripts/qhip/scripts/funct_deterministic/common/rtl_files_MGBASET_SM_10M100M1G2P5G_8BIT_D2P5G/alt_mge_mac_phy_wrapper.sv
 ${REG_LOCAL_ROOT_DIR_PATH}/ip/ethernet/intel_mge_phy_scripts/qhip/scripts/funct_deterministic/common/rtl_files_MGBASET_SM_10M100M1G2P5G_8BIT_D2P5G/alt_mge_mac_wrapper.sv
// ${REG_LOCAL_ROOT_DIR_PATH}/ip/ethernet/intel_mge_phy_scripts/qhip/scripts/funct_deterministic/common/rtl_files_MGBASET_SM_10M100M1G2P5G_8BIT_D2P5G/alt_mge_channel.v
// ${REG_LOCAL_ROOT_DIR_PATH}/ip/ethernet/intel_mge_phy_scripts/qhip/scripts/funct_deterministic/common/rtl_files_MGBASET_SM_10M100M1G2P5G_8BIT_D2P5G/alt_mge_rd.sv
// ${REG_LOCAL_ROOT_DIR_PATH}/ip/ethernet/intel_mge_phy_scripts/qhip/scripts/funct_deterministic/common/rtl_files_MGBASET_SM_10M100M1G2P5G_8BIT_D2P5G/alt_mge_reset_synchronizer.v
../../alt_mge_phy_reconfig_parameters_CFG0.sv
// ${REG_LOCAL_ROOT_DIR_PATH}/ip/ethernet/intel_mge_phy_scripts/qhip/scripts/funct_deterministic/common/rtl_files_MGBASET_SM_10M100M1G2P5G_8BIT_D2P5G/alt_mge_rcfg.sv
// ${REG_LOCAL_ROOT_DIR_PATH}/ip/ethernet/intel_mge_phy_scripts/qhip/scripts/funct_deterministic/common/rtl_files_MGBASET_SM_10M100M1G2P5G_8BIT_D2P5G/alt_mge_rcfg_ch_recal.v
// ${REG_LOCAL_ROOT_DIR_PATH}/ip/ethernet/intel_mge_phy_scripts/qhip/scripts/funct_deterministic/common/rtl_files_MGBASET_SM_10M100M1G2P5G_8BIT_D2P5G/alt_mge_rcfg_mif_master.v
// ${REG_LOCAL_ROOT_DIR_PATH}/ip/ethernet/intel_mge_phy_scripts/qhip/scripts/funct_deterministic/common/rtl_files_MGBASET_SM_10M100M1G2P5G_8BIT_D2P5G/alt_mge_rcfg_mif_rom.v
// ${REG_LOCAL_ROOT_DIR_PATH}/ip/ethernet/intel_mge_phy_scripts/qhip/scripts/funct_deterministic/common/rtl_files_MGBASET_SM_10M100M1G2P5G_8BIT_D2P5G/alt_mge_rcfg_txpll_switch.v
