module top #()
(

input wire i_clk_tx,
input wire i_clk_rx,
input wire i_reconfig_clk,
output wire o_clk_pll,
output wire o_clk_tx_div,
output wire o_clk_rec_div64,
output wire o_clk_rec_div,
//input wire i_clk_ref,
//input wire i_clk_sys,
input wire i_rst_n,
//output wire o_rst_ack_n,
input wire i_tx_rst_n,
//output wire o_tx_rst_ack_n,
input wire i_rx_rst_n,
//output wire o_rx_rst_ack_n,
input wire i_reconfig_reset,
output wire o_tx_lanes_stable,
output wire o_rx_pcs_ready,
output wire o_tx_pll_locked,
output wire o_cdr_lock,
output wire o_rx_block_lock,
output wire o_rx_am_lock,
output wire o_local_fault_status,
output wire o_remote_fault_status,
input wire i_stats_snapshot,
output wire o_rx_hi_ber,
output wire o_rx_pcs_fully_aligned,
input wire [63:0] i_tx_data,
input wire i_tx_valid,
input wire i_tx_startofpacket,
input wire i_tx_endofpacket,
input wire [2:0] i_tx_empty,
output wire o_tx_ready,
input wire i_tx_error,
input wire i_tx_skip_crc,
//input wire [63:0] i_tx_preamble, // for 40G/50G
output wire [63:0] o_rx_data,
output wire o_rx_valid,
output wire o_rx_startofpacket,
output wire o_rx_endofpacket,
output wire [2:0] o_rx_empty,
output wire [5:0] o_rx_error,
//output wire [63:0] o_rx_preamble, // for 40G/50G
output wire [39:0] o_rxstatus_data,
output wire o_rxstatus_valid,
//output wire o_tx_serial,
//input wire i_rx_serial,
input wire [19:0] i_eth_reconfig_addr,
input wire i_eth_reconfig_read,
input wire i_eth_reconfig_write,
input wire [31:0] i_eth_reconfig_writedata,
output wire [31:0] o_eth_reconfig_readdata,
output wire o_eth_reconfig_readdata_valid,
output wire o_eth_reconfig_waitrequest,
input wire i_xcvr_reconfig_write,
input wire i_xcvr_reconfig_read,
input wire [19:0] i_xcvr_reconfig_address,
input wire [31:0] i_xcvr_reconfig_writedata,
output wire [31:0] o_xcvr_reconfig_readdata,
output wire o_xcvr_reconfig_waitrequest,
output wire o_xcvr_reconfig_readdata_valid
);

