`define eth_mode_ip0 10G_1
`define ll_speed_ip0 10G_1
`define llvar_ip0 10G_1
`define trans_type_ip0 0
`define ptp_ip0 0
`define rx_fc_fwd_ip0 0 
`define sa_ip0 0 
`define txvlan_ip0 0 
`define rxvlan_ip0 0 
`define en_mx_frsz_ip0 0 
`define en_async_adp_ip0 0 
`define preamble_passthrough_ip0 0 
`define strict_preamble_ip0 0 
`define sfd_ip0 0 
`define lf_ip0 0 
`define fc_ip0 0 
`define rxbyte_rem_ip0 0 
`define fc_rdy_drop_ip0 0 
`define rdy_lat_ip0 0 
`define phy_refclk_ip0 0 
`define ipg_ip0 1 
`define interface_ip0 1 
`define fec_type_ip0 0 
`define tx_frm_size_ip0 1518 
`define rx_frm_size_ip0 1518 
`define ipg_rm_perperiod_ip0 0 
