// alt_mge_phy_0_intel_mge_phy_100_mdesbaq.v

// This file was auto-generated from intel_mge_phy_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 23.4.1 162

`timescale 1 ps / 1 ps
module alt_mge_phy_0_intel_mge_phy_100_mdesbaq #(
		parameter ENABLE_GMII_ADAPTER = 1,
		parameter ENABLE_DL           = 0
	) (
		input  wire        csr_clk,                 //                csr_clk.clk
		input  wire        gmii8b_tx_clkin,         //        gmii8b_tx_clkin.clk
		output wire        tx_clkout,               //              tx_clkout.clk
		output wire        rx_clkout,               //              rx_clkout.clk
		input  wire        gmii8b_tx_rst_n,         //        gmii8b_tx_rst_n.gmii8b_tx_rst_n
		input  wire        gmii8b_rx_rst_n,         //        gmii8b_rx_rst_n.gmii8b_rx_rst_n
		output wire        gmii8b_rx_clkout,        //       gmii8b_rx_clkout.clk
		output wire        gmii8b_tx_clkout,        //       gmii8b_tx_clkout.clk
		input  wire        reset,                   //                  reset.reset
		input  wire        rx_digitalreset,         //        rx_digitalreset.rx_digitalreset
		input  wire        tx_digitalreset,         //        tx_digitalreset.tx_digitalreset
		output wire [15:0] csr_readdata,            //          avalon_mm_csr.readdata
		input  wire [15:0] csr_writedata,           //                       .writedata
		input  wire [4:0]  csr_address,             //                       .address
		output wire        csr_waitrequest,         //                       .waitrequest
		input  wire        csr_read,                //                       .read
		input  wire        csr_write,               //                       .write
		input  wire        gmii8b_mac_txen,         //        gmii8b_mac_txen.export
		input  wire [7:0]  gmii8b_mac_tx_d,         //        gmii8b_mac_tx_d.export
		input  wire        gmii8b_mac_txer,         //        gmii8b_mac_txer.export
		output wire        gmii8b_mac_rxdv,         //        gmii8b_mac_rxdv.export
		output wire [7:0]  gmii8b_mac_rxd,          //         gmii8b_mac_rxd.export
		output wire        gmii8b_mac_rxer,         //        gmii8b_mac_rxer.export
		input  wire [1:0]  gmii8b_mac_speed,        //       gmii8b_mac_speed.export
		output wire        led_link,                //               led_link.export
		output wire        led_char_err,            //           led_char_err.export
		output wire        led_disp_err,            //           led_disp_err.export
		output wire        led_an,                  //                 led_an.export
		output wire [2:0]  operating_speed,         //        operating_speed.export
		output wire        mrphy_pll_lock,          //         mrphy_pll_lock.pll_locked_stable
		input  wire        i_src_ch_pause_request,  // i_src_ch_pause_request.o_src_ch_pause_request
		output wire        o_src_ch_pause_grant,    //   o_src_ch_pause_grant.i_src_ch_pause_grant
		input  wire        i_rst_n,                 //                i_rst_n.i_rst_n
		output wire        o_rst_ack_n,             //            o_rst_ack_n.o_rst_ack_n
		input  wire        i_tx_rst_n,              //             i_tx_rst_n.i_tx_rst_n
		input  wire        i_rx_rst_n,              //             i_rx_rst_n.i_rx_rst_n
		output wire        o_tx_rst_ack_n,          //         o_tx_rst_ack_n.o_tx_rst_ack_n
		output wire        o_rx_rst_ack_n,          //         o_rx_rst_ack_n.o_rx_rst_ack_n
		input  wire        rx_cdr_refclk_p,         //        rx_cdr_refclk_p.clk
		output wire        tx_ready,                //               tx_ready.tx_ready
		output wire        rx_ready,                //               rx_ready.rx_ready
		output wire        rx_pma_clkout,           //          rx_pma_clkout.clk
		input  wire [1:0]  xcvr_mode,               //              xcvr_mode.export
		input  wire [0:0]  tx_pll_refclk_p,         //        tx_pll_refclk_p.clk,                   The connection made from "Reference and SystemPLL Clocks IP" to this pin will guide Quartus on properly setting clock network.
		input  wire [0:0]  i_pma_cu_clk,            //           i_pma_cu_clk.clk,                   The connection made from "Reference and SystemPLL Clocks IP" to this pin will guide Quartus on properly setting clock network.
		input  wire [0:0]  i_system_pll_clk,        //       i_system_pll_clk.clk,                   The connection made from "Reference and SystemPLL Clocks IP" to this pin will guide Quartus on properly setting clock network.
		input  wire [0:0]  i_system_pll_lock,       //      i_system_pll_lock.system_pll_lock,       The connection made from "Reference and SystemPLL Clocks IP" to this pin will guide Quartus on properly setting clock network.
		input  wire [0:0]  i_src_rs_grant,          //         i_src_rs_grant.src_rs_grant,          Grant Signal
		output wire [0:0]  o_src_rs_req,            //           o_src_rs_req.src_rs_req,            Request Signal
		output wire [0:0]  tx_serial_data,          //         tx_serial_data.o_tx_serial_data,      TX serial data port.
		output wire [0:0]  tx_serial_data_n,        //       tx_serial_data_n.o_tx_serial_data_n,    Differential pair for TX serial data port. Historically was hidden; however now used in pam4 signal simulation model, hence needs to be connected by user.
		input  wire [0:0]  rx_serial_data,          //         rx_serial_data.i_rx_serial_data,      RX serial data port.
		input  wire [0:0]  rx_serial_data_n,        //       rx_serial_data_n.i_rx_serial_data_n,    Differential pair for RX serial data port. Historically was hidden; however now used in pam4 signal simulation model, hence needs to be connected by user.
		output wire [0:0]  rx_is_lockedtodata,      //     rx_is_lockedtodata.o_rx_is_lockedtodata,  RX CDR data lock status signal. 1`b0: CDR is not locked to data. 1`b1: CDR is locked to data.
		input  wire [0:0]  reconfig_clk,            //           reconfig_clk.clk,                   Reconfiguration interface clock.
		input  wire [0:0]  reconfig_reset,          //         reconfig_reset.reset,                 Reconfiguration reset.
		input  wire [0:0]  reconfig_write,          //               reconfig.write,                 Reconfiguration write.
		input  wire [0:0]  reconfig_read,           //                       .read,                  Reconfiguration read.
		input  wire [17:0] reconfig_address,        //                       .address,               Reconfiguration word address.
		input  wire [3:0]  reconfig_be,             //                       .byteenable,            Reconfiguration byte enable. If byteenable[3:0] is 4`b1111, 32-bit Dword Access is assumed; otherwise byte access will be used.
		input  wire [31:0] reconfig_writedata,      //                       .writedata,             Reconfiguration write data.
		output wire [31:0] reconfig_readdata,       //                       .readdata,              Reconfiguration read data.
		output wire [0:0]  reconfig_waitrequest,    //                       .waitrequest,           Reconfiguration wait request.
		output wire [0:0]  reconfig_readdata_valid  //                       .readdatavalid,         Reconfiguration read data valid. Optional port, available if the port is enabled in parameter editor.
	);

	wire         xcvr_term_latency_sclk_to_pcs_clk;                                                  // xcvr_term:latency_sclk_to_pcs -> mge_pcs:latency_sclk
	wire         xcvr_term_rx_cdr_refclk_out0_a10_clk;                                               // xcvr_term:rx_cdr_refclk_out0_a10 -> alt_mge_xcvr_directphy:i_rx_cdr_refclk_p
	wire         xcvr_term_tx_clkout_out_pcs_clk;                                                    // xcvr_term:tx_clkout_out_pcs -> mge_pcs:tx_pma_clk
	wire         xcvr_term_rx_clkout_out_pcs_clk;                                                    // xcvr_term:rx_clkout_out_pcs -> mge_pcs:rx_pma_clk
	wire         alt_mge_xcvr_directphy_o_tx_clkout_clk;                                             // alt_mge_xcvr_directphy:o_tx_clkout -> [alt_mge_xcvr_directphy:i_tx_cadence_fast_clk, xcvr_term:tx_clkout_in]
	wire         alt_mge_xcvr_directphy_o_tx_clkout2_clk;                                            // alt_mge_xcvr_directphy:o_tx_clkout2 -> [alt_mge_xcvr_directphy:i_tx_cadence_slow_clk, iopll_tx:refclk, xcvr_term:tx_clkout_in_2]
	wire         xcvr_term_tx_coreclkin_out_xcvr_clk;                                                // xcvr_term:tx_coreclkin_out_xcvr -> alt_mge_xcvr_directphy:i_tx_coreclkin
	wire         xcvr_term_rx_coreclkin_out_xcvr_clk;                                                // xcvr_term:rx_coreclkin_out_xcvr -> alt_mge_xcvr_directphy:i_rx_coreclkin
	wire         alt_mge_xcvr_directphy_o_rx_clkout_clk;                                             // alt_mge_xcvr_directphy:o_rx_clkout -> xcvr_term:rx_clkout_in
	wire         alt_mge_xcvr_directphy_o_rx_clkout2_clk;                                            // alt_mge_xcvr_directphy:o_rx_clkout2 -> xcvr_term:rx_pma_clkout_in
	wire   [1:0] xcvr_term_xcvr_mode_out_export;                                                     // xcvr_term:xcvr_mode_out -> mge_pcs:xcvr_mode
	wire  [19:0] mge_pcs_tx_basex_parallel_data_tx_parallel_data;                                    // mge_pcs:tx_basex_parallel_data -> xcvr_term:tx_basex_parallel_data
	wire  [19:0] xcvr_term_rx_basex_parallel_data_rx_parallel_data;                                  // xcvr_term:rx_basex_parallel_data -> mge_pcs:rx_basex_parallel_data
	wire   [1:0] xcvr_term_rx_syncstatus_a10_rx_syncstatus;                                          // xcvr_term:rx_syncstatus_a10 -> mge_pcs:rx_syncstatus
	wire   [1:0] xcvr_term_rx_runningdisp_a10_rx_runningdisp;                                        // xcvr_term:rx_runningdisp_a10 -> mge_pcs:rx_runningdisp
	wire   [1:0] xcvr_term_rx_disperr_a10_rx_disperr;                                                // xcvr_term:rx_disperr_a10 -> mge_pcs:rx_disperr
	wire   [1:0] xcvr_term_rx_errdetect_a10_rx_errdetect;                                            // xcvr_term:rx_errdetect_a10 -> mge_pcs:rx_errdetect
	wire   [1:0] xcvr_term_rx_patterndetect_a10_rx_patterndetect;                                    // xcvr_term:rx_patterndetect_a10 -> mge_pcs:rx_patterndetect
	wire  [79:0] xcvr_term_tx_parallel_data_sm_i_tx_parallel_data;                                   // xcvr_term:tx_parallel_data_sm -> alt_mge_xcvr_directphy:i_tx_parallel_data
	wire  [79:0] alt_mge_xcvr_directphy_o_rx_parallel_data_o_rx_parallel_data;                       // alt_mge_xcvr_directphy:o_rx_parallel_data -> xcvr_term:rx_parallel_data_sm
	wire         xcvr_term_tx_digitalreset_iopll_reset;                                              // xcvr_term:tx_digitalreset_iopll -> iopll_tx:rst
	wire         iopll_tx_outclk1_clk;                                                               // iopll_tx:outclk_1 -> [mge_pcs:rx_mac_clk, mge_pcs:tx_mac_clk]
	wire         iopll_tx_outclk0_clk;                                                               // iopll_tx:outclk_0 -> mge_pcs:tx_8b_clk
	wire         xcvr_term_permit_cal_export;                                                        // xcvr_term:permit_cal -> iopll_tx:permit_cal
	wire         iopll_tx_outclk2_clk;                                                               // iopll_tx:outclk_2 -> mge_pcs:tx_mac_clk_125
	wire         iopll_tx_outclk3_clk;                                                               // iopll_tx:outclk_3 -> mge_pcs:rx_mac_clk_125
	wire         iopll_tx_locked_export;                                                             // iopll_tx:locked -> mge_pcs:mrphy_pll_lock_pcs
	wire         xcvr_term_o_tx_rst_tx_reset;                                                        // xcvr_term:o_tx_rst -> alt_mge_xcvr_directphy:i_tx_reset
	wire         xcvr_term_o_rx_rst_rx_reset;                                                        // xcvr_term:o_rx_rst -> alt_mge_xcvr_directphy:i_rx_reset
	wire   [0:0] alt_mge_xcvr_directphy_o_tx_reset_ack_tx_reset_ack;                                 // alt_mge_xcvr_directphy:o_tx_reset_ack -> xcvr_term:i_tx_rst_ack
	wire   [0:0] alt_mge_xcvr_directphy_o_rx_reset_ack_rx_reset_ack;                                 // alt_mge_xcvr_directphy:o_rx_reset_ack -> xcvr_term:i_rx_rst_ack
	wire   [0:0] alt_mge_xcvr_directphy_o_tx_ready_tx_ready;                                         // alt_mge_xcvr_directphy:o_tx_ready -> xcvr_term:i_tx_ready
	wire   [0:0] alt_mge_xcvr_directphy_o_rx_ready_rx_ready;                                         // alt_mge_xcvr_directphy:o_rx_ready -> xcvr_term:i_rx_ready
	wire         xcvr_term_det_lat_rx_dl_clk_det_lat_rx_dl_clk;                                      // xcvr_term:det_lat_rx_dl_clk -> alt_mge_xcvr_directphy:i_det_lat_rx_dl_clk
	wire         xcvr_term_det_lat_rx_mux_select_det_lat_rx_mux_select;                              // xcvr_term:det_lat_rx_mux_select -> alt_mge_xcvr_directphy:i_det_lat_rx_mux_select
	wire         xcvr_term_det_lat_rx_sclk_flop_det_lat_rx_sclk_flop;                                // xcvr_term:det_lat_rx_sclk_flop -> alt_mge_xcvr_directphy:i_det_lat_rx_sclk_flop
	wire         xcvr_term_det_lat_rx_sclk_gen_clk_det_lat_rx_sclk_gen_clk;                          // xcvr_term:det_lat_rx_sclk_gen_clk -> alt_mge_xcvr_directphy:i_det_lat_rx_sclk_gen_clk
	wire         xcvr_term_det_lat_rx_trig_flop_det_lat_rx_trig_flop;                                // xcvr_term:det_lat_rx_trig_flop -> alt_mge_xcvr_directphy:i_det_lat_rx_trig_flop
	wire         xcvr_term_det_lat_sampling_clk_det_lat_sampling_clk;                                // xcvr_term:det_lat_sampling_clk -> alt_mge_xcvr_directphy:i_det_lat_sampling_clk
	wire         xcvr_term_det_lat_tx_dl_clk_det_lat_tx_dl_clk;                                      // xcvr_term:det_lat_tx_dl_clk -> alt_mge_xcvr_directphy:i_det_lat_tx_dl_clk
	wire         xcvr_term_det_lat_tx_mux_select_det_lat_tx_mux_select;                              // xcvr_term:det_lat_tx_mux_select -> alt_mge_xcvr_directphy:i_det_lat_tx_mux_select
	wire         xcvr_term_det_lat_tx_sclk_flop_det_lat_tx_sclk_flop;                                // xcvr_term:det_lat_tx_sclk_flop -> alt_mge_xcvr_directphy:i_det_lat_tx_sclk_flop
	wire         xcvr_term_det_lat_tx_sclk_gen_clk_det_lat_tx_sclk_gen_clk;                          // xcvr_term:det_lat_tx_sclk_gen_clk -> alt_mge_xcvr_directphy:i_det_lat_tx_sclk_gen_clk
	wire         xcvr_term_det_lat_tx_trig_flop_det_lat_tx_trig_flop;                                // xcvr_term:det_lat_tx_trig_flop -> alt_mge_xcvr_directphy:i_det_lat_tx_trig_flop
	wire   [0:0] alt_mge_xcvr_directphy_o_det_lat_rx_async_dl_sync_det_lat_rx_async_dl_sync;         // alt_mge_xcvr_directphy:o_det_lat_rx_async_dl_sync -> xcvr_term:det_lat_rx_async_dl_sync
	wire   [0:0] alt_mge_xcvr_directphy_o_det_lat_rx_async_pulse_det_lat_rx_async_pulse;             // alt_mge_xcvr_directphy:o_det_lat_rx_async_pulse -> xcvr_term:det_lat_rx_async_pulse
	wire   [0:0] alt_mge_xcvr_directphy_o_det_lat_rx_async_sample_sync_det_lat_rx_async_sample_sync; // alt_mge_xcvr_directphy:o_det_lat_rx_async_sample_sync -> xcvr_term:det_lat_rx_async_sample_sync
	wire   [0:0] alt_mge_xcvr_directphy_o_det_lat_rx_sclk_sample_sync_det_lat_rx_sclk_sample_sync;   // alt_mge_xcvr_directphy:o_det_lat_rx_sclk_sample_sync -> xcvr_term:det_lat_rx_sclk_sample_sync
	wire   [0:0] alt_mge_xcvr_directphy_o_det_lat_rx_trig_sample_sync_det_lat_rx_trig_sample_sync;   // alt_mge_xcvr_directphy:o_det_lat_rx_trig_sample_sync -> xcvr_term:det_lat_rx_trig_sample_sync
	wire   [0:0] alt_mge_xcvr_directphy_o_det_lat_tx_async_dl_sync_det_lat_tx_async_dl_sync;         // alt_mge_xcvr_directphy:o_det_lat_tx_async_dl_sync -> xcvr_term:det_lat_tx_async_dl_sync
	wire   [0:0] alt_mge_xcvr_directphy_o_det_lat_tx_async_pulse_det_lat_tx_async_pulse;             // alt_mge_xcvr_directphy:o_det_lat_tx_async_pulse -> xcvr_term:det_lat_tx_async_pulse
	wire   [0:0] alt_mge_xcvr_directphy_o_det_lat_tx_async_sample_sync_det_lat_tx_async_sample_sync; // alt_mge_xcvr_directphy:o_det_lat_tx_async_sample_sync -> xcvr_term:det_lat_tx_async_sample_sync
	wire   [0:0] alt_mge_xcvr_directphy_o_det_lat_tx_sclk_sample_sync_det_lat_tx_sclk_sample_sync;   // alt_mge_xcvr_directphy:o_det_lat_tx_sclk_sample_sync -> xcvr_term:det_lat_tx_sclk_sample_sync
	wire   [0:0] alt_mge_xcvr_directphy_o_det_lat_tx_trig_sample_sync_det_lat_tx_trig_sample_sync;   // alt_mge_xcvr_directphy:o_det_lat_tx_trig_sample_sync -> xcvr_term:det_lat_tx_trig_sample_sync
	wire   [0:0] alt_mge_xcvr_directphy_o_xcvrif_rx_latency_pulse_xcvrif_rx_latency_pulse;           // alt_mge_xcvr_directphy:o_xcvrif_rx_latency_pulse -> xcvr_term:xcvrif_rx_latency_pulse
	wire   [0:0] alt_mge_xcvr_directphy_o_xcvrif_tx_latency_pulse_xcvrif_tx_latency_pulse;           // alt_mge_xcvr_directphy:o_xcvrif_tx_latency_pulse -> xcvr_term:xcvrif_tx_latency_pulse
	wire         mge_pcs_tx_digitalreset_to_xcvr_tx_digitalreset;                                    // mge_pcs:tx_digitalreset_to_xcvr -> xcvr_term:tx_digitalreset_to_xcvr_in
	wire         mge_pcs_rx_digitalreset_to_xcvr_rx_digitalreset;                                    // mge_pcs:rx_digitalreset_to_xcvr -> xcvr_term:rx_digitalreset_to_xcvr_in

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (ENABLE_GMII_ADAPTER != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					enable_gmii_adapter_check ( .error(1'b1) );
		end
		if (ENABLE_DL != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					enable_dl_check ( .error(1'b1) );
		end
	endgenerate

	alt_mge_phy_pcs #(
		.DEVICE_FAMILY       ("Agilex 5"),
		.DEV_VERSION         (256),
		.PHY_IDENTIFIER      (0),
		.ENABLE_IEEE1588     (0),
		.ENABLE_SGMII        (0),
		.ENABLE_GMII_ADAPTER (1),
		.PMA_MODE            (40),
		.IS_2P5G             (0),
		.IS_1G_2P5G          (1),
		.IS_1G_10G           (0),
		.IS_MGBASE_T         (0),
		.IS_10G_USXGMII      (0)
	) mge_pcs (
		.csr_clk                   (csr_clk),                                                              //   input,   width = 1,                   csr_clk.clk
		.rx_pma_clk                (xcvr_term_rx_clkout_out_pcs_clk),                                      //   input,   width = 1,                rx_pma_clk.clk
		.tx_pma_clk                (xcvr_term_tx_clkout_out_pcs_clk),                                      //   input,   width = 1,                tx_pma_clk.clk
		.rx_mac_clk_125            (iopll_tx_outclk3_clk),                                                 //   input,   width = 1,            rx_mac_clk_125.clk
		.tx_mac_clk_125            (iopll_tx_outclk2_clk),                                                 //   input,   width = 1,            tx_mac_clk_125.clk
		.tx_8b_clk                 (iopll_tx_outclk0_clk),                                                 //   input,   width = 1,                 tx_8b_clk.clk
		.gmii8b_tx_clkin           (gmii8b_tx_clkin),                                                      //   input,   width = 1,           gmii8b_tx_clkin.clk
		.rx_mac_clk                (iopll_tx_outclk1_clk),                                                 //   input,   width = 1,                rx_mac_clk.clk
		.tx_mac_clk                (iopll_tx_outclk1_clk),                                                 //   input,   width = 1,                tx_mac_clk.clk
		.tx_clkout                 (tx_clkout),                                                            //  output,   width = 1,                 tx_clkout.clk
		.rx_clkout                 (rx_clkout),                                                            //  output,   width = 1,                 rx_clkout.clk
		.gmii8b_tx_rst_n           (gmii8b_tx_rst_n),                                                      //   input,   width = 1,           gmii8b_tx_rst_n.gmii8b_tx_rst_n
		.gmii8b_rx_rst_n           (gmii8b_rx_rst_n),                                                      //   input,   width = 1,           gmii8b_rx_rst_n.gmii8b_rx_rst_n
		.gmii8b_rx_clkout          (gmii8b_rx_clkout),                                                     //  output,   width = 1,          gmii8b_rx_clkout.clk
		.gmii8b_tx_clkout          (gmii8b_tx_clkout),                                                     //  output,   width = 1,          gmii8b_tx_clkout.clk
		.reset                     (reset),                                                                //   input,   width = 1,                     reset.reset
		.rx_digitalreset           (rx_digitalreset),                                                      //   input,   width = 1,           rx_digitalreset.rx_digitalreset
		.tx_digitalreset           (tx_digitalreset),                                                      //   input,   width = 1,           tx_digitalreset.tx_digitalreset
		.rx_digitalreset_to_xcvr   (mge_pcs_rx_digitalreset_to_xcvr_rx_digitalreset),                      //  output,   width = 1,   rx_digitalreset_to_xcvr.rx_digitalreset
		.tx_digitalreset_to_xcvr   (mge_pcs_tx_digitalreset_to_xcvr_tx_digitalreset),                      //  output,   width = 1,   tx_digitalreset_to_xcvr.tx_digitalreset
		.csr_readdata              (csr_readdata),                                                         //  output,  width = 16,             avalon_mm_csr.readdata
		.csr_writedata             (csr_writedata),                                                        //   input,  width = 16,                          .writedata
		.csr_address               (csr_address),                                                          //   input,   width = 5,                          .address
		.csr_waitrequest           (csr_waitrequest),                                                      //  output,   width = 1,                          .waitrequest
		.csr_read                  (csr_read),                                                             //   input,   width = 1,                          .read
		.csr_write                 (csr_write),                                                            //   input,   width = 1,                          .write
		.tx_gmii8b_en              (gmii8b_mac_txen),                                                      //   input,   width = 1,              tx_gmii8b_en.export
		.tx_gmii8b_d               (gmii8b_mac_tx_d),                                                      //   input,   width = 8,               tx_gmii8b_d.export
		.tx_gmii8b_err             (gmii8b_mac_txer),                                                      //   input,   width = 1,             tx_gmii8b_err.export
		.rx_gmii8b_dv              (gmii8b_mac_rxdv),                                                      //  output,   width = 1,              rx_gmii8b_dv.export
		.rx_gmii8b_d               (gmii8b_mac_rxd),                                                       //  output,   width = 8,               rx_gmii8b_d.export
		.rx_gmii8b_err             (gmii8b_mac_rxer),                                                      //  output,   width = 1,             rx_gmii8b_err.export
		.gmii8b_mac_speed          (gmii8b_mac_speed),                                                     //   input,   width = 2,          gmii8b_mac_speed.export
		.mrphy_pll_lock_pcs        (iopll_tx_locked_export),                                               //   input,   width = 1,        mrphy_pll_lock_pcs.export
		.tx_basex_parallel_data    (mge_pcs_tx_basex_parallel_data_tx_parallel_data),                      //  output,  width = 20,    tx_basex_parallel_data.tx_parallel_data
		.rx_basex_parallel_data    (xcvr_term_rx_basex_parallel_data_rx_parallel_data),                    //   input,  width = 20,    rx_basex_parallel_data.rx_parallel_data
		.led_link                  (led_link),                                                             //  output,   width = 1,                  led_link.export
		.led_char_err              (led_char_err),                                                         //  output,   width = 1,              led_char_err.export
		.led_disp_err              (led_disp_err),                                                         //  output,   width = 1,              led_disp_err.export
		.led_an                    (led_an),                                                               //  output,   width = 1,                    led_an.export
		.rx_syncstatus             (xcvr_term_rx_syncstatus_a10_rx_syncstatus),                            //   input,   width = 2,             rx_syncstatus.rx_syncstatus
		.rx_runningdisp            (xcvr_term_rx_runningdisp_a10_rx_runningdisp),                          //   input,   width = 2,            rx_runningdisp.rx_runningdisp
		.rx_disperr                (xcvr_term_rx_disperr_a10_rx_disperr),                                  //   input,   width = 2,                rx_disperr.rx_disperr
		.rx_errdetect              (xcvr_term_rx_errdetect_a10_rx_errdetect),                              //   input,   width = 2,              rx_errdetect.rx_errdetect
		.rx_patterndetect          (xcvr_term_rx_patterndetect_a10_rx_patterndetect),                      //   input,   width = 2,          rx_patterndetect.rx_patterndetect
		.rx_std_bitslipboundarysel (),                                                                     //   input,   width = 5, rx_std_bitslipboundarysel.rx_std_bitslipboundarysel
		.latency_sclk              (xcvr_term_latency_sclk_to_pcs_clk),                                    //   input,   width = 1,              latency_sclk.clk
		.xcvr_mode                 (xcvr_term_xcvr_mode_out_export),                                       //   input,   width = 2,                 xcvr_mode.export
		.operating_speed           (operating_speed),                                                      //  output,   width = 3,           operating_speed.export
		.rx_seriallpbken           (),                                                                     //  output,   width = 1,           rx_seriallpbken.rx_seriallpbken
		.pll_locked_stable         (mrphy_pll_lock),                                                       //  output,   width = 1,         pll_locked_stable.pll_locked_stable
		.rx_xgmii_clk              (1'b0),                                                                 // (terminated),                                        
		.tx_xgmii_clk              (1'b0),                                                                 // (terminated),                                        
		.tx_xgmii_valid_in         (1'b0),                                                                 // (terminated),                                        
		.tx_xgmii_control_in       (8'b00000000),                                                          // (terminated),                                        
		.tx_xgmii_data_in          (64'b0000000000000000000000000000000000000000000000000000000000000000), // (terminated),                                        
		.rx_xgmii_valid_in         (1'b0),                                                                 // (terminated),                                        
		.rx_xgmii_control_in       (8'b00000000),                                                          // (terminated),                                        
		.rx_xgmii_data_in          (64'b0000000000000000000000000000000000000000000000000000000000000000), // (terminated),                                        
		.rx_block_lock_in          (1'b0),                                                                 // (terminated),                                        
		.latency_measure_clk       (1'b0),                                                                 // (terminated),                                        
		.tx_gmii16b_en             (2'b00),                                                                // (terminated),                                        
		.tx_gmii16b_d              (16'b0000000000000000),                                                 // (terminated),                                        
		.tx_gmii16b_err            (2'b00),                                                                // (terminated),                                        
		.rx_gmii16b_dv             (),                                                                     // (terminated),                                        
		.rx_gmii16b_d              (),                                                                     // (terminated),                                        
		.rx_gmii16b_err            (),                                                                     // (terminated),                                        
		.tx_xgmii_valid_out        (),                                                                     // (terminated),                                        
		.tx_xgmii_control_out      (),                                                                     // (terminated),                                        
		.tx_xgmii_data_out         (),                                                                     // (terminated),                                        
		.tx_mii_d                  (),                                                                     // (terminated),                                        
		.tx_mii_c                  (),                                                                     // (terminated),                                        
		.tx_mii_valid              (),                                                                     // (terminated),                                        
		.tx_mii_am                 (),                                                                     // (terminated),                                        
		.tx_mii_ready              (1'b0),                                                                 // (terminated),                                        
		.rx_mii_d                  (64'b0000000000000000000000000000000000000000000000000000000000000000), // (terminated),                                        
		.rx_mii_c                  (8'b00000000),                                                          // (terminated),                                        
		.rx_mii_valid              (1'b0),                                                                 // (terminated),                                        
		.rx_mii_am_valid           (1'b0),                                                                 // (terminated),                                        
		.rx_block_lock_fm_in       (1'b0),                                                                 // (terminated),                                        
		.rx_am_lock                (1'b0),                                                                 // (terminated),                                        
		.local_fault_status        (1'b0),                                                                 // (terminated),                                        
		.remote_fault_status       (1'b0),                                                                 // (terminated),                                        
		.stats_snapshot            (),                                                                     // (terminated),                                        
		.rx_hi_ber                 (1'b0),                                                                 // (terminated),                                        
		.rx_pcs_fully_aligned      (1'b0),                                                                 // (terminated),                                        
		.rx_xgmii_valid_out        (),                                                                     // (terminated),                                        
		.rx_xgmii_control_out      (),                                                                     // (terminated),                                        
		.rx_xgmii_data_out         (),                                                                     // (terminated),                                        
		.rx_clkena                 (),                                                                     // (terminated),                                        
		.tx_clkena                 (),                                                                     // (terminated),                                        
		.led_panel_link            (),                                                                     // (terminated),                                        
		.rx_umii_fault_status      (),                                                                     // (terminated),                                        
		.rx_block_lock_out         (),                                                                     // (terminated),                                        
		.tx_gmii16b_latency        (),                                                                     // (terminated),                                        
		.rx_gmii16b_latency        (),                                                                     // (terminated),                                        
		.rx_pma_clkout             (1'b0),                                                                 // (terminated),                                        
		.rx_fm_ff_sample_clk       (1'b0),                                                                 // (terminated),                                        
		.tx_fifo_latency_pulse     (1'b0),                                                                 // (terminated),                                        
		.tx_pcs_fifo_latency_pulse (1'b0),                                                                 // (terminated),                                        
		.rx_fifo_latency_pulse     (1'b0),                                                                 // (terminated),                                        
		.rx_pcs_fifo_latency_pulse (1'b0),                                                                 // (terminated),                                        
		.tx_dl_async_pulse         (1'b0),                                                                 // (terminated),                                        
		.rx_dl_async_pulse         (1'b0),                                                                 // (terminated),                                        
		.tx_dl_measure_sel         (),                                                                     // (terminated),                                        
		.rx_dl_measure_sel         (),                                                                     // (terminated),                                        
		.dl_async_cal_pulse        (),                                                                     // (terminated),                                        
		.cdr_lock                  (1'b0),                                                                 // (terminated),                                        
		.tx_pll_locked             (1'b0),                                                                 // (terminated),                                        
		.tx_lanes_stable           (1'b0),                                                                 // (terminated),                                        
		.rx_pcs_ready              (1'b0),                                                                 // (terminated),                                        
		.o_cdr_lock                (),                                                                     // (terminated),                                        
		.o_tx_pll_locked           (),                                                                     // (terminated),                                        
		.o_tx_lanes_stable         (),                                                                     // (terminated),                                        
		.o_rx_pcs_ready            (),                                                                     // (terminated),                                        
		.rx_xgmii_latency          (),                                                                     // (terminated),                                        
		.tx_xgmii_latency          ()                                                                      // (terminated),                                        
	);

	alt_mge16_phy_xcvr_term #(
		.DEVICE_FAMILY       ("Agilex 5"),
		.BASER_REG_MODE      (1),
		.ENABLE_IEEE1588     (0),
		.ENABLE_GMII_ADAPTER (1),
		.IS_2P5G             (0),
		.IS_1G_2P5G          (1),
		.IS_1G_10G           (0),
		.IS_MGBASE_T         (0),
		.IS_10G_USXGMII      (0),
		.ENABLE_RX_PIPELINE  (1)
	) xcvr_term (
		.o_src_ch_pause_request       (i_src_ch_pause_request),                                                                                                                //   input,   width = 1,       o_src_ch_pause_request.o_src_ch_pause_request
		.i_src_ch_pause_grant         (o_src_ch_pause_grant),                                                                                                                  //  output,   width = 1,         i_src_ch_pause_grant.i_src_ch_pause_grant
		.i_rst_n                      (i_rst_n),                                                                                                                               //   input,   width = 1,                      i_rst_n.i_rst_n
		.o_rst_ack_n                  (o_rst_ack_n),                                                                                                                           //  output,   width = 1,                  o_rst_ack_n.o_rst_ack_n
		.i_tx_rst_n                   (i_tx_rst_n),                                                                                                                            //   input,   width = 1,                   i_tx_rst_n.i_tx_rst_n
		.i_rx_rst_n                   (i_rx_rst_n),                                                                                                                            //   input,   width = 1,                   i_rx_rst_n.i_rx_rst_n
		.o_tx_rst                     (xcvr_term_o_tx_rst_tx_reset),                                                                                                           //  output,   width = 1,                     o_tx_rst.tx_reset
		.o_rx_rst                     (xcvr_term_o_rx_rst_rx_reset),                                                                                                           //  output,   width = 1,                     o_rx_rst.rx_reset
		.i_tx_rst_ack                 (alt_mge_xcvr_directphy_o_tx_reset_ack_tx_reset_ack),                                                                                    //   input,   width = 1,                 i_tx_rst_ack.tx_reset_ack
		.i_rx_rst_ack                 (alt_mge_xcvr_directphy_o_rx_reset_ack_rx_reset_ack),                                                                                    //   input,   width = 1,                 i_rx_rst_ack.rx_reset_ack
		.o_tx_rst_ack_n               (o_tx_rst_ack_n),                                                                                                                        //  output,   width = 1,               o_tx_rst_ack_n.o_tx_rst_ack_n
		.o_rx_rst_ack_n               (o_rx_rst_ack_n),                                                                                                                        //  output,   width = 1,               o_rx_rst_ack_n.o_rx_rst_ack_n
		.tx_digitalreset_to_xcvr_in   (mge_pcs_tx_digitalreset_to_xcvr_tx_digitalreset),                                                                                       //   input,   width = 1,   tx_digitalreset_to_xcvr_in.tx_digitalreset
		.tx_digitalreset_to_xcvr_out  (),                                                                                                                                      //  output,   width = 1,  tx_digitalreset_to_xcvr_out.tx_digitalreset
		.rx_digitalreset_to_xcvr_in   (mge_pcs_rx_digitalreset_to_xcvr_rx_digitalreset),                                                                                       //   input,   width = 1,   rx_digitalreset_to_xcvr_in.rx_digitalreset
		.rx_digitalreset_to_xcvr_out  (),                                                                                                                                      //  output,   width = 1,  rx_digitalreset_to_xcvr_out.rx_digitalreset
		.tx_serial_clk_in             (),                                                                                                                                      //   input,   width = 2,             tx_serial_clk_in.clk
		.tx_serial_clk_out0_a10       (),                                                                                                                                      //  output,   width = 1,       tx_serial_clk_out0_a10.clk
		.tx_serial_clk_out1_a10       (),                                                                                                                                      //  output,   width = 1,       tx_serial_clk_out1_a10.clk
		.rx_cdr_refclk_in_0           (rx_cdr_refclk_p),                                                                                                                       //   input,   width = 1,           rx_cdr_refclk_in_0.clk
		.rx_cdr_refclk_out0_a10       (xcvr_term_rx_cdr_refclk_out0_a10_clk),                                                                                                  //  output,   width = 1,       rx_cdr_refclk_out0_a10.clk
		.latency_sclk_to_xcvr         (),                                                                                                                                      //  output,   width = 1,         latency_sclk_to_xcvr.clk
		.latency_sclk_to_pcs          (xcvr_term_latency_sclk_to_pcs_clk),                                                                                                     //  output,   width = 1,          latency_sclk_to_pcs.clk
		.tx_clkout_out_pcs            (xcvr_term_tx_clkout_out_pcs_clk),                                                                                                       //  output,   width = 1,            tx_clkout_out_pcs.clk
		.tx_clkout_out_mac            (),                                                                                                                                      //  output,   width = 1,            tx_clkout_out_mac.clk
		.tx_clkout_in                 (alt_mge_xcvr_directphy_o_tx_clkout_clk),                                                                                                //   input,   width = 1,                 tx_clkout_in.clk
		.permit_cal                   (xcvr_term_permit_cal_export),                                                                                                           //  output,   width = 1,                   permit_cal.export
		.i_tx_ready                   (alt_mge_xcvr_directphy_o_tx_ready_tx_ready),                                                                                            //   input,   width = 1,                   i_tx_ready.tx_ready
		.i_rx_ready                   (alt_mge_xcvr_directphy_o_rx_ready_rx_ready),                                                                                            //   input,   width = 1,                   i_rx_ready.rx_ready
		.o_tx_ready                   (tx_ready),                                                                                                                              //  output,   width = 1,                   o_tx_ready.tx_ready
		.o_rx_ready                   (rx_ready),                                                                                                                              //  output,   width = 1,                   o_rx_ready.rx_ready
		.tx_digitalreset_iopll        (xcvr_term_tx_digitalreset_iopll_reset),                                                                                                 //  output,   width = 1,        tx_digitalreset_iopll.reset
		.tx_clkout_in_2               (alt_mge_xcvr_directphy_o_tx_clkout2_clk),                                                                                               //   input,   width = 1,               tx_clkout_in_2.clk
		.tx_coreclkin_out_xcvr        (xcvr_term_tx_coreclkin_out_xcvr_clk),                                                                                                   //  output,   width = 1,        tx_coreclkin_out_xcvr.clk
		.rx_clkout_out_pcs            (xcvr_term_rx_clkout_out_pcs_clk),                                                                                                       //  output,   width = 1,            rx_clkout_out_pcs.clk
		.rx_clkout_out_mac            (),                                                                                                                                      //  output,   width = 1,            rx_clkout_out_mac.clk
		.rx_clkout_in                 (alt_mge_xcvr_directphy_o_rx_clkout_clk),                                                                                                //   input,   width = 1,                 rx_clkout_in.clk
		.rx_coreclkin_out_xcvr        (xcvr_term_rx_coreclkin_out_xcvr_clk),                                                                                                   //  output,   width = 1,        rx_coreclkin_out_xcvr.clk
		.rx_pma_clkout_in             (alt_mge_xcvr_directphy_o_rx_clkout2_clk),                                                                                               //   input,   width = 1,             rx_pma_clkout_in.clk
		.rx_pma_clkout_out            (rx_pma_clkout),                                                                                                                         //  output,   width = 1,            rx_pma_clkout_out.clk
		.rx_seriallpbken_out          (),                                                                                                                                      //  output,   width = 1,          rx_seriallpbken_out.rx_seriallpbken
		.xcvr_mode_in                 (xcvr_mode),                                                                                                                             //   input,   width = 2,                 xcvr_mode_in.export
		.xcvr_mode_out                (xcvr_term_xcvr_mode_out_export),                                                                                                        //  output,   width = 2,                xcvr_mode_out.export
		.det_lat_rx_dl_clk            (xcvr_term_det_lat_rx_dl_clk_det_lat_rx_dl_clk),                                                                                         //  output,   width = 1,            det_lat_rx_dl_clk.det_lat_rx_dl_clk
		.det_lat_rx_mux_select        (xcvr_term_det_lat_rx_mux_select_det_lat_rx_mux_select),                                                                                 //  output,   width = 1,        det_lat_rx_mux_select.det_lat_rx_mux_select
		.det_lat_rx_sclk_flop         (xcvr_term_det_lat_rx_sclk_flop_det_lat_rx_sclk_flop),                                                                                   //  output,   width = 1,         det_lat_rx_sclk_flop.det_lat_rx_sclk_flop
		.det_lat_rx_sclk_gen_clk      (xcvr_term_det_lat_rx_sclk_gen_clk_det_lat_rx_sclk_gen_clk),                                                                             //  output,   width = 1,      det_lat_rx_sclk_gen_clk.det_lat_rx_sclk_gen_clk
		.det_lat_rx_trig_flop         (xcvr_term_det_lat_rx_trig_flop_det_lat_rx_trig_flop),                                                                                   //  output,   width = 1,         det_lat_rx_trig_flop.det_lat_rx_trig_flop
		.det_lat_sampling_clk         (xcvr_term_det_lat_sampling_clk_det_lat_sampling_clk),                                                                                   //  output,   width = 1,         det_lat_sampling_clk.det_lat_sampling_clk
		.det_lat_tx_dl_clk            (xcvr_term_det_lat_tx_dl_clk_det_lat_tx_dl_clk),                                                                                         //  output,   width = 1,            det_lat_tx_dl_clk.det_lat_tx_dl_clk
		.det_lat_tx_mux_select        (xcvr_term_det_lat_tx_mux_select_det_lat_tx_mux_select),                                                                                 //  output,   width = 1,        det_lat_tx_mux_select.det_lat_tx_mux_select
		.det_lat_tx_sclk_flop         (xcvr_term_det_lat_tx_sclk_flop_det_lat_tx_sclk_flop),                                                                                   //  output,   width = 1,         det_lat_tx_sclk_flop.det_lat_tx_sclk_flop
		.det_lat_tx_sclk_gen_clk      (xcvr_term_det_lat_tx_sclk_gen_clk_det_lat_tx_sclk_gen_clk),                                                                             //  output,   width = 1,      det_lat_tx_sclk_gen_clk.det_lat_tx_sclk_gen_clk
		.det_lat_tx_trig_flop         (xcvr_term_det_lat_tx_trig_flop_det_lat_tx_trig_flop),                                                                                   //  output,   width = 1,         det_lat_tx_trig_flop.det_lat_tx_trig_flop
		.det_lat_rx_async_dl_sync     (alt_mge_xcvr_directphy_o_det_lat_rx_async_dl_sync_det_lat_rx_async_dl_sync),                                                            //   input,   width = 1,     det_lat_rx_async_dl_sync.det_lat_rx_async_dl_sync
		.det_lat_rx_async_pulse       (alt_mge_xcvr_directphy_o_det_lat_rx_async_pulse_det_lat_rx_async_pulse),                                                                //   input,   width = 1,       det_lat_rx_async_pulse.det_lat_rx_async_pulse
		.det_lat_rx_async_sample_sync (alt_mge_xcvr_directphy_o_det_lat_rx_async_sample_sync_det_lat_rx_async_sample_sync),                                                    //   input,   width = 1, det_lat_rx_async_sample_sync.det_lat_rx_async_sample_sync
		.det_lat_rx_sclk_sample_sync  (alt_mge_xcvr_directphy_o_det_lat_rx_sclk_sample_sync_det_lat_rx_sclk_sample_sync),                                                      //   input,   width = 1,  det_lat_rx_sclk_sample_sync.det_lat_rx_sclk_sample_sync
		.det_lat_rx_trig_sample_sync  (alt_mge_xcvr_directphy_o_det_lat_rx_trig_sample_sync_det_lat_rx_trig_sample_sync),                                                      //   input,   width = 1,  det_lat_rx_trig_sample_sync.det_lat_rx_trig_sample_sync
		.det_lat_tx_async_dl_sync     (alt_mge_xcvr_directphy_o_det_lat_tx_async_dl_sync_det_lat_tx_async_dl_sync),                                                            //   input,   width = 1,     det_lat_tx_async_dl_sync.det_lat_tx_async_dl_sync
		.det_lat_tx_async_pulse       (alt_mge_xcvr_directphy_o_det_lat_tx_async_pulse_det_lat_tx_async_pulse),                                                                //   input,   width = 1,       det_lat_tx_async_pulse.det_lat_tx_async_pulse
		.det_lat_tx_async_sample_sync (alt_mge_xcvr_directphy_o_det_lat_tx_async_sample_sync_det_lat_tx_async_sample_sync),                                                    //   input,   width = 1, det_lat_tx_async_sample_sync.det_lat_tx_async_sample_sync
		.det_lat_tx_sclk_sample_sync  (alt_mge_xcvr_directphy_o_det_lat_tx_sclk_sample_sync_det_lat_tx_sclk_sample_sync),                                                      //   input,   width = 1,  det_lat_tx_sclk_sample_sync.det_lat_tx_sclk_sample_sync
		.det_lat_tx_trig_sample_sync  (alt_mge_xcvr_directphy_o_det_lat_tx_trig_sample_sync_det_lat_tx_trig_sample_sync),                                                      //   input,   width = 1,  det_lat_tx_trig_sample_sync.det_lat_tx_trig_sample_sync
		.xcvrif_rx_latency_pulse      (alt_mge_xcvr_directphy_o_xcvrif_rx_latency_pulse_xcvrif_rx_latency_pulse),                                                              //   input,   width = 1,      xcvrif_rx_latency_pulse.xcvrif_rx_latency_pulse
		.xcvrif_tx_latency_pulse      (alt_mge_xcvr_directphy_o_xcvrif_tx_latency_pulse_xcvrif_tx_latency_pulse),                                                              //   input,   width = 1,      xcvrif_tx_latency_pulse.xcvrif_tx_latency_pulse
		.tx_basex_parallel_data       (mge_pcs_tx_basex_parallel_data_tx_parallel_data),                                                                                       //   input,  width = 20,       tx_basex_parallel_data.tx_parallel_data
		.rx_basex_parallel_data       (xcvr_term_rx_basex_parallel_data_rx_parallel_data),                                                                                     //  output,  width = 20,       rx_basex_parallel_data.rx_parallel_data
		.rx_syncstatus_a10            (xcvr_term_rx_syncstatus_a10_rx_syncstatus),                                                                                             //  output,   width = 2,            rx_syncstatus_a10.rx_syncstatus
		.rx_runningdisp_a10           (xcvr_term_rx_runningdisp_a10_rx_runningdisp),                                                                                           //  output,   width = 2,           rx_runningdisp_a10.rx_runningdisp
		.rx_disperr_a10               (xcvr_term_rx_disperr_a10_rx_disperr),                                                                                                   //  output,   width = 2,               rx_disperr_a10.rx_disperr
		.rx_errdetect_a10             (xcvr_term_rx_errdetect_a10_rx_errdetect),                                                                                               //  output,   width = 2,             rx_errdetect_a10.rx_errdetect
		.rx_patterndetect_a10         (xcvr_term_rx_patterndetect_a10_rx_patterndetect),                                                                                       //  output,   width = 2,         rx_patterndetect_a10.rx_patterndetect
		.tx_parallel_data_sm          (xcvr_term_tx_parallel_data_sm_i_tx_parallel_data),                                                                                      //  output,  width = 80,          tx_parallel_data_sm.i_tx_parallel_data
		.rx_parallel_data_sm          (alt_mge_xcvr_directphy_o_rx_parallel_data_o_rx_parallel_data),                                                                          //   input,  width = 80,          rx_parallel_data_sm.o_rx_parallel_data
		.tx_serial_clk_out_28nm       (),                                                                                                                                      // (terminated),                                           
		.tx_serial_clk_out2_a10       (),                                                                                                                                      // (terminated),                                           
		.rx_cdr_refclk_out_28nm       (),                                                                                                                                      // (terminated),                                           
		.latency_sclk                 (1'b0),                                                                                                                                  // (terminated),                                           
		.i_tx_dl_sync_pulse           (1'b0),                                                                                                                                  // (terminated),                                           
		.o_rx_dl_sync_pulse           (),                                                                                                                                      // (terminated),                                           
		.tx_xgmii_coreclkin           (1'b0),                                                                                                                                  // (terminated),                                           
		.rx_xgmii_coreclkin           (1'b0),                                                                                                                                  // (terminated),                                           
		.rx_seriallpbken_in           (1'b0),                                                                                                                                  // (terminated),                                           
		.tx_baser_control             (8'b00000000),                                                                                                                           // (terminated),                                           
		.tx_baser_parallel_data       (64'b0000000000000000000000000000000000000000000000000000000000000000),                                                                  // (terminated),                                           
		.tx_baser_data_valid          (1'b0),                                                                                                                                  // (terminated),                                           
		.rx_baser_control             (),                                                                                                                                      // (terminated),                                           
		.rx_baser_control_fec         (),                                                                                                                                      // (terminated),                                           
		.rx_baser_parallel_data       (),                                                                                                                                      // (terminated),                                           
		.rx_baser_data_valid          (),                                                                                                                                      // (terminated),                                           
		.rx_enh_blk_lock_in           (1'b0),                                                                                                                                  // (terminated),                                           
		.rx_enh_blk_lock_out          (),                                                                                                                                      // (terminated),                                           
		.unused_tx_parallel_data_28nm (),                                                                                                                                      // (terminated),                                           
		.unused_rx_parallel_data_28nm (36'b000000000000000000000000000000000000),                                                                                              // (terminated),                                           
		.tx_control_a10               (),                                                                                                                                      // (terminated),                                           
		.tx_parallel_data_a10         (),                                                                                                                                      // (terminated),                                           
		.rx_control_a10               (20'b00000000000000000000),                                                                                                              // (terminated),                                           
		.rx_parallel_data_a10         (128'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000), // (terminated),                                           
		.tx_enh_data_valid_out        (),                                                                                                                                      // (terminated),                                           
		.rx_enh_data_valid_in         (1'b0),                                                                                                                                  // (terminated),                                           
		.rx_enh_highber_in            (1'b0),                                                                                                                                  // (terminated),                                           
		.rx_enh_highber_clr_cnt_out   (),                                                                                                                                      // (terminated),                                           
		.rx_enh_clr_errblk_count_out  ()                                                                                                                                       // (terminated),                                           
	);

	alt_mge_phy_0_intel_directphy_gts_200_twelxbq #(
		.num_sys_cop                            (1),
		.num_xcvr_per_sys                       (1),
		.duplex_mode                            ("duplex"),
		.rx_deskew_en                           (0),
		.l_num_aib_per_xcvr                     (1),
		.l_sys_xcvrs                            (1),
		.l_quad_num                             (1),
		.l_sys_xcvrs_cascade                    (1),
		.l_sys_aibs                             (1),
		.l_tx_enable                            (1),
		.l_rx_enable                            (1),
		.l_fec_mode                             ("IEEE 802.3 BASE-R Firecode (CL 74)"),
		.l_av1_enable                           (1),
		.avmm1_readdv_enable                    (1),
		.avmm1_split                            (0),
		.avmm1_jtag_enable                      (0),
		.l_av1_aib_enable                       (0),
		.l_soft_csr_enable                      (0),
		.l_num_avmm1                            (1),
		.l_av1_ifaces                           (1),
		.l_av1_addr_bits                        (18),
		.l_line_rate_p1ghz                      (31),
		.silicon_revision                       ("14nm5bcr3a"),
		.device_revision                        ("14nm5bcr3a"),
		.enable_port_latency_measurement        (1),
		.l_rx_deskew_enable                     (0),
		.txparalleldata_width                   (80),
		.txsimpleinterface_enable               (0),
		.simulation_sip_only                    (0),
		.simulation_only                        (0),
		.bb_f_ehip_rx_fec_enable                ("RX_FEC_ENABLE_DISABLED"),
		.bb_f_ehip_tx_fec_enable                ("TX_FEC_ENABLE_DISABLED"),
		.bb_f_ehip_xcvr_mode                    ("XCVR_MODE_NRZ"),
		.bb_f_ehip_xcvr_type                    ("XCVR_TYPE_UX"),
		.tx_custom_cadence_enable               (1),
		.enable_port_tx_cadence_slow_clk_locked (1),
		.pldif_tx_fifo_mode                     ("phase_comp"),
		.pldif_tx_double_width_transfer_enable  (1),
		.pldif_rx_double_width_transfer_enable  (1)
	) alt_mge_xcvr_directphy (
		.i_rx_cdr_refclk_p              (xcvr_term_rx_cdr_refclk_out0_a10_clk),                                                                      //   input,   width = 1,              i_rx_cdr_refclk_p.clk
		.i_tx_pll_refclk_p              (tx_pll_refclk_p),                                                                                           //   input,   width = 1,              i_tx_pll_refclk_p.clk
		.i_pma_cu_clk                   (i_pma_cu_clk),                                                                                              //   input,   width = 1,                   i_pma_cu_clk.clk
		.i_system_pll_clk               (i_system_pll_clk),                                                                                          //   input,   width = 1,               i_system_pll_clk.clk
		.i_system_pll_lock              (i_system_pll_lock),                                                                                         //   input,   width = 1,              i_system_pll_lock.system_pll_lock
		.i_tx_reset                     (xcvr_term_o_tx_rst_tx_reset),                                                                               //   input,   width = 1,                     i_tx_reset.tx_reset
		.i_rx_reset                     (xcvr_term_o_rx_rst_rx_reset),                                                                               //   input,   width = 1,                     i_rx_reset.rx_reset
		.o_tx_reset_ack                 (alt_mge_xcvr_directphy_o_tx_reset_ack_tx_reset_ack),                                                        //  output,   width = 1,                 o_tx_reset_ack.tx_reset_ack
		.o_rx_reset_ack                 (alt_mge_xcvr_directphy_o_rx_reset_ack_rx_reset_ack),                                                        //  output,   width = 1,                 o_rx_reset_ack.rx_reset_ack
		.o_tx_ready                     (alt_mge_xcvr_directphy_o_tx_ready_tx_ready),                                                                //  output,   width = 1,                     o_tx_ready.tx_ready
		.o_rx_ready                     (alt_mge_xcvr_directphy_o_rx_ready_rx_ready),                                                                //  output,   width = 1,                     o_rx_ready.rx_ready
		.i_tx_coreclkin                 (xcvr_term_tx_coreclkin_out_xcvr_clk),                                                                       //   input,   width = 1,                 i_tx_coreclkin.clk
		.i_rx_coreclkin                 (xcvr_term_rx_coreclkin_out_xcvr_clk),                                                                       //   input,   width = 1,                 i_rx_coreclkin.clk
		.o_tx_clkout                    (alt_mge_xcvr_directphy_o_tx_clkout_clk),                                                                    //  output,   width = 1,                    o_tx_clkout.clk
		.o_tx_clkout2                   (alt_mge_xcvr_directphy_o_tx_clkout2_clk),                                                                   //  output,   width = 1,                   o_tx_clkout2.clk
		.o_rx_clkout                    (alt_mge_xcvr_directphy_o_rx_clkout_clk),                                                                    //  output,   width = 1,                    o_rx_clkout.clk
		.o_rx_clkout2                   (alt_mge_xcvr_directphy_o_rx_clkout2_clk),                                                                   //  output,   width = 1,                   o_rx_clkout2.clk
		.o_tx_cadence                   (),                                                                                                          //  output,   width = 1,                   o_tx_cadence.tx_cadence
		.i_tx_cadence_fast_clk          (alt_mge_xcvr_directphy_o_tx_clkout_clk),                                                                    //   input,   width = 1,          i_tx_cadence_fast_clk.clk
		.i_tx_cadence_slow_clk          (alt_mge_xcvr_directphy_o_tx_clkout2_clk),                                                                   //   input,   width = 1,          i_tx_cadence_slow_clk.clk
		.i_tx_cadence_slow_clk_locked   (),                                                                                                          //   input,   width = 1,   i_tx_cadence_slow_clk_locked.tx_cadence_slow_clk_locked
		.i_src_rs_grant                 (i_src_rs_grant),                                                                                            //   input,   width = 1,                 i_src_rs_grant.src_rs_grant
		.o_src_rs_req                   (o_src_rs_req),                                                                                              //  output,   width = 1,                   o_src_rs_req.src_rs_req
		.i_det_lat_rx_dl_clk            (xcvr_term_det_lat_rx_dl_clk_det_lat_rx_dl_clk),                                                             //   input,   width = 1,            i_det_lat_rx_dl_clk.det_lat_rx_dl_clk
		.i_det_lat_rx_mux_select        (xcvr_term_det_lat_rx_mux_select_det_lat_rx_mux_select),                                                     //   input,   width = 1,        i_det_lat_rx_mux_select.det_lat_rx_mux_select
		.i_det_lat_rx_sclk_flop         (xcvr_term_det_lat_rx_sclk_flop_det_lat_rx_sclk_flop),                                                       //   input,   width = 1,         i_det_lat_rx_sclk_flop.det_lat_rx_sclk_flop
		.i_det_lat_rx_sclk_gen_clk      (xcvr_term_det_lat_rx_sclk_gen_clk_det_lat_rx_sclk_gen_clk),                                                 //   input,   width = 1,      i_det_lat_rx_sclk_gen_clk.det_lat_rx_sclk_gen_clk
		.i_det_lat_rx_trig_flop         (xcvr_term_det_lat_rx_trig_flop_det_lat_rx_trig_flop),                                                       //   input,   width = 1,         i_det_lat_rx_trig_flop.det_lat_rx_trig_flop
		.i_det_lat_sampling_clk         (xcvr_term_det_lat_sampling_clk_det_lat_sampling_clk),                                                       //   input,   width = 1,         i_det_lat_sampling_clk.det_lat_sampling_clk
		.i_det_lat_tx_dl_clk            (xcvr_term_det_lat_tx_dl_clk_det_lat_tx_dl_clk),                                                             //   input,   width = 1,            i_det_lat_tx_dl_clk.det_lat_tx_dl_clk
		.i_det_lat_tx_mux_select        (xcvr_term_det_lat_tx_mux_select_det_lat_tx_mux_select),                                                     //   input,   width = 1,        i_det_lat_tx_mux_select.det_lat_tx_mux_select
		.i_det_lat_tx_sclk_flop         (xcvr_term_det_lat_tx_sclk_flop_det_lat_tx_sclk_flop),                                                       //   input,   width = 1,         i_det_lat_tx_sclk_flop.det_lat_tx_sclk_flop
		.i_det_lat_tx_sclk_gen_clk      (xcvr_term_det_lat_tx_sclk_gen_clk_det_lat_tx_sclk_gen_clk),                                                 //   input,   width = 1,      i_det_lat_tx_sclk_gen_clk.det_lat_tx_sclk_gen_clk
		.i_det_lat_tx_trig_flop         (xcvr_term_det_lat_tx_trig_flop_det_lat_tx_trig_flop),                                                       //   input,   width = 1,         i_det_lat_tx_trig_flop.det_lat_tx_trig_flop
		.o_det_lat_rx_async_dl_sync     (alt_mge_xcvr_directphy_o_det_lat_rx_async_dl_sync_det_lat_rx_async_dl_sync),                                //  output,   width = 1,     o_det_lat_rx_async_dl_sync.det_lat_rx_async_dl_sync
		.o_det_lat_rx_async_pulse       (alt_mge_xcvr_directphy_o_det_lat_rx_async_pulse_det_lat_rx_async_pulse),                                    //  output,   width = 1,       o_det_lat_rx_async_pulse.det_lat_rx_async_pulse
		.o_det_lat_rx_async_sample_sync (alt_mge_xcvr_directphy_o_det_lat_rx_async_sample_sync_det_lat_rx_async_sample_sync),                        //  output,   width = 1, o_det_lat_rx_async_sample_sync.det_lat_rx_async_sample_sync
		.o_det_lat_rx_sclk_sample_sync  (alt_mge_xcvr_directphy_o_det_lat_rx_sclk_sample_sync_det_lat_rx_sclk_sample_sync),                          //  output,   width = 1,  o_det_lat_rx_sclk_sample_sync.det_lat_rx_sclk_sample_sync
		.o_det_lat_rx_trig_sample_sync  (alt_mge_xcvr_directphy_o_det_lat_rx_trig_sample_sync_det_lat_rx_trig_sample_sync),                          //  output,   width = 1,  o_det_lat_rx_trig_sample_sync.det_lat_rx_trig_sample_sync
		.o_det_lat_tx_async_dl_sync     (alt_mge_xcvr_directphy_o_det_lat_tx_async_dl_sync_det_lat_tx_async_dl_sync),                                //  output,   width = 1,     o_det_lat_tx_async_dl_sync.det_lat_tx_async_dl_sync
		.o_det_lat_tx_async_pulse       (alt_mge_xcvr_directphy_o_det_lat_tx_async_pulse_det_lat_tx_async_pulse),                                    //  output,   width = 1,       o_det_lat_tx_async_pulse.det_lat_tx_async_pulse
		.o_det_lat_tx_async_sample_sync (alt_mge_xcvr_directphy_o_det_lat_tx_async_sample_sync_det_lat_tx_async_sample_sync),                        //  output,   width = 1, o_det_lat_tx_async_sample_sync.det_lat_tx_async_sample_sync
		.o_det_lat_tx_sclk_sample_sync  (alt_mge_xcvr_directphy_o_det_lat_tx_sclk_sample_sync_det_lat_tx_sclk_sample_sync),                          //  output,   width = 1,  o_det_lat_tx_sclk_sample_sync.det_lat_tx_sclk_sample_sync
		.o_det_lat_tx_trig_sample_sync  (alt_mge_xcvr_directphy_o_det_lat_tx_trig_sample_sync_det_lat_tx_trig_sample_sync),                          //  output,   width = 1,  o_det_lat_tx_trig_sample_sync.det_lat_tx_trig_sample_sync
		.o_xcvrif_rx_latency_pulse      (alt_mge_xcvr_directphy_o_xcvrif_rx_latency_pulse_xcvrif_rx_latency_pulse),                                  //  output,   width = 1,      o_xcvrif_rx_latency_pulse.xcvrif_rx_latency_pulse
		.o_xcvrif_tx_latency_pulse      (alt_mge_xcvr_directphy_o_xcvrif_tx_latency_pulse_xcvrif_tx_latency_pulse),                                  //  output,   width = 1,      o_xcvrif_tx_latency_pulse.xcvrif_tx_latency_pulse
		.o_tx_serial_data               (tx_serial_data),                                                                                            //  output,   width = 1,               o_tx_serial_data.o_tx_serial_data
		.o_tx_serial_data_n             (tx_serial_data_n),                                                                                          //  output,   width = 1,             o_tx_serial_data_n.o_tx_serial_data_n
		.i_rx_serial_data               (rx_serial_data),                                                                                            //   input,   width = 1,               i_rx_serial_data.i_rx_serial_data
		.i_rx_serial_data_n             (rx_serial_data_n),                                                                                          //   input,   width = 1,             i_rx_serial_data_n.i_rx_serial_data_n
		.o_tx_pll_locked                (),                                                                                                          //  output,   width = 1,                o_tx_pll_locked.o_tx_pll_locked
		.o_rx_is_lockedtodata           (rx_is_lockedtodata),                                                                                        //  output,   width = 1,           o_rx_is_lockedtodata.o_rx_is_lockedtodata
		.o_rx_is_lockedtoref            (),                                                                                                          //  output,   width = 1,            o_rx_is_lockedtoref.o_rx_is_lockedtoref
		.i_tx_parallel_data             (xcvr_term_tx_parallel_data_sm_i_tx_parallel_data),                                                          //   input,  width = 80,             i_tx_parallel_data.i_tx_parallel_data
		.o_rx_parallel_data             (alt_mge_xcvr_directphy_o_rx_parallel_data_o_rx_parallel_data),                                              //  output,  width = 80,             o_rx_parallel_data.o_rx_parallel_data
		.i_reconfig_clk                 (reconfig_clk),                                                                                              //   input,   width = 1,                 i_reconfig_clk.clk
		.i_reconfig_reset               (reconfig_reset),                                                                                            //   input,   width = 1,               i_reconfig_reset.reset
		.i_reconfig_write               (reconfig_write),                                                                                            //   input,   width = 1,                       reconfig.write
		.i_reconfig_read                (reconfig_read),                                                                                             //   input,   width = 1,                               .read
		.i_reconfig_address             (reconfig_address),                                                                                          //   input,  width = 18,                               .address
		.i_reconfig_byteenable          (reconfig_be),                                                                                               //   input,   width = 4,                               .byteenable
		.i_reconfig_writedata           (reconfig_writedata),                                                                                        //   input,  width = 32,                               .writedata
		.o_reconfig_readdata            (reconfig_readdata),                                                                                         //  output,  width = 32,                               .readdata
		.o_reconfig_waitrequest         (reconfig_waitrequest),                                                                                      //  output,   width = 1,                               .waitrequest
		.o_reconfig_readdatavalid       (reconfig_readdata_valid),                                                                                   //  output,   width = 1,                               .readdatavalid
		.o_rx_cdr_divclk                (),                                                                                                          // (terminated),                                             
		.o_tx_am_gen_start              (),                                                                                                          // (terminated),                                             
		.i_tx_am_gen_2x_ack             (1'b0),                                                                                                      // (terminated),                                             
		.i_uxquad_async                 (80'b00000000000000000000000000000000000000000000000000000000000000000000000000000000),                      // (terminated),                                             
		.i_uxquad_async_pcie_mux        (80'b00000000000000000000000000000000000000000000000000000000000000000000000000000000),                      // (terminated),                                             
		.o_uxquad_async                 (),                                                                                                          // (terminated),                                             
		.i_txdata_async                 (100'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000), // (terminated),                                             
		.i_txdata_direct                (10'b0000000000),                                                                                            // (terminated),                                             
		.o_rxdata_async                 (),                                                                                                          // (terminated),                                             
		.o_rxdata_direct                (),                                                                                                          // (terminated),                                             
		.i_rx_set_locktoref             (1'b0),                                                                                                      // (terminated),                                             
		.o_tx_fifo_full                 (),                                                                                                          // (terminated),                                             
		.o_tx_fifo_empty                (),                                                                                                          // (terminated),                                             
		.o_tx_fifo_pfull                (),                                                                                                          // (terminated),                                             
		.o_tx_fifo_pempty               (),                                                                                                          // (terminated),                                             
		.o_rx_fifo_full                 (),                                                                                                          // (terminated),                                             
		.o_rx_fifo_empty                (),                                                                                                          // (terminated),                                             
		.o_rx_fifo_pfull                (),                                                                                                          // (terminated),                                             
		.o_rx_fifo_pempty               (),                                                                                                          // (terminated),                                             
		.i_rx_fifo_rd_en                (1'b0),                                                                                                      // (terminated),                                             
		.o_rx_pmaif_fifo_empty          (),                                                                                                          // (terminated),                                             
		.o_rx_pmaif_fifo_pempty         (),                                                                                                          // (terminated),                                             
		.o_rx_pmaif_fifo_pfull          (),                                                                                                          // (terminated),                                             
		.o_tx_pmaif_fifo_empty          (),                                                                                                          // (terminated),                                             
		.o_tx_pmaif_fifo_pempty         (),                                                                                                          // (terminated),                                             
		.o_tx_pmaif_fifo_pfull          (),                                                                                                          // (terminated),                                             
		.o_fec_sf                       (),                                                                                                          // (terminated),                                             
		.o_fec_status_rx_not_align      (),                                                                                                          // (terminated),                                             
		.o_fec_status_rx_not_deskew     (),                                                                                                          // (terminated),                                             
		.o_fec_status_rx_not_locked     (),                                                                                                          // (terminated),                                             
		.i_fec_snapshot                 (1'b0),                                                                                                      // (terminated),                                             
		.o_rx_block_lock                (),                                                                                                          // (terminated),                                             
		.o_rx_am_lock                   (),                                                                                                          // (terminated),                                             
		.o_local_fault_status           (),                                                                                                          // (terminated),                                             
		.o_rx_hi_ber                    (),                                                                                                          // (terminated),                                             
		.o_rx_pcs_fully_aligned         (),                                                                                                          // (terminated),                                             
		.o_refclk2core                  (),                                                                                                          // (terminated),                                             
		.i_tx_pma_elecidle              (4'b0000)                                                                                                    // (terminated),                                             
	);

	alt_mge_phy_0_altera_iopll_1931_tktuxka iopll_tx (
		.refclk     (alt_mge_xcvr_directphy_o_tx_clkout2_clk), //   input,  width = 1,     refclk.clk
		.locked     (iopll_tx_locked_export),                  //  output,  width = 1,     locked.export
		.rst        (xcvr_term_tx_digitalreset_iopll_reset),   //   input,  width = 1,      reset.reset
		.permit_cal (xcvr_term_permit_cal_export),             //   input,  width = 1, permit_cal.export
		.outclk_0   (iopll_tx_outclk0_clk),                    //  output,  width = 1,    outclk0.clk
		.outclk_1   (iopll_tx_outclk1_clk),                    //  output,  width = 1,    outclk1.clk
		.outclk_2   (iopll_tx_outclk2_clk),                    //  output,  width = 1,    outclk2.clk
		.outclk_3   (iopll_tx_outclk3_clk)                     //  output,  width = 1,    outclk3.clk
	);

endmodule
