+uvm_set_action=*,uvm_link_transaction,UVM_ERROR,UVM_NO_ACTION

+define+UVM_NO_DEPRECATED
+define+UVM_OBJECT_MUST_HAVE_CONSTRUCTOR
+define+UVM_TR_RECORD
+define+UVM_VCS_RECORD
+define+ENABLE_ALTERA_AVALON_TRANSACTION_RECORDING
+define+UVM_REG_ADDR_WIDTH=20
+define+UVM_REG_DATA_WIDTH=32
+define+ALTUVM_ASSERT_ON
+define+SVT_ETHERNET_RETAIN_CFG_AFTER_RESET
+define+SVT_EXCLUDE_METHODOLOGY_PKG_INCLUDE
+define+SVT_ETHERNET_DISABLE_UVM_PKG_INCLUDE
+define+SVT_UVM_TECHNOLOGY
+define+UVM_DISABLE_AUTO_ITEM_RECORDING
+define+SVT_ETHERNET
+define+SYNOPSYS_SV
+define+VIP_ETHERNET_40G100G_OPT_SVT
+define+SVT_ETHERNET_DEBUG_BUS_ENABLE
+define+GMII_D_WIDTH=256
+define+GMII_C_WIDTH=32
+define+NUM_CH=4
+define+ETH_ENV_AVST_RX_RTB=eth_env_top.avst_rx_rtb.monitor.u_bfm
-f $ALTUVM_COMMON_HOME/scripts/generic/vcs/altuvm_common_pkg.f
-f $ALTUVM_BCL_HOME/scripts/generic/vcs/altuvm_pkg.f
-f $ALTUVM_AVALON_ST_HOME/scripts/generic/vcs/altuvm_avalon_st_pkg.f
-f $ALTUVM_AVALON_MM_HOME/scripts/generic/vcs/altuvm_avalon_mm_pkg.f

#+incdir+../../../../../../
#+incdir+../../../../
#+incdir+../../../
#+incdir+../../
#+incdir+../../gdr_gen_qhip_files
#+incdir+${REG_LOCAL_ROOT_DIR_PATH}/ip/ethernet/intel_mge_phy_scripts/qhip/scripts/common
+incdir+$TSN_HOME/testbench/include
+incdir+$TSN_HOME/testbench/define      
+incdir+$TSN_HOME/testbench/tb
+incdir+$TSN_HOME/testbench/tb/pcs66_model
+incdir+$TSN_HOME/testbench/tests
+incdir+$TSN_HOME/testbench/tests/top      
+incdir+$TSN_HOME/testbench/uvc
+incdir+$TSN_HOME/testbench/uvc/agent
+incdir+$TSN_HOME/testbench/uvc/agent/seg_tx
+incdir+$TSN_HOME/testbench/uvc/agent/seg_rx
+incdir+$TSN_HOME/testbench/uvc/agent/checker
+incdir+$TSN_HOME/testbench/uvc/agent/decoder_agent
+incdir+$TSN_HOME/testbench/uvc/agent/layering_agent
+incdir+$TSN_HOME/testbench/uvc/agent/fc_agent
+incdir+$TSN_HOME/testbench/uvc/agent/ptp_tx
+incdir+$TSN_HOME/testbench/uvc/agent/ehip_mii_agent
+incdir+$TSN_HOME/testbench/uvc/env
+incdir+$TSN_HOME/testbench/uvc/interface
+incdir+$TSN_HOME/testbench/uvc/seq_item
+incdir+$TSN_HOME/testbench/uvc/sequences
+incdir+$TSN_HOME/testbench/uvc/sequences/pcs_mac_seq_lib/
+incdir+$TSN_HOME/testbench/uvc/sequences/tsn_seq_lib/
+incdir+$TSN_HOME/testbench/uvc/sequences/pcs_seq_lib/
+incdir+$TSN_HOME/testbench/uvc/sequences/eth_ptp_seq_lib/
+incdir+$TSN_HOME/testbench/uvc/sequences/eth_rsfec_seq_lib/     
+incdir+$TSN_HOME/testbench/uvc/sequences/eth_malf_decoder_seq_lib/
+incdir+$TSN_HOME/testbench/uvc/sequences/eth_link_fault_seq/
+incdir+$TSN_HOME/testbench/uvc/sequences/eth_lt_seq_lib/
+incdir+$TSN_HOME/testbench/uvc/sequences/eth_an_seq_lib/
+incdir+$TSN_HOME/testbench/uvc/sequences/eth_stat_checkers_lib/
+incdir+$TSN_HOME/testbench/uvc/env/reset_uvc

#+incdir+/tools/synopsys_vip/vip_base_groups/M-2016.12-3-T0216/src/sverilog/vcs 
#+incdir+/tools/synopsys_vip/vip_base_groups/M-2016.12-3-T0216/src/verilog/vcs
#+incdir+/tools/synopsys_vip/vip_base_groups/M-2016.12-3-T0216/include/sverilog 
#+incdir+/tools/synopsys_vip/vip_base_groups/M-2016.12-3-T0216/include/verilog 
#/tools/synopsys_vip/vip_base_groups/M-2016.12-3-T0216/include/sverilog/svt_ethernet.uvm.pkg

$TSN_HOME/testbench/uvc/env/reset_uvc/reset_uvc_pkg.sv

+incdir+$ALTUVM_AVALON_ST_HOME/results/default/tb_defaults
+incdir+$UVM_HOME/src
+incdir+$ALTUVM_BCL_HOME/src
+incdir+$ALTUVM_AVALON_ST_HOME/testbench
+incdir+$ALTUVM_AVALON_ST_HOME/testbench/uvc
+incdir+$ALTUVM_AVALON_ST_HOME/testbench/uvc/sequences
+incdir+$ALTUVM_AVALON_ST_HOME/testbench/define
+incdir+$ALTUVM_AVALON_ST_HOME/testbench/tests
+incdir+$ALTUVM_AVALON_ST_HOME/testbench/../src
+incdir+$ALTUVM_AVALON_ST_HOME/testbench/../src/macros
+incdir+$ALTUVM_AVALON_ST_HOME/testbench/../src/bfm
+incdir+$ALTUVM_AVALON_MM_HOME/testbench
+incdir+$ALTUVM_AVALON_MM_HOME/testbench/uvc
+incdir+$ALTUVM_AVALON_MM_HOME/testbench/uvc/sequences
+incdir+$ALTUVM_AVALON_MM_HOME/testbench/define
+incdir+$ALTUVM_AVALON_MM_HOME/testbench/tests
+incdir+$ALTUVM_AVALON_MM_HOME/testbench/../src/bfm
+incdir+$TSN_HOME/testbench/tb
+incdir+$TSN_HOME/testbench/tb/rtb

#$TSN_HOME/testbench/tb/pcs66_model/pcs66_otn_modules.sv
#$TSN_HOME/testbench/tb/pcs66_model/flex_e_gaskets.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_async_fifo.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_lvlsync.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_bintogray.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_graytobin.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_dv_defines.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_sync2_set_ulvt_gate.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_sync_metastable_behav_gate.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_sync2_reset_ulvt_gate.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_sync2_reset_lvt_gate.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_sync2_set_lvt_gate.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_bitsync.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_ckmux4_lvt_gate.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_mux4_ctn.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_mux2_ctn.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_ckg_lvt_8x.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_ckg_posedge_ctn.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_sync2_lvt_bitsync.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_rstsync.sv
#$TSN_HOME/testbench/tb/pcs66_model/c2_c3lib_avmm_pulse_cross.sv
$TSN_HOME/testbench/uvc/agent/layering_agent/avst_pkg.sv
$TSN_HOME/testbench/uvc/agent/mm_pkg.sv
$TSN_HOME/testbench/uvc/agent/vector_uvc_pkg.sv
$TSN_HOME/testbench/uvc/agent/seg_tx_pkg.sv
$TSN_HOME/testbench/uvc/agent/seg_rx_pkg.sv
#$TSN_HOME/testbench/uvc/agent/ehip_mii_agent/ehip_mii_tx_pkg.sv
${REG_LOCAL_ROOT_DIR_PATH}/scripts/common/params_avmm.sv
$TSN_HOME/testbench/uvc/env/eth_env_pkg.sv
$TSN_HOME/testbench/uvc/agent/ptp_tx/ptp_tx_rtb_module.sv
$TSN_HOME/testbench/uvc/agent/seg_tx/seg_tx_rtb_module.sv
$TSN_HOME/testbench/uvc/agent/seg_rx/seg_rx_rtb_module.sv
#/tools/acdstest-rtl/${ACDS_VERSION}/${ACDS_BUILD_NUMBER}/linux64/quartus/eda/sim_lib/synopsys/cr3v0_encrypted_ncrypt.sv
# Temp includes
#../../gdr_gen_qhip_files/dut_top.v
#../../gdr_gen_qhip_files/eth_ehip_gdr_top.sv
#../../gdr_gen_qhip_files/gdr_tb_defines.v
$TSN_HOME/testbench/uvc/tsn_pkg.sv
$TSN_HOME/testbench/tb/rtb/hps_rtb.sv      
$TSN_HOME/testbench/tb/rtb/tsn_rtb.sv      
$TSN_HOME/testbench/tb/top_tb.sv
