# ITF GENERATED FILE 
#   to update please modify project.ini 
 

# Enabling advanced devices
asm_enable_advanced_devices=on

# Enabling backwards compatible
qatm_force_import=on
qatm_force_export=on
qatm_disable_compression=on
