// gavmm_f_0.v

// Generated using ACDS version 20.3 97

`timescale 1 ps / 1 ps
module gavmm_f_0 #(
		parameter avmm_data_width      = 32,
		parameter avmm_addr_width      = 18,
		parameter read_pipeline_enable = 1,
		parameter avmm_jtag_enable     = 0,
		parameter bb_placeholder       = "fm6",
		parameter silicon_revision     = "10nm6agdra",
		parameter device_revision      = "10nm6agdra"
	) (
		input  wire                       g_avmm_clk,           //    clock.clk
		input  wire                       g_avmm_reset,         //    reset.reset
		input  wire                       g_avmm_write,         // glb_avmm.write
		input  wire                       g_avmm_read,          //         .read
		input  wire [11:0]                g_avmm_address,       //         .address
		input  wire [3:0]                 g_avmm_byteenable,    //         .byteenable
		input  wire [31:0]                g_avmm_writedata,     //         .writedata
		output wire [31:0]                g_avmm_readdata,      //         .readdata
		output wire                       g_avmm_waitrequest,   //         .waitrequest
		output wire                       g_avmm_readdatavalid  //         .readdatavalid
	);

/*	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (avmm_data_width != 32)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					avmm_data_width_check ( .error(1'b1) );
		end
		if (avmm_addr_width != 18)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					avmm_addr_width_check ( .error(1'b1) );
		end
		if (read_pipeline_enable != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					read_pipeline_enable_check ( .error(1'b1) );
		end
		if (avmm_jtag_enable != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					avmm_jtag_enable_check ( .error(1'b1) );
		end
		if (bb_placeholder != "fm6")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					bb_placeholder_check ( .error(1'b1) );
		end
		if (silicon_revision != "10nm6agdra")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					silicon_revision_check ( .error(1'b1) );
		end
		if (device_revision != "10nm6agdra")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					device_revision_check ( .error(1'b1) );
		end
	endgenerate

	ex_25G_gavmm_f_100_ndjtzvq #(
		.avmm_data_width      (32),
		.avmm_addr_width      (18),
		.read_pipeline_enable (1),
		.avmm_jtag_enable     (0),
		.bb_placeholder       ("fm6"),
		.silicon_revision     ("10nm6agdra"),
		.device_revision      ("10nm6agdra")
	) gavmm_f_0 (
		.g_avmm_clk           (g_avmm_clk),           //   input,   width = 1,    clock.clk
		.g_avmm_reset         (g_avmm_reset),         //   input,   width = 1,    reset.reset
		.g_avmm_write         (g_avmm_write),         //   input,   width = 1, glb_avmm.write
		.g_avmm_read          (g_avmm_read),          //   input,   width = 1,         .read
		.g_avmm_address       (g_avmm_address),       //   input,  width = 18,         .address
		.g_avmm_byteenable    (g_avmm_byteenable),    //   input,   width = 4,         .byteenable
		.g_avmm_writedata     (g_avmm_writedata),     //   input,  width = 32,         .writedata
		.g_avmm_readdata      (g_avmm_readdata),      //  output,  width = 32,         .readdata
		.g_avmm_waitrequest   (g_avmm_waitrequest),   //  output,   width = 1,         .waitrequest
		.g_avmm_readdatavalid (g_avmm_readdatavalid)  //  output,   width = 1,         .readdatavalid
	);
*/
endmodule
