// systemclk_f_0.v

// Generated using ACDS version 20.3 97

`timescale 1 ps / 1 ps
module systemclk_f_0 #(
		parameter enables_systempll             = 1,
		parameter systempll_refsrc_0            = 0,
		parameter systempll_refsrc_1            = 0,
		parameter systempll_refsrc_2            = 0,
		parameter enables_refclk_fgt            = 1,
		parameter enables_refclk_fht            = 1,
		parameter systempll_c0_counter_0        = "8",
		parameter systempll_c1_counter_0        = "16",
		parameter systempll_c2_counter_0        = "0",
		parameter systempll_c0_output_enable_0  = "C0_OUTPUT_ENABLE",
		parameter systempll_c1_output_enable_0  = "C1_OUTPUT_ENABLE",
		parameter systempll_c2_output_enable_0  = "C2_OUTPUT_DISABLE",
		parameter systempll_f_out_c0_hz_0       = "805664062",
		parameter systempll_f_out_c1_hz_0       = "402832031",
		parameter systempll_f_out_c2_hz_0       = "0",
		parameter systempll_f_pfd_hz_0          = "39062500",
		parameter systempll_f_ref_hz_0          = "156250000",
		parameter systempll_f_vco_hz_0          = "",
		parameter systempll_fractional_enable_0 = "DISABLED",
		parameter systempll_m_counter_0         = "165",
		parameter systempll_n_counter_0         = "4",
		parameter systempll_ethernet_preset_0   = "ETHERNET_FREQ_OTHER",
		parameter systempll_pcie_preset_0       = "PCIE_UNUSED",
		parameter systempll_c0_counter_1        = "",
		parameter systempll_c1_counter_1        = "",
		parameter systempll_c2_counter_1        = "",
		parameter systempll_c0_output_enable_1  = "",
		parameter systempll_c1_output_enable_1  = "",
		parameter systempll_c2_output_enable_1  = "",
		parameter systempll_f_out_c0_hz_1       = "",
		parameter systempll_f_out_c1_hz_1       = "",
		parameter systempll_f_out_c2_hz_1       = "",
		parameter systempll_f_pfd_hz_1          = "",
		parameter systempll_f_ref_hz_1          = "",
		parameter systempll_f_vco_hz_1          = "",
		parameter systempll_fractional_enable_1 = "",
		parameter systempll_m_counter_1         = "",
		parameter systempll_n_counter_1         = "",
		parameter systempll_ethernet_preset_1   = "",
		parameter systempll_pcie_preset_1       = "",
		parameter systempll_c0_counter_2        = "",
		parameter systempll_c1_counter_2        = "",
		parameter systempll_c2_counter_2        = "",
		parameter systempll_c0_output_enable_2  = "",
		parameter systempll_c1_output_enable_2  = "",
		parameter systempll_c2_output_enable_2  = "",
		parameter systempll_f_out_c0_hz_2       = "",
		parameter systempll_f_out_c1_hz_2       = "",
		parameter systempll_f_out_c2_hz_2       = "",
		parameter systempll_f_pfd_hz_2          = "",
		parameter systempll_f_ref_hz_2          = "",
		parameter systempll_f_vco_hz_2          = "",
		parameter systempll_fractional_enable_2 = "",
		parameter systempll_m_counter_2         = "",
		parameter systempll_n_counter_2         = "",
		parameter systempll_ethernet_preset_2   = "",
		parameter systempll_pcie_preset_2       = "",
		parameter cmnpll_m_counter              = "",
		parameter cmnpll_fraction_div           = "",
		parameter cmnpll_en_cmos_refclk_out     = "",
		parameter silicon_revision              = "10nm6agdra",
		parameter device_revision               = "10nm6agdra"
	) (
		output wire  out_systempll_clk_0,  //  out_systempll_clk_0.clk
		output wire  out_refclk_fgt_0,     //     out_refclk_fgt_0.clk
		input  wire  in_refclk_fgt_0,      //           refclk_fgt.in_refclk_fgt_0
		input  wire  in_refclk_fht_0,      //           refclk_fht.in_refclk_fht_0
		output wire  out_fht_cmmpll_clk_0  // out_fht_cmmpll_clk_0.clk
	);

/*	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (enables_systempll != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					enables_systempll_check ( .error(1'b1) );
		end
		if (systempll_refsrc_0 != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_refsrc_0_check ( .error(1'b1) );
		end
		if (systempll_refsrc_1 != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_refsrc_1_check ( .error(1'b1) );
		end
		if (systempll_refsrc_2 != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_refsrc_2_check ( .error(1'b1) );
		end
		if (enables_refclk_fgt != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					enables_refclk_fgt_check ( .error(1'b1) );
		end
		if (enables_refclk_fht != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					enables_refclk_fht_check ( .error(1'b1) );
		end
		if (systempll_c0_counter_0 != "8")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_c0_counter_0_check ( .error(1'b1) );
		end
		if (systempll_c1_counter_0 != "16")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_c1_counter_0_check ( .error(1'b1) );
		end
		if (systempll_c2_counter_0 != "0")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_c2_counter_0_check ( .error(1'b1) );
		end
		if (systempll_c0_output_enable_0 != "C0_OUTPUT_ENABLE")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_c0_output_enable_0_check ( .error(1'b1) );
		end
		if (systempll_c1_output_enable_0 != "C1_OUTPUT_ENABLE")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_c1_output_enable_0_check ( .error(1'b1) );
		end
		if (systempll_c2_output_enable_0 != "C2_OUTPUT_DISABLE")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_c2_output_enable_0_check ( .error(1'b1) );
		end
		if (systempll_f_out_c0_hz_0 != "805664062")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_f_out_c0_hz_0_check ( .error(1'b1) );
		end
		if (systempll_f_out_c1_hz_0 != "402832031")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_f_out_c1_hz_0_check ( .error(1'b1) );
		end
		if (systempll_f_out_c2_hz_0 != "0")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_f_out_c2_hz_0_check ( .error(1'b1) );
		end
		if (systempll_f_pfd_hz_0 != "39062500")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_f_pfd_hz_0_check ( .error(1'b1) );
		end
		if (systempll_f_ref_hz_0 != "156250000")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_f_ref_hz_0_check ( .error(1'b1) );
		end
		if (systempll_f_vco_hz_0 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_f_vco_hz_0_check ( .error(1'b1) );
		end
		if (systempll_fractional_enable_0 != "DISABLED")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_fractional_enable_0_check ( .error(1'b1) );
		end
		if (systempll_m_counter_0 != "165")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_m_counter_0_check ( .error(1'b1) );
		end
		if (systempll_n_counter_0 != "4")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_n_counter_0_check ( .error(1'b1) );
		end
		if (systempll_ethernet_preset_0 != "ETHERNET_FREQ_OTHER")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_ethernet_preset_0_check ( .error(1'b1) );
		end
		if (systempll_pcie_preset_0 != "PCIE_UNUSED")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_pcie_preset_0_check ( .error(1'b1) );
		end
		if (systempll_c0_counter_1 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_c0_counter_1_check ( .error(1'b1) );
		end
		if (systempll_c1_counter_1 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_c1_counter_1_check ( .error(1'b1) );
		end
		if (systempll_c2_counter_1 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_c2_counter_1_check ( .error(1'b1) );
		end
		if (systempll_c0_output_enable_1 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_c0_output_enable_1_check ( .error(1'b1) );
		end
		if (systempll_c1_output_enable_1 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_c1_output_enable_1_check ( .error(1'b1) );
		end
		if (systempll_c2_output_enable_1 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_c2_output_enable_1_check ( .error(1'b1) );
		end
		if (systempll_f_out_c0_hz_1 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_f_out_c0_hz_1_check ( .error(1'b1) );
		end
		if (systempll_f_out_c1_hz_1 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_f_out_c1_hz_1_check ( .error(1'b1) );
		end
		if (systempll_f_out_c2_hz_1 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_f_out_c2_hz_1_check ( .error(1'b1) );
		end
		if (systempll_f_pfd_hz_1 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_f_pfd_hz_1_check ( .error(1'b1) );
		end
		if (systempll_f_ref_hz_1 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_f_ref_hz_1_check ( .error(1'b1) );
		end
		if (systempll_f_vco_hz_1 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_f_vco_hz_1_check ( .error(1'b1) );
		end
		if (systempll_fractional_enable_1 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_fractional_enable_1_check ( .error(1'b1) );
		end
		if (systempll_m_counter_1 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_m_counter_1_check ( .error(1'b1) );
		end
		if (systempll_n_counter_1 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_n_counter_1_check ( .error(1'b1) );
		end
		if (systempll_ethernet_preset_1 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_ethernet_preset_1_check ( .error(1'b1) );
		end
		if (systempll_pcie_preset_1 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_pcie_preset_1_check ( .error(1'b1) );
		end
		if (systempll_c0_counter_2 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_c0_counter_2_check ( .error(1'b1) );
		end
		if (systempll_c1_counter_2 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_c1_counter_2_check ( .error(1'b1) );
		end
		if (systempll_c2_counter_2 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_c2_counter_2_check ( .error(1'b1) );
		end
		if (systempll_c0_output_enable_2 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_c0_output_enable_2_check ( .error(1'b1) );
		end
		if (systempll_c1_output_enable_2 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_c1_output_enable_2_check ( .error(1'b1) );
		end
		if (systempll_c2_output_enable_2 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_c2_output_enable_2_check ( .error(1'b1) );
		end
		if (systempll_f_out_c0_hz_2 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_f_out_c0_hz_2_check ( .error(1'b1) );
		end
		if (systempll_f_out_c1_hz_2 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_f_out_c1_hz_2_check ( .error(1'b1) );
		end
		if (systempll_f_out_c2_hz_2 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_f_out_c2_hz_2_check ( .error(1'b1) );
		end
		if (systempll_f_pfd_hz_2 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_f_pfd_hz_2_check ( .error(1'b1) );
		end
		if (systempll_f_ref_hz_2 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_f_ref_hz_2_check ( .error(1'b1) );
		end
		if (systempll_f_vco_hz_2 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_f_vco_hz_2_check ( .error(1'b1) );
		end
		if (systempll_fractional_enable_2 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_fractional_enable_2_check ( .error(1'b1) );
		end
		if (systempll_m_counter_2 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_m_counter_2_check ( .error(1'b1) );
		end
		if (systempll_n_counter_2 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_n_counter_2_check ( .error(1'b1) );
		end
		if (systempll_ethernet_preset_2 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_ethernet_preset_2_check ( .error(1'b1) );
		end
		if (systempll_pcie_preset_2 != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					systempll_pcie_preset_2_check ( .error(1'b1) );
		end
		if (cmnpll_m_counter != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					cmnpll_m_counter_check ( .error(1'b1) );
		end
		if (cmnpll_fraction_div != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					cmnpll_fraction_div_check ( .error(1'b1) );
		end
		if (cmnpll_en_cmos_refclk_out != "")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					cmnpll_en_cmos_refclk_out_check ( .error(1'b1) );
		end
		if (silicon_revision != "10nm6agdra")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					silicon_revision_check ( .error(1'b1) );
		end
		if (device_revision != "10nm6agdra")
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					device_revision_check ( .error(1'b1) );
		end
	endgenerate

	ex_25G_systemclk_f_100_fmzzgsq #(
		.enables_systempll             (1),
		.systempll_refsrc_0            (0),
		.systempll_refsrc_1            (0),
		.systempll_refsrc_2            (0),
		.enables_refclk_fgt            (1),
		.enables_refclk_fht            (1),
		.systempll_c0_counter_0        ("8"),
		.systempll_c1_counter_0        ("16"),
		.systempll_c2_counter_0        ("0"),
		.systempll_c0_output_enable_0  ("C0_OUTPUT_ENABLE"),
		.systempll_c1_output_enable_0  ("C1_OUTPUT_ENABLE"),
		.systempll_c2_output_enable_0  ("C2_OUTPUT_DISABLE"),
		.systempll_f_out_c0_hz_0       ("805664062"),
		.systempll_f_out_c1_hz_0       ("402832031"),
		.systempll_f_out_c2_hz_0       ("0"),
		.systempll_f_pfd_hz_0          ("39062500"),
		.systempll_f_ref_hz_0          ("156250000"),
		.systempll_f_vco_hz_0          (""),
		.systempll_fractional_enable_0 ("DISABLED"),
		.systempll_m_counter_0         ("165"),
		.systempll_n_counter_0         ("4"),
		.systempll_ethernet_preset_0   ("ETHERNET_FREQ_OTHER"),
		.systempll_pcie_preset_0       ("PCIE_UNUSED"),
		.systempll_c0_counter_1        (""),
		.systempll_c1_counter_1        (""),
		.systempll_c2_counter_1        (""),
		.systempll_c0_output_enable_1  (""),
		.systempll_c1_output_enable_1  (""),
		.systempll_c2_output_enable_1  (""),
		.systempll_f_out_c0_hz_1       (""),
		.systempll_f_out_c1_hz_1       (""),
		.systempll_f_out_c2_hz_1       (""),
		.systempll_f_pfd_hz_1          (""),
		.systempll_f_ref_hz_1          (""),
		.systempll_f_vco_hz_1          (""),
		.systempll_fractional_enable_1 (""),
		.systempll_m_counter_1         (""),
		.systempll_n_counter_1         (""),
		.systempll_ethernet_preset_1   (""),
		.systempll_pcie_preset_1       (""),
		.systempll_c0_counter_2        (""),
		.systempll_c1_counter_2        (""),
		.systempll_c2_counter_2        (""),
		.systempll_c0_output_enable_2  (""),
		.systempll_c1_output_enable_2  (""),
		.systempll_c2_output_enable_2  (""),
		.systempll_f_out_c0_hz_2       (""),
		.systempll_f_out_c1_hz_2       (""),
		.systempll_f_out_c2_hz_2       (""),
		.systempll_f_pfd_hz_2          (""),
		.systempll_f_ref_hz_2          (""),
		.systempll_f_vco_hz_2          (""),
		.systempll_fractional_enable_2 (""),
		.systempll_m_counter_2         (""),
		.systempll_n_counter_2         (""),
		.systempll_ethernet_preset_2   (""),
		.systempll_pcie_preset_2       (""),
		.cmnpll_m_counter              (""),
		.cmnpll_fraction_div           (""),
		.cmnpll_en_cmos_refclk_out     (""),
		.silicon_revision              ("10nm6agdra"),
		.device_revision               ("10nm6agdra")
	) systemclk_f_0 (
		.out_systempll_clk_0  (out_systempll_clk_0),  //  output,  width = 1,  out_systempll_clk_0.clk
		.out_refclk_fgt_0     (out_refclk_fgt_0),     //  output,  width = 1,     out_refclk_fgt_0.clk
		.in_refclk_fgt_0      (in_refclk_fgt_0),      //   input,  width = 1,           refclk_fgt.in_refclk_fgt_0
		.in_refclk_fht_0      (in_refclk_fht_0),      //   input,  width = 1,           refclk_fht.in_refclk_fht_0
		.out_fht_cmmpll_clk_0 (out_fht_cmmpll_clk_0), //  output,  width = 1, out_fht_cmmpll_clk_0.clk
		.out_systempll_clk_1  (),                     // (terminated),                                  
		.out_systempll_clk_2  (),                     // (terminated),                                  
		.out_refclk_fgt_1     (),                     // (terminated),                                  
		.out_refclk_fgt_2     (),                     // (terminated),                                  
		.out_refclk_fgt_3     (),                     // (terminated),                                  
		.out_refclk_fgt_4     (),                     // (terminated),                                  
		.out_refclk_fgt_5     (),                     // (terminated),                                  
		.out_refclk_fgt_6     (),                     // (terminated),                                  
		.out_refclk_fgt_7     (),                     // (terminated),                                  
		.out_refclk_fgt_8     (),                     // (terminated),                                  
		.out_refclk_fgt_9     (),                     // (terminated),                                  
		.in_refclk_fgt_1      (1'b0),                 // (terminated),                                  
		.in_refclk_fgt_2      (1'b0),                 // (terminated),                                  
		.in_refclk_fgt_3      (1'b0),                 // (terminated),                                  
		.in_refclk_fgt_4      (1'b0),                 // (terminated),                                  
		.in_refclk_fgt_5      (1'b0),                 // (terminated),                                  
		.in_refclk_fgt_6      (1'b0),                 // (terminated),                                  
		.in_refclk_fgt_7      (1'b0),                 // (terminated),                                  
		.in_refclk_fgt_8      (1'b0),                 // (terminated),                                  
		.in_refclk_fgt_9      (1'b0),                 // (terminated),                                  
		.in_refclk_fht_1      (1'b0),                 // (terminated),                                  
		.out_fht_cmmpll_clk_1 (),                     // (terminated),                                  
		.in_cdrclk_0          (1'b0),                 // (terminated),                                  
		.in_cdrclk_1          (1'b0),                 // (terminated),                                  
		.out_cdrclk_0         (),                     // (terminated),                                  
		.out_cdrclk_1         ()                      // (terminated),                                  
	);
*/
endmodule
