// hps_axi_bridge.v

// Generated using ACDS version 23.4 40

`timescale 1 ps / 1 ps
module hps_axi_bridge (
		input  wire        clk_clk,                                          //                                      clk.clk
		output wire        intel_agilex_5_soc_0_h2f_reset_reset_n,           //           intel_agilex_5_soc_0_h2f_reset.reset_n
		input  wire        intel_agilex_5_soc_0_emac_ptp_clk_clk,            //        intel_agilex_5_soc_0_emac_ptp_clk.clk
		input  wire        intel_agilex_5_soc_0_emac_timestamp_clk_clk,      //  intel_agilex_5_soc_0_emac_timestamp_clk.clk
		input  wire [63:0] intel_agilex_5_soc_0_emac_timestamp_data_data_in, // intel_agilex_5_soc_0_emac_timestamp_data.data_in
		output wire        intel_agilex_5_soc_0_emac0_mdio_mac_mdc,          //          intel_agilex_5_soc_0_emac0_mdio.mac_mdc
		input  wire        intel_agilex_5_soc_0_emac0_mdio_mac_mdi,          //                                         .mac_mdi
		output wire        intel_agilex_5_soc_0_emac0_mdio_mac_mdo,          //                                         .mac_mdo
		output wire        intel_agilex_5_soc_0_emac0_mdio_mac_mdoe,         //                                         .mac_mdoe
		output wire        intel_agilex_5_soc_0_emac0_app_rst_reset_n,       //       intel_agilex_5_soc_0_emac0_app_rst.reset_n
		output wire        intel_agilex_5_soc_0_emac0_mac_tx_clk_o,          //               intel_agilex_5_soc_0_emac0.mac_tx_clk_o
		input  wire        intel_agilex_5_soc_0_emac0_mac_rx_clk,            //                                         .mac_rx_clk
		output wire        intel_agilex_5_soc_0_emac0_mac_rst_tx_n,          //                                         .mac_rst_tx_n
		output wire        intel_agilex_5_soc_0_emac0_mac_rst_rx_n,          //                                         .mac_rst_rx_n
		output wire        intel_agilex_5_soc_0_emac0_mac_txen,              //                                         .mac_txen
		output wire        intel_agilex_5_soc_0_emac0_mac_txer,              //                                         .mac_txer
		input  wire        intel_agilex_5_soc_0_emac0_mac_rxdv,              //                                         .mac_rxdv
		input  wire        intel_agilex_5_soc_0_emac0_mac_rxer,              //                                         .mac_rxer
		input  wire [7:0]  intel_agilex_5_soc_0_emac0_mac_rxd,               //                                         .mac_rxd
		input  wire        intel_agilex_5_soc_0_emac0_mac_col,               //                                         .mac_col
		input  wire        intel_agilex_5_soc_0_emac0_mac_crs,               //                                         .mac_crs
		output wire [2:0]  intel_agilex_5_soc_0_emac0_mac_speed,             //                                         .mac_speed
		output wire [7:0]  intel_agilex_5_soc_0_emac0_mac_txd_o,             //                                         .mac_txd_o
		input  wire [63:0] intel_agilex_5_soc_0_fpga2hps_interrupt_irq,      //  intel_agilex_5_soc_0_fpga2hps_interrupt.irq
		input  wire        mm_bridge_0_m0_waitrequest,                       //                           mm_bridge_0_m0.waitrequest
		input  wire [31:0] mm_bridge_0_m0_readdata,                          //                                         .readdata
		input  wire        mm_bridge_0_m0_readdatavalid,                     //                                         .readdatavalid
		output wire [0:0]  mm_bridge_0_m0_burstcount,                        //                                         .burstcount
		output wire [31:0] mm_bridge_0_m0_writedata,                         //                                         .writedata
		output wire [9:0]  mm_bridge_0_m0_address,                           //                                         .address
		output wire        mm_bridge_0_m0_write,                             //                                         .write
		output wire        mm_bridge_0_m0_read,                              //                                         .read
		output wire [3:0]  mm_bridge_0_m0_byteenable,                        //                                         .byteenable
		output wire        mm_bridge_0_m0_debugaccess,                       //                                         .debugaccess
		input  wire        reset_reset                                       //                                    reset.reset
	);
   /*
   initial begin
      assign intel_agilex_5_soc_0_h2f_reset_reset_n = 'h0;
      assign intel_agilex_5_soc_0_emac0_mdio_mac_mdc = 'h0;
      assign intel_agilex_5_soc_0_emac0_mdio_mac_mdo = 'h0;
      assign intel_agilex_5_soc_0_emac0_mdio_mac_mdoe = 'h0;
      assign intel_agilex_5_soc_0_emac0_app_rst_reset_n = 'h0;
      assign intel_agilex_5_soc_0_emac0_mac_tx_clk_o = 'h0;
      assign mm_bridge_0_m0_burstcount = 'h0;
      assign mm_bridge_0_m0_writedata = 'h0;
      assign mm_bridge_0_m0_address = 'h0;
      assign mm_bridge_0_m0_write = 'h0;
      assign mm_bridge_0_m0_read = 'h0;
      assign mm_bridge_0_m0_byteenable = 'h0;
      assign mm_bridge_0_m0_debugaccess = 'h0;
      assign intel_agilex_5_soc_0_emac0_mac_speed = 'h0;
      assign intel_agilex_5_soc_0_emac0_mac_txd_o = 'h0;
      assign intel_agilex_5_soc_0_emac0_mac_txen = 'h0;
      assign intel_agilex_5_soc_0_emac0_mac_txer = 'h0;
      assign intel_agilex_5_soc_0_emac0_mac_rst_tx_n = 'h0;
      assign intel_agilex_5_soc_0_emac0_mac_rst_rx_n = 'h0;
   end
   */
endmodule
