// alt_mge_phy_0.v

// Generated using ACDS version 23.4.1 162

`timescale 1 ps / 1 ps
module alt_mge_phy_0 (
		input  wire        csr_clk,                 //                csr_clk.clk
		input  wire        gmii8b_tx_clkin,         //        gmii8b_tx_clkin.clk
		output wire        tx_clkout,               //              tx_clkout.clk
		output wire        rx_clkout,               //              rx_clkout.clk
		input  wire        gmii8b_tx_rst_n,         //        gmii8b_tx_rst_n.gmii8b_tx_rst_n
		input  wire        gmii8b_rx_rst_n,         //        gmii8b_rx_rst_n.gmii8b_rx_rst_n
		output wire        gmii8b_rx_clkout,        //       gmii8b_rx_clkout.clk
		output wire        gmii8b_tx_clkout,        //       gmii8b_tx_clkout.clk
		input  wire        reset,                   //                  reset.reset
		input  wire        rx_digitalreset,         //        rx_digitalreset.rx_digitalreset
		input  wire        tx_digitalreset,         //        tx_digitalreset.tx_digitalreset
		output wire [15:0] csr_readdata,            //          avalon_mm_csr.readdata
		input  wire [15:0] csr_writedata,           //                       .writedata
		input  wire [4:0]  csr_address,             //                       .address
		output wire        csr_waitrequest,         //                       .waitrequest
		input  wire        csr_read,                //                       .read
		input  wire        csr_write,               //                       .write
		input  wire        gmii8b_mac_txen,         //        gmii8b_mac_txen.export
		input  wire [7:0]  gmii8b_mac_tx_d,         //        gmii8b_mac_tx_d.export
		input  wire        gmii8b_mac_txer,         //        gmii8b_mac_txer.export
		output wire        gmii8b_mac_rxdv,         //        gmii8b_mac_rxdv.export
		output wire [7:0]  gmii8b_mac_rxd,          //         gmii8b_mac_rxd.export
		output wire        gmii8b_mac_rxer,         //        gmii8b_mac_rxer.export
		input  wire [1:0]  gmii8b_mac_speed,        //       gmii8b_mac_speed.export
		output wire        led_link,                //               led_link.export
		output wire        led_char_err,            //           led_char_err.export
		output wire        led_disp_err,            //           led_disp_err.export
		output wire        led_an,                  //                 led_an.export
		output wire [2:0]  operating_speed,         //        operating_speed.export
		output wire        mrphy_pll_lock,          //         mrphy_pll_lock.pll_locked_stable
		input  wire        i_src_ch_pause_request,  // i_src_ch_pause_request.o_src_ch_pause_request
		output wire        o_src_ch_pause_grant,    //   o_src_ch_pause_grant.i_src_ch_pause_grant
		input  wire        i_rst_n,                 //                i_rst_n.i_rst_n
		output wire        o_rst_ack_n,             //            o_rst_ack_n.o_rst_ack_n
		input  wire        i_tx_rst_n,              //             i_tx_rst_n.i_tx_rst_n
		input  wire        i_rx_rst_n,              //             i_rx_rst_n.i_rx_rst_n
		output wire        o_tx_rst_ack_n,          //         o_tx_rst_ack_n.o_tx_rst_ack_n
		output wire        o_rx_rst_ack_n,          //         o_rx_rst_ack_n.o_rx_rst_ack_n
		input  wire        rx_cdr_refclk_p,         //        rx_cdr_refclk_p.clk
		output wire        tx_ready,                //               tx_ready.tx_ready
		output wire        rx_ready,                //               rx_ready.rx_ready
		output wire        rx_pma_clkout,           //          rx_pma_clkout.clk
		input  wire [1:0]  xcvr_mode,               //              xcvr_mode.export
		input  wire [0:0]  tx_pll_refclk_p,         //        tx_pll_refclk_p.clk,                   The connection made from "Reference and SystemPLL Clocks IP" to this pin will guide Quartus on properly setting clock network.
		input  wire [0:0]  i_pma_cu_clk,            //           i_pma_cu_clk.clk,                   The connection made from "Reference and SystemPLL Clocks IP" to this pin will guide Quartus on properly setting clock network.
		input  wire [0:0]  i_system_pll_clk,        //       i_system_pll_clk.clk,                   The connection made from "Reference and SystemPLL Clocks IP" to this pin will guide Quartus on properly setting clock network.
		input  wire [0:0]  i_system_pll_lock,       //      i_system_pll_lock.system_pll_lock,       The connection made from "Reference and SystemPLL Clocks IP" to this pin will guide Quartus on properly setting clock network.
		input  wire [0:0]  i_src_rs_grant,          //         i_src_rs_grant.src_rs_grant,          Grant Signal
		output wire [0:0]  o_src_rs_req,            //           o_src_rs_req.src_rs_req,            Request Signal
		output wire [0:0]  tx_serial_data,          //         tx_serial_data.o_tx_serial_data,      TX serial data port.
		output wire [0:0]  tx_serial_data_n,        //       tx_serial_data_n.o_tx_serial_data_n,    Differential pair for TX serial data port. Historically was hidden; however now used in pam4 signal simulation model, hence needs to be connected by user.
		input  wire [0:0]  rx_serial_data,          //         rx_serial_data.i_rx_serial_data,      RX serial data port.
		input  wire [0:0]  rx_serial_data_n,        //       rx_serial_data_n.i_rx_serial_data_n,    Differential pair for RX serial data port. Historically was hidden; however now used in pam4 signal simulation model, hence needs to be connected by user.
		output wire [0:0]  rx_is_lockedtodata,      //     rx_is_lockedtodata.o_rx_is_lockedtodata,  RX CDR data lock status signal. 1`b0: CDR is not locked to data. 1`b1: CDR is locked to data.
		input  wire [0:0]  reconfig_clk,            //           reconfig_clk.clk,                   Reconfiguration interface clock.
		input  wire [0:0]  reconfig_reset,          //         reconfig_reset.reset,                 Reconfiguration reset.
		input  wire [0:0]  reconfig_write,          //               reconfig.write,                 Reconfiguration write.
		input  wire [0:0]  reconfig_read,           //                       .read,                  Reconfiguration read.
		input  wire [17:0] reconfig_address,        //                       .address,               Reconfiguration word address.
		input  wire [3:0]  reconfig_be,             //                       .byteenable,            Reconfiguration byte enable. If byteenable[3:0] is 4`b1111, 32-bit Dword Access is assumed; otherwise byte access will be used.
		input  wire [31:0] reconfig_writedata,      //                       .writedata,             Reconfiguration write data.
		output wire [31:0] reconfig_readdata,       //                       .readdata,              Reconfiguration read data.
		output wire [0:0]  reconfig_waitrequest,    //                       .waitrequest,           Reconfiguration wait request.
		output wire [0:0]  reconfig_readdata_valid  //                       .readdatavalid,         Reconfiguration read data valid. Optional port, available if the port is enabled in parameter editor.
	);

	alt_mge_phy_0_intel_mge_phy_100_mdesbaq #(
		.ENABLE_GMII_ADAPTER (1),
		.ENABLE_DL           (0)
	) alt_mge_phy_0 (
		.csr_clk                 (csr_clk),                 //   input,   width = 1,                csr_clk.clk
		.gmii8b_tx_clkin         (gmii8b_tx_clkin),         //   input,   width = 1,        gmii8b_tx_clkin.clk
		.tx_clkout               (tx_clkout),               //  output,   width = 1,              tx_clkout.clk
		.rx_clkout               (rx_clkout),               //  output,   width = 1,              rx_clkout.clk
		.gmii8b_tx_rst_n         (gmii8b_tx_rst_n),         //   input,   width = 1,        gmii8b_tx_rst_n.gmii8b_tx_rst_n
		.gmii8b_rx_rst_n         (gmii8b_rx_rst_n),         //   input,   width = 1,        gmii8b_rx_rst_n.gmii8b_rx_rst_n
		.gmii8b_rx_clkout        (gmii8b_rx_clkout),        //  output,   width = 1,       gmii8b_rx_clkout.clk
		.gmii8b_tx_clkout        (gmii8b_tx_clkout),        //  output,   width = 1,       gmii8b_tx_clkout.clk
		.reset                   (reset),                   //   input,   width = 1,                  reset.reset
		.rx_digitalreset         (rx_digitalreset),         //   input,   width = 1,        rx_digitalreset.rx_digitalreset
		.tx_digitalreset         (tx_digitalreset),         //   input,   width = 1,        tx_digitalreset.tx_digitalreset
		.csr_readdata            (csr_readdata),            //  output,  width = 16,          avalon_mm_csr.readdata
		.csr_writedata           (csr_writedata),           //   input,  width = 16,                       .writedata
		.csr_address             (csr_address),             //   input,   width = 5,                       .address
		.csr_waitrequest         (csr_waitrequest),         //  output,   width = 1,                       .waitrequest
		.csr_read                (csr_read),                //   input,   width = 1,                       .read
		.csr_write               (csr_write),               //   input,   width = 1,                       .write
		.gmii8b_mac_txen         (gmii8b_mac_txen),         //   input,   width = 1,        gmii8b_mac_txen.export
		.gmii8b_mac_tx_d         (gmii8b_mac_tx_d),         //   input,   width = 8,        gmii8b_mac_tx_d.export
		.gmii8b_mac_txer         (gmii8b_mac_txer),         //   input,   width = 1,        gmii8b_mac_txer.export
		.gmii8b_mac_rxdv         (gmii8b_mac_rxdv),         //  output,   width = 1,        gmii8b_mac_rxdv.export
		.gmii8b_mac_rxd          (gmii8b_mac_rxd),          //  output,   width = 8,         gmii8b_mac_rxd.export
		.gmii8b_mac_rxer         (gmii8b_mac_rxer),         //  output,   width = 1,        gmii8b_mac_rxer.export
		.gmii8b_mac_speed        (gmii8b_mac_speed),        //   input,   width = 2,       gmii8b_mac_speed.export
		.led_link                (led_link),                //  output,   width = 1,               led_link.export
		.led_char_err            (led_char_err),            //  output,   width = 1,           led_char_err.export
		.led_disp_err            (led_disp_err),            //  output,   width = 1,           led_disp_err.export
		.led_an                  (led_an),                  //  output,   width = 1,                 led_an.export
		.operating_speed         (operating_speed),         //  output,   width = 3,        operating_speed.export
		.mrphy_pll_lock          (mrphy_pll_lock),          //  output,   width = 1,         mrphy_pll_lock.pll_locked_stable
		.i_src_ch_pause_request  (i_src_ch_pause_request),  //   input,   width = 1, i_src_ch_pause_request.o_src_ch_pause_request
		.o_src_ch_pause_grant    (o_src_ch_pause_grant),    //  output,   width = 1,   o_src_ch_pause_grant.i_src_ch_pause_grant
		.i_rst_n                 (i_rst_n),                 //   input,   width = 1,                i_rst_n.i_rst_n
		.o_rst_ack_n             (o_rst_ack_n),             //  output,   width = 1,            o_rst_ack_n.o_rst_ack_n
		.i_tx_rst_n              (i_tx_rst_n),              //   input,   width = 1,             i_tx_rst_n.i_tx_rst_n
		.i_rx_rst_n              (i_rx_rst_n),              //   input,   width = 1,             i_rx_rst_n.i_rx_rst_n
		.o_tx_rst_ack_n          (o_tx_rst_ack_n),          //  output,   width = 1,         o_tx_rst_ack_n.o_tx_rst_ack_n
		.o_rx_rst_ack_n          (o_rx_rst_ack_n),          //  output,   width = 1,         o_rx_rst_ack_n.o_rx_rst_ack_n
		.rx_cdr_refclk_p         (rx_cdr_refclk_p),         //   input,   width = 1,        rx_cdr_refclk_p.clk
		.tx_ready                (tx_ready),                //  output,   width = 1,               tx_ready.tx_ready
		.rx_ready                (rx_ready),                //  output,   width = 1,               rx_ready.rx_ready
		.rx_pma_clkout           (rx_pma_clkout),           //  output,   width = 1,          rx_pma_clkout.clk
		.xcvr_mode               (xcvr_mode),               //   input,   width = 2,              xcvr_mode.export
		.tx_pll_refclk_p         (tx_pll_refclk_p),         //   input,   width = 1,        tx_pll_refclk_p.clk
		.i_pma_cu_clk            (i_pma_cu_clk),            //   input,   width = 1,           i_pma_cu_clk.clk
		.i_system_pll_clk        (i_system_pll_clk),        //   input,   width = 1,       i_system_pll_clk.clk
		.i_system_pll_lock       (i_system_pll_lock),       //   input,   width = 1,      i_system_pll_lock.system_pll_lock
		.i_src_rs_grant          (i_src_rs_grant),          //   input,   width = 1,         i_src_rs_grant.src_rs_grant
		.o_src_rs_req            (o_src_rs_req),            //  output,   width = 1,           o_src_rs_req.src_rs_req
		.tx_serial_data          (tx_serial_data),          //  output,   width = 1,         tx_serial_data.o_tx_serial_data
		.tx_serial_data_n        (tx_serial_data_n),        //  output,   width = 1,       tx_serial_data_n.o_tx_serial_data_n
		.rx_serial_data          (rx_serial_data),          //   input,   width = 1,         rx_serial_data.i_rx_serial_data
		.rx_serial_data_n        (rx_serial_data_n),        //   input,   width = 1,       rx_serial_data_n.i_rx_serial_data_n
		.rx_is_lockedtodata      (rx_is_lockedtodata),      //  output,   width = 1,     rx_is_lockedtodata.o_rx_is_lockedtodata
		.reconfig_clk            (reconfig_clk),            //   input,   width = 1,           reconfig_clk.clk
		.reconfig_reset          (reconfig_reset),          //   input,   width = 1,         reconfig_reset.reset
		.reconfig_write          (reconfig_write),          //   input,   width = 1,               reconfig.write
		.reconfig_read           (reconfig_read),           //   input,   width = 1,                       .read
		.reconfig_address        (reconfig_address),        //   input,  width = 18,                       .address
		.reconfig_be             (reconfig_be),             //   input,   width = 4,                       .byteenable
		.reconfig_writedata      (reconfig_writedata),      //   input,  width = 32,                       .writedata
		.reconfig_readdata       (reconfig_readdata),       //  output,  width = 32,                       .readdata
		.reconfig_waitrequest    (reconfig_waitrequest),    //  output,   width = 1,                       .waitrequest
		.reconfig_readdata_valid (reconfig_readdata_valid)  //  output,   width = 1,                       .readdatavalid
	);

endmodule
