// alt_mge_rd_avmm_mux_xcvr_rcfg.v

// Generated using ACDS version 21.4 67

`timescale 1 ps / 1 ps
module alt_mge_rd_avmm_mux_xcvr_rcfg (
		input  wire        csr_clk_clk,                  //          csr_clk.clk
		input  wire        csr_clk_reset_reset_n,        //    csr_clk_reset.reset_n
		input  wire [9:0]  mge_rcfg_master_address,      //  mge_rcfg_master.address
		output wire        mge_rcfg_master_waitrequest,  //                 .waitrequest
		input  wire        mge_rcfg_master_read,         //                 .read
		output wire [31:0] mge_rcfg_master_readdata,     //                 .readdata
		input  wire        mge_rcfg_master_write,        //                 .write
		input  wire [31:0] mge_rcfg_master_writedata,    //                 .writedata
		input  wire [9:0]  user_rcfg_master_address,     // user_rcfg_master.address
		output wire        user_rcfg_master_waitrequest, //                 .waitrequest
		input  wire        user_rcfg_master_read,        //                 .read
		output wire [31:0] user_rcfg_master_readdata,    //                 .readdata
		input  wire        user_rcfg_master_write,       //                 .write
		input  wire [31:0] user_rcfg_master_writedata,   //                 .writedata
		output wire [9:0]  xcvr_rcfg_slave_address,      //  xcvr_rcfg_slave.address
		output wire        xcvr_rcfg_slave_write,        //                 .write
		output wire        xcvr_rcfg_slave_read,         //                 .read
		input  wire [31:0] xcvr_rcfg_slave_readdata,     //                 .readdata
		output wire [31:0] xcvr_rcfg_slave_writedata,    //                 .writedata
		input  wire        xcvr_rcfg_slave_waitrequest   //                 .waitrequest
	);

	wire         csr_clk_clk_clk;                                                          // csr_clk:clk_out -> [mge_rcfg_master:clk, mm_interconnect_0:csr_clk_clk_clk, rst_controller:clk, user_rcfg_master:clk, xcvr_rcfg_slave:clk]
	wire         user_rcfg_master_avalon_universal_master_0_waitrequest;                   // mm_interconnect_0:user_rcfg_master_avalon_universal_master_0_waitrequest -> user_rcfg_master:uav_waitrequest
	wire  [31:0] user_rcfg_master_avalon_universal_master_0_readdata;                      // mm_interconnect_0:user_rcfg_master_avalon_universal_master_0_readdata -> user_rcfg_master:uav_readdata
	wire         user_rcfg_master_avalon_universal_master_0_debugaccess;                   // user_rcfg_master:uav_debugaccess -> mm_interconnect_0:user_rcfg_master_avalon_universal_master_0_debugaccess
	wire  [11:0] user_rcfg_master_avalon_universal_master_0_address;                       // user_rcfg_master:uav_address -> mm_interconnect_0:user_rcfg_master_avalon_universal_master_0_address
	wire         user_rcfg_master_avalon_universal_master_0_read;                          // user_rcfg_master:uav_read -> mm_interconnect_0:user_rcfg_master_avalon_universal_master_0_read
	wire   [3:0] user_rcfg_master_avalon_universal_master_0_byteenable;                    // user_rcfg_master:uav_byteenable -> mm_interconnect_0:user_rcfg_master_avalon_universal_master_0_byteenable
	wire         user_rcfg_master_avalon_universal_master_0_readdatavalid;                 // mm_interconnect_0:user_rcfg_master_avalon_universal_master_0_readdatavalid -> user_rcfg_master:uav_readdatavalid
	wire         user_rcfg_master_avalon_universal_master_0_lock;                          // user_rcfg_master:uav_lock -> mm_interconnect_0:user_rcfg_master_avalon_universal_master_0_lock
	wire         user_rcfg_master_avalon_universal_master_0_write;                         // user_rcfg_master:uav_write -> mm_interconnect_0:user_rcfg_master_avalon_universal_master_0_write
	wire  [31:0] user_rcfg_master_avalon_universal_master_0_writedata;                     // user_rcfg_master:uav_writedata -> mm_interconnect_0:user_rcfg_master_avalon_universal_master_0_writedata
	wire   [2:0] user_rcfg_master_avalon_universal_master_0_burstcount;                    // user_rcfg_master:uav_burstcount -> mm_interconnect_0:user_rcfg_master_avalon_universal_master_0_burstcount
	wire         mge_rcfg_master_avalon_universal_master_0_waitrequest;                    // mm_interconnect_0:mge_rcfg_master_avalon_universal_master_0_waitrequest -> mge_rcfg_master:uav_waitrequest
	wire  [31:0] mge_rcfg_master_avalon_universal_master_0_readdata;                       // mm_interconnect_0:mge_rcfg_master_avalon_universal_master_0_readdata -> mge_rcfg_master:uav_readdata
	wire         mge_rcfg_master_avalon_universal_master_0_debugaccess;                    // mge_rcfg_master:uav_debugaccess -> mm_interconnect_0:mge_rcfg_master_avalon_universal_master_0_debugaccess
	wire  [11:0] mge_rcfg_master_avalon_universal_master_0_address;                        // mge_rcfg_master:uav_address -> mm_interconnect_0:mge_rcfg_master_avalon_universal_master_0_address
	wire         mge_rcfg_master_avalon_universal_master_0_read;                           // mge_rcfg_master:uav_read -> mm_interconnect_0:mge_rcfg_master_avalon_universal_master_0_read
	wire   [3:0] mge_rcfg_master_avalon_universal_master_0_byteenable;                     // mge_rcfg_master:uav_byteenable -> mm_interconnect_0:mge_rcfg_master_avalon_universal_master_0_byteenable
	wire         mge_rcfg_master_avalon_universal_master_0_readdatavalid;                  // mm_interconnect_0:mge_rcfg_master_avalon_universal_master_0_readdatavalid -> mge_rcfg_master:uav_readdatavalid
	wire         mge_rcfg_master_avalon_universal_master_0_lock;                           // mge_rcfg_master:uav_lock -> mm_interconnect_0:mge_rcfg_master_avalon_universal_master_0_lock
	wire         mge_rcfg_master_avalon_universal_master_0_write;                          // mge_rcfg_master:uav_write -> mm_interconnect_0:mge_rcfg_master_avalon_universal_master_0_write
	wire  [31:0] mge_rcfg_master_avalon_universal_master_0_writedata;                      // mge_rcfg_master:uav_writedata -> mm_interconnect_0:mge_rcfg_master_avalon_universal_master_0_writedata
	wire   [2:0] mge_rcfg_master_avalon_universal_master_0_burstcount;                     // mge_rcfg_master:uav_burstcount -> mm_interconnect_0:mge_rcfg_master_avalon_universal_master_0_burstcount
	wire  [31:0] mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_readdata;      // xcvr_rcfg_slave:uav_readdata -> mm_interconnect_0:xcvr_rcfg_slave_avalon_universal_slave_0_readdata
	wire         mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_waitrequest;   // xcvr_rcfg_slave:uav_waitrequest -> mm_interconnect_0:xcvr_rcfg_slave_avalon_universal_slave_0_waitrequest
	wire         mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_debugaccess;   // mm_interconnect_0:xcvr_rcfg_slave_avalon_universal_slave_0_debugaccess -> xcvr_rcfg_slave:uav_debugaccess
	wire  [11:0] mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_address;       // mm_interconnect_0:xcvr_rcfg_slave_avalon_universal_slave_0_address -> xcvr_rcfg_slave:uav_address
	wire         mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_read;          // mm_interconnect_0:xcvr_rcfg_slave_avalon_universal_slave_0_read -> xcvr_rcfg_slave:uav_read
	wire   [3:0] mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_byteenable;    // mm_interconnect_0:xcvr_rcfg_slave_avalon_universal_slave_0_byteenable -> xcvr_rcfg_slave:uav_byteenable
	wire         mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_readdatavalid; // xcvr_rcfg_slave:uav_readdatavalid -> mm_interconnect_0:xcvr_rcfg_slave_avalon_universal_slave_0_readdatavalid
	wire         mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_lock;          // mm_interconnect_0:xcvr_rcfg_slave_avalon_universal_slave_0_lock -> xcvr_rcfg_slave:uav_lock
	wire         mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_write;         // mm_interconnect_0:xcvr_rcfg_slave_avalon_universal_slave_0_write -> xcvr_rcfg_slave:uav_write
	wire  [31:0] mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_writedata;     // mm_interconnect_0:xcvr_rcfg_slave_avalon_universal_slave_0_writedata -> xcvr_rcfg_slave:uav_writedata
	wire   [2:0] mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_burstcount;    // mm_interconnect_0:xcvr_rcfg_slave_avalon_universal_slave_0_burstcount -> xcvr_rcfg_slave:uav_burstcount
	wire         rst_controller_reset_out_reset;                                           // rst_controller:reset_out -> [mge_rcfg_master:reset, mm_interconnect_0:user_rcfg_master_reset_reset_bridge_in_reset_reset, user_rcfg_master:reset, xcvr_rcfg_slave:reset]
	wire         csr_clk_clk_reset_reset;                                                  // csr_clk:reset_n_out -> rst_controller:reset_in0

	alt_mge_rd_avmm_mux_xcvr_rcfg_csr_clk csr_clk (
		.clk_out     (csr_clk_clk_clk),         //  output,  width = 1,          clk.clk
		.in_clk      (csr_clk_clk),             //   input,  width = 1,       clk_in.clk
		.reset_n     (csr_clk_reset_reset_n),   //   input,  width = 1, clk_in_reset.reset_n
		.reset_n_out (csr_clk_clk_reset_reset)  //  output,  width = 1,    clk_reset.reset_n
	);

	alt_mge_rd_avmm_mux_xcvr_rcfg_mge_rcfg_master mge_rcfg_master (
		.av_address        (mge_rcfg_master_address),                                 //   input,  width = 10,      avalon_anti_master_0.address
		.av_waitrequest    (mge_rcfg_master_waitrequest),                             //  output,   width = 1,                          .waitrequest
		.av_read           (mge_rcfg_master_read),                                    //   input,   width = 1,                          .read
		.av_readdata       (mge_rcfg_master_readdata),                                //  output,  width = 32,                          .readdata
		.av_write          (mge_rcfg_master_write),                                   //   input,   width = 1,                          .write
		.av_writedata      (mge_rcfg_master_writedata),                               //   input,  width = 32,                          .writedata
		.uav_address       (mge_rcfg_master_avalon_universal_master_0_address),       //  output,  width = 12, avalon_universal_master_0.address
		.uav_burstcount    (mge_rcfg_master_avalon_universal_master_0_burstcount),    //  output,   width = 3,                          .burstcount
		.uav_read          (mge_rcfg_master_avalon_universal_master_0_read),          //  output,   width = 1,                          .read
		.uav_write         (mge_rcfg_master_avalon_universal_master_0_write),         //  output,   width = 1,                          .write
		.uav_waitrequest   (mge_rcfg_master_avalon_universal_master_0_waitrequest),   //   input,   width = 1,                          .waitrequest
		.uav_readdatavalid (mge_rcfg_master_avalon_universal_master_0_readdatavalid), //   input,   width = 1,                          .readdatavalid
		.uav_byteenable    (mge_rcfg_master_avalon_universal_master_0_byteenable),    //  output,   width = 4,                          .byteenable
		.uav_readdata      (mge_rcfg_master_avalon_universal_master_0_readdata),      //   input,  width = 32,                          .readdata
		.uav_writedata     (mge_rcfg_master_avalon_universal_master_0_writedata),     //  output,  width = 32,                          .writedata
		.uav_lock          (mge_rcfg_master_avalon_universal_master_0_lock),          //  output,   width = 1,                          .lock
		.uav_debugaccess   (mge_rcfg_master_avalon_universal_master_0_debugaccess),   //  output,   width = 1,                          .debugaccess
		.clk               (csr_clk_clk_clk),                                         //   input,   width = 1,                       clk.clk
		.reset             (rst_controller_reset_out_reset)                           //   input,   width = 1,                     reset.reset
	);

	alt_mge_rd_avmm_mux_xcvr_rcfg_user_rcfg_master user_rcfg_master (
		.av_address        (user_rcfg_master_address),                                 //   input,  width = 10,      avalon_anti_master_0.address
		.av_waitrequest    (user_rcfg_master_waitrequest),                             //  output,   width = 1,                          .waitrequest
		.av_read           (user_rcfg_master_read),                                    //   input,   width = 1,                          .read
		.av_readdata       (user_rcfg_master_readdata),                                //  output,  width = 32,                          .readdata
		.av_write          (user_rcfg_master_write),                                   //   input,   width = 1,                          .write
		.av_writedata      (user_rcfg_master_writedata),                               //   input,  width = 32,                          .writedata
		.uav_address       (user_rcfg_master_avalon_universal_master_0_address),       //  output,  width = 12, avalon_universal_master_0.address
		.uav_burstcount    (user_rcfg_master_avalon_universal_master_0_burstcount),    //  output,   width = 3,                          .burstcount
		.uav_read          (user_rcfg_master_avalon_universal_master_0_read),          //  output,   width = 1,                          .read
		.uav_write         (user_rcfg_master_avalon_universal_master_0_write),         //  output,   width = 1,                          .write
		.uav_waitrequest   (user_rcfg_master_avalon_universal_master_0_waitrequest),   //   input,   width = 1,                          .waitrequest
		.uav_readdatavalid (user_rcfg_master_avalon_universal_master_0_readdatavalid), //   input,   width = 1,                          .readdatavalid
		.uav_byteenable    (user_rcfg_master_avalon_universal_master_0_byteenable),    //  output,   width = 4,                          .byteenable
		.uav_readdata      (user_rcfg_master_avalon_universal_master_0_readdata),      //   input,  width = 32,                          .readdata
		.uav_writedata     (user_rcfg_master_avalon_universal_master_0_writedata),     //  output,  width = 32,                          .writedata
		.uav_lock          (user_rcfg_master_avalon_universal_master_0_lock),          //  output,   width = 1,                          .lock
		.uav_debugaccess   (user_rcfg_master_avalon_universal_master_0_debugaccess),   //  output,   width = 1,                          .debugaccess
		.clk               (csr_clk_clk_clk),                                          //   input,   width = 1,                       clk.clk
		.reset             (rst_controller_reset_out_reset)                            //   input,   width = 1,                     reset.reset
	);

	alt_mge_rd_avmm_mux_xcvr_rcfg_xcvr_rcfg_slave xcvr_rcfg_slave (
		.av_address        (xcvr_rcfg_slave_address),                                                  //  output,  width = 10,      avalon_anti_slave_0.address
		.av_write          (xcvr_rcfg_slave_write),                                                    //  output,   width = 1,                         .write
		.av_read           (xcvr_rcfg_slave_read),                                                     //  output,   width = 1,                         .read
		.av_readdata       (xcvr_rcfg_slave_readdata),                                                 //   input,  width = 32,                         .readdata
		.av_writedata      (xcvr_rcfg_slave_writedata),                                                //  output,  width = 32,                         .writedata
		.av_waitrequest    (xcvr_rcfg_slave_waitrequest),                                              //   input,   width = 1,                         .waitrequest
		.uav_address       (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_address),       //   input,  width = 12, avalon_universal_slave_0.address
		.uav_burstcount    (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_burstcount),    //   input,   width = 3,                         .burstcount
		.uav_read          (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_read),          //   input,   width = 1,                         .read
		.uav_write         (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_write),         //   input,   width = 1,                         .write
		.uav_waitrequest   (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_waitrequest),   //  output,   width = 1,                         .waitrequest
		.uav_readdatavalid (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_readdatavalid), //  output,   width = 1,                         .readdatavalid
		.uav_byteenable    (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_byteenable),    //   input,   width = 4,                         .byteenable
		.uav_readdata      (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_readdata),      //  output,  width = 32,                         .readdata
		.uav_writedata     (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_writedata),     //   input,  width = 32,                         .writedata
		.uav_lock          (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_lock),          //   input,   width = 1,                         .lock
		.uav_debugaccess   (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_debugaccess),   //   input,   width = 1,                         .debugaccess
		.clk               (csr_clk_clk_clk),                                                          //   input,   width = 1,                      clk.clk
		.reset             (rst_controller_reset_out_reset)                                            //   input,   width = 1,                    reset.reset
	);

	alt_mge_rd_avmm_mux_xcvr_rcfg_altera_mm_interconnect_1920_jyqwl7a mm_interconnect_0 (
		.user_rcfg_master_avalon_universal_master_0_address       (user_rcfg_master_avalon_universal_master_0_address),                       //   input,  width = 12,   user_rcfg_master_avalon_universal_master_0.address
		.user_rcfg_master_avalon_universal_master_0_waitrequest   (user_rcfg_master_avalon_universal_master_0_waitrequest),                   //  output,   width = 1,                                             .waitrequest
		.user_rcfg_master_avalon_universal_master_0_burstcount    (user_rcfg_master_avalon_universal_master_0_burstcount),                    //   input,   width = 3,                                             .burstcount
		.user_rcfg_master_avalon_universal_master_0_byteenable    (user_rcfg_master_avalon_universal_master_0_byteenable),                    //   input,   width = 4,                                             .byteenable
		.user_rcfg_master_avalon_universal_master_0_read          (user_rcfg_master_avalon_universal_master_0_read),                          //   input,   width = 1,                                             .read
		.user_rcfg_master_avalon_universal_master_0_readdata      (user_rcfg_master_avalon_universal_master_0_readdata),                      //  output,  width = 32,                                             .readdata
		.user_rcfg_master_avalon_universal_master_0_readdatavalid (user_rcfg_master_avalon_universal_master_0_readdatavalid),                 //  output,   width = 1,                                             .readdatavalid
		.user_rcfg_master_avalon_universal_master_0_write         (user_rcfg_master_avalon_universal_master_0_write),                         //   input,   width = 1,                                             .write
		.user_rcfg_master_avalon_universal_master_0_writedata     (user_rcfg_master_avalon_universal_master_0_writedata),                     //   input,  width = 32,                                             .writedata
		.user_rcfg_master_avalon_universal_master_0_lock          (user_rcfg_master_avalon_universal_master_0_lock),                          //   input,   width = 1,                                             .lock
		.user_rcfg_master_avalon_universal_master_0_debugaccess   (user_rcfg_master_avalon_universal_master_0_debugaccess),                   //   input,   width = 1,                                             .debugaccess
		.mge_rcfg_master_avalon_universal_master_0_address        (mge_rcfg_master_avalon_universal_master_0_address),                        //   input,  width = 12,    mge_rcfg_master_avalon_universal_master_0.address
		.mge_rcfg_master_avalon_universal_master_0_waitrequest    (mge_rcfg_master_avalon_universal_master_0_waitrequest),                    //  output,   width = 1,                                             .waitrequest
		.mge_rcfg_master_avalon_universal_master_0_burstcount     (mge_rcfg_master_avalon_universal_master_0_burstcount),                     //   input,   width = 3,                                             .burstcount
		.mge_rcfg_master_avalon_universal_master_0_byteenable     (mge_rcfg_master_avalon_universal_master_0_byteenable),                     //   input,   width = 4,                                             .byteenable
		.mge_rcfg_master_avalon_universal_master_0_read           (mge_rcfg_master_avalon_universal_master_0_read),                           //   input,   width = 1,                                             .read
		.mge_rcfg_master_avalon_universal_master_0_readdata       (mge_rcfg_master_avalon_universal_master_0_readdata),                       //  output,  width = 32,                                             .readdata
		.mge_rcfg_master_avalon_universal_master_0_readdatavalid  (mge_rcfg_master_avalon_universal_master_0_readdatavalid),                  //  output,   width = 1,                                             .readdatavalid
		.mge_rcfg_master_avalon_universal_master_0_write          (mge_rcfg_master_avalon_universal_master_0_write),                          //   input,   width = 1,                                             .write
		.mge_rcfg_master_avalon_universal_master_0_writedata      (mge_rcfg_master_avalon_universal_master_0_writedata),                      //   input,  width = 32,                                             .writedata
		.mge_rcfg_master_avalon_universal_master_0_lock           (mge_rcfg_master_avalon_universal_master_0_lock),                           //   input,   width = 1,                                             .lock
		.mge_rcfg_master_avalon_universal_master_0_debugaccess    (mge_rcfg_master_avalon_universal_master_0_debugaccess),                    //   input,   width = 1,                                             .debugaccess
		.xcvr_rcfg_slave_avalon_universal_slave_0_address         (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_address),       //  output,  width = 12,     xcvr_rcfg_slave_avalon_universal_slave_0.address
		.xcvr_rcfg_slave_avalon_universal_slave_0_write           (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_write),         //  output,   width = 1,                                             .write
		.xcvr_rcfg_slave_avalon_universal_slave_0_read            (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_read),          //  output,   width = 1,                                             .read
		.xcvr_rcfg_slave_avalon_universal_slave_0_readdata        (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_readdata),      //   input,  width = 32,                                             .readdata
		.xcvr_rcfg_slave_avalon_universal_slave_0_writedata       (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_writedata),     //  output,  width = 32,                                             .writedata
		.xcvr_rcfg_slave_avalon_universal_slave_0_burstcount      (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_burstcount),    //  output,   width = 3,                                             .burstcount
		.xcvr_rcfg_slave_avalon_universal_slave_0_byteenable      (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_byteenable),    //  output,   width = 4,                                             .byteenable
		.xcvr_rcfg_slave_avalon_universal_slave_0_readdatavalid   (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_readdatavalid), //   input,   width = 1,                                             .readdatavalid
		.xcvr_rcfg_slave_avalon_universal_slave_0_waitrequest     (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_waitrequest),   //   input,   width = 1,                                             .waitrequest
		.xcvr_rcfg_slave_avalon_universal_slave_0_lock            (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_lock),          //  output,   width = 1,                                             .lock
		.xcvr_rcfg_slave_avalon_universal_slave_0_debugaccess     (mm_interconnect_0_xcvr_rcfg_slave_avalon_universal_slave_0_debugaccess),   //  output,   width = 1,                                             .debugaccess
		.user_rcfg_master_reset_reset_bridge_in_reset_reset       (rst_controller_reset_out_reset),                                           //   input,   width = 1, user_rcfg_master_reset_reset_bridge_in_reset.reset
		.csr_clk_clk_clk                                          (csr_clk_clk_clk)                                                           //   input,   width = 1,                                  csr_clk_clk.clk
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~csr_clk_clk_reset_reset),       //   input,  width = 1, reset_in0.reset
		.clk            (csr_clk_clk_clk),                //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_reset_out_reset), //  output,  width = 1, reset_out.reset
		.reset_req      (),                               // (terminated),                       
		.reset_req_in0  (1'b0),                           // (terminated),                       
		.reset_in1      (1'b0),                           // (terminated),                       
		.reset_req_in1  (1'b0),                           // (terminated),                       
		.reset_in2      (1'b0),                           // (terminated),                       
		.reset_req_in2  (1'b0),                           // (terminated),                       
		.reset_in3      (1'b0),                           // (terminated),                       
		.reset_req_in3  (1'b0),                           // (terminated),                       
		.reset_in4      (1'b0),                           // (terminated),                       
		.reset_req_in4  (1'b0),                           // (terminated),                       
		.reset_in5      (1'b0),                           // (terminated),                       
		.reset_req_in5  (1'b0),                           // (terminated),                       
		.reset_in6      (1'b0),                           // (terminated),                       
		.reset_req_in6  (1'b0),                           // (terminated),                       
		.reset_in7      (1'b0),                           // (terminated),                       
		.reset_req_in7  (1'b0),                           // (terminated),                       
		.reset_in8      (1'b0),                           // (terminated),                       
		.reset_req_in8  (1'b0),                           // (terminated),                       
		.reset_in9      (1'b0),                           // (terminated),                       
		.reset_req_in9  (1'b0),                           // (terminated),                       
		.reset_in10     (1'b0),                           // (terminated),                       
		.reset_req_in10 (1'b0),                           // (terminated),                       
		.reset_in11     (1'b0),                           // (terminated),                       
		.reset_req_in11 (1'b0),                           // (terminated),                       
		.reset_in12     (1'b0),                           // (terminated),                       
		.reset_req_in12 (1'b0),                           // (terminated),                       
		.reset_in13     (1'b0),                           // (terminated),                       
		.reset_req_in13 (1'b0),                           // (terminated),                       
		.reset_in14     (1'b0),                           // (terminated),                       
		.reset_req_in14 (1'b0),                           // (terminated),                       
		.reset_in15     (1'b0),                           // (terminated),                       
		.reset_req_in15 (1'b0)                            // (terminated),                       
	);

endmodule
